class Locators:
    # VIEWS
    ui_main_app = "#HomeScreenView"
    restricted_access_view = "#noAccessView"
    
    main_app_view = "#HomeScreenAppApplicationStackView"
    toast_message_view = "#ToastWindowToastStackView"
    
    # APPS BUTTONS
    menu_app_button = "#8a6dc844-4138-4954-b0c0-0b791fc68587 MouseArea"
    menu_app_button_floating_dock = "#floatingDockButton"
    info_app_button = "#697749ba-b6ea-11eb-80d0-9ffe5c5f1620 MouseArea"
    network_app_button = "#a7965b73-7050-49b0-8450-cf27931959ba MouseArea"
    supplies_app_button = "#a5e59604-d216-4977-a901-4774fcacbcb4 MouseArea"
    media_app_button = "#60ce8d1a-64b1-4850-875b-5b9acfc95963 MouseArea"
    scan_usb_app_button = "#df4a8a01-7659-486f-95d5-e125ccd1529a MouseArea"
    scan_disk_app_button = "#dc711695-0441-4e1e-b059-6321a40cc6e0 MouseArea"
    scan_folder_app = "#D1AC8C3A-9503-44f8-AFD8-9FAC389F6E32 #launcherButton"
    scan_to_email_app = "#b8460c9e-43c8-4290-a0f8-8ce450867f09 #launcherButton"
    copy_app_button = "#cedab422-33b3-4638-b6a1-604e54525215 MouseArea" 
    job_queue_app = "#56ce9217-377d-4d5c-a950-a2ad37c07882"
    job_queue_app_button = "#56ce9217-377d-4d5c-a950-a2ad37c07882 MouseArea"
    job_storage_app_button = "#86DCD04A-5F44-4EAE-83C3-1C3C3F12E32B MouseArea"
    print_app_button = "#02FECD9A-7FE7-4797-AD15-8127DF2CFAAD MouseArea"
    gallery_app_button = "#8f22c7b6-a675-491b-ae16-b7010009231f MouseArea"
    quick_forms_app_button = "#6c8ddc45-4b4d-44cb-b5c9-f48a0574fe42"
    sign_in_app_button = "#7db992ba-557a-461c-b941-6023aa8cfa34 #launcherButton"
    sign_in_app_button_text = sign_in_app_button + " #labelText"
    fax_app_button = "#44aa632b-cfa3-4c10-8cab-697a9bef610b #launcherButton"
    restricted_access_ok_button = "#noAccessOkButton #ButtonControl"
    all_input_fields_required_ok_button = "#ConstraintMessage #okButton #ButtonControl"
    persistent_sign_in_button = "#HomeScreenView #persistentHeader #SignInButton"
    persistent_sign_out_button= "#HomeScreenView #persistentHeader #SignInButton"

    # BUTTONS
    home_button = "#HomeButton"
    usb_device_connected_ok_button = "#usbUnsupportedDeviceError #AlertFooter #OKButton #ButtonControl"
    web_app_home_button = "#webAppApplicationStackView #SpiceView #HeaderViewLeft #homeButton #ButtonControl"

    # TEXT
    all_input_fields_required_text_view = "#ConstraintMessage #constraintDescription SpiceText[visible=true]"
    all_input_fields_required_text = "All input fields are required."
    usb_device_connected_text_view = "#usbUnsupportedDeviceError #TitleText"
    usb_device_connected_text = "USB Device Connected"
    restricted_access_text_view = restricted_access_view + " #alertDetailDescription #contentItem"
    restricted_access_text = "This item is restricted. Try using another account, or contact the system administrator or the person who set up the printer."
    toast_message_text = toast_message_view + " SpiceText[visible=true]"

    # "Dynamics" Locators
    # Calibration print plot flow
    calibration_preparing_to_print = "#calibrationFlow_preparingToPrint"
    calibration_preparing_to_print_header = "#calibrationFlow_preparingToPrint #wizardProgressHeader SpiceText"
    calibration_preparing_to_print_content = "#calibrationFlow_preparingToPrint #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    calibration_printing = "#calibrationFlow_printingPattern"
    calibration_printing_header = "#calibrationFlow_printingPattern #wizardProgressHeader SpiceText"
    calibration_printing_content = "#calibrationFlow_printingPattern #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    calibration_scanning = "#calibrationFlow_scanningPattern"
    calibration_scanning_header = "#calibrationFlow_scanningPattern #wizardProgressHeader SpiceText"
    calibration_scanning_content = "#calibrationFlow_scanningPattern #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    calibration_preparing_intermediate_drying = "#calibrationFlow_intermediateDrying"
    calibration_preparing_intermediate_drying_header = "#calibrationFlow_intermediateDrying #wizardProgressHeader SpiceText"
    calibration_preparing_intermediate_drying_content = "#calibrationFlow_intermediateDrying #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    calibration_finishing = "#calibrationFlow_terminatingPattern"
    calibration_finishing_header = "#calibrationFlow_terminatingPattern #wizardProgressHeader SpiceText"
    calibration_finishing_content = "#calibrationFlow_terminatingPattern #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    calibration_finished_success = "#calibrationFlow_finishedSuccess"
    calibration_finished_success_header = "#calibrationFlow_finishedSuccess #wizardCompletionHeader SpiceText"
    calibration_finished_success_content_images = "#calibrationFlow_finishedSuccess #wizardCompletionImages SpiceImage"
    calibration_finished_success_content_texts = "#calibrationFlow_finishedSuccess #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    calibration_cancelling = "#calibrationFlow_cancelling"
    calibration_cancelling_header = "#calibrationFlow_cancelling #wizardProgressHeader SpiceText"
    calibration_cancelling_content = "#calibrationFlow_cancelling #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    calibration_align_configure_values = "#calibrationFlow_alignConfigureValues"
    calibration_align_configure_values_header = "#calibrationFlow_alignConfigureValues #alignConfigurationValuesHeader SpiceText"
    calibration_align_configure_values_content_contents_texts = "#calibrationFlow_alignConfigureValues #alignConfigurationValuesContentTexts #contentItem"
    calibration_finished_fail = "#calibrationFlow_finishedFail"
    calibration_finished_fail_header = "#calibrationFlow_finishedFail #wizardCompletionHeader SpiceText"
    calibration_finished_fail_content_images = "#calibrationFlow_finishedFail #wizardCompletionImages SpiceImage"
    calibration_finished_fail_content_texts = "#calibrationFlow_finishedFail #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    reset_calibrations_finished = "#calibrationEndProcess"
    reset_calibrations_finished_header = "#calibrationEndProcess #calibrationEndProcessHeader SpiceText"
    reset_calibrations_finished_content_images = "#calibrationEndProcess #wizardCompletionImages SpiceImage"
    calibration_help_message_non_hp_ink = "#calibrationFlow_helpMessage_nonHpInk"
    calibration_help_message_non_hp_ink_header = "#calibrationFlow_helpMessage_nonHpInk #TitleText SpiceText"
    calibration_help_message_non_hp_ink_content_contents_texts = "#calibrationFlow_helpMessage_nonHpInk #alertDetailDescription #contentItem"

    # Load single sheet flow
    load_single_sheet_load = "#loadSingleSheetFlow_load"
    load_single_sheet_load_header = "#loadSingleSheetFlow_load #wizardProgressHeader SpiceText"
    load_single_sheet_load_content = "#loadSingleSheetFlow_load #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_single_sheet_checking = "#loadSingleSheetFlow_checking"
    load_single_sheet_checking_header = "#loadSingleSheetFlow_checking #wizardProgressHeader SpiceText"
    load_single_sheet_checking_content = "#loadSingleSheetFlow_checking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_single_sheet_ask_media_info = "#loadSingleSheetFlow_askMediaInfo"

    # Load roll flow
    load_roll_resuming = "#loadRollFlow_resuming"
    load_roll_resuming_header = "#loadRollFlow_resuming #wizardProgressHeader SpiceText"
    load_roll_resuming_content = "#loadRollFlow_resuming #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_core_attached = "#loadRollFlow_coreAttached"
    load_roll_core_attached_header = "#loadRollFlow_coreAttached #wizardProgressHeader SpiceText"
    load_roll_core_attached_content = "#loadRollFlow_coreAttached #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_unload = "#loadRollFlow_unload"
    load_roll_unload_header = "#loadRollFlow_unload #wizardProgressHeader SpiceText"
    load_roll_unload_content = "#loadRollFlow_unload #ProgressPanel #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_preparing = "#loadRollFlow_preparing"
    load_roll_preparing_header = "#loadRollFlow_preparing #wizardProgressHeader SpiceText"
    load_roll_preparing_content = "#loadRollFlow_preparing #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_ask_media_info = "#loadRollFlow_askMediaInfo"
    load_roll_drawer_batch_load_details = "#loadRollFlow_batchLoadDetails"
    load_roll_wait_door_open = "#loadRollFlow_waitForCoverOpen"
    load_roll_wait_door_open_video = "#loadRollFlow_waitForCoverOpen #VideoLayout #VideoItem"
    load_roll_wait_drawer_open = "#loadRollFlow_waitForDrawerOpen"
    load_roll_wait_drawer_open_video = "#loadRollFlow_waitForDrawerOpen #VideoLayout #VideoItem"
    load_roll_feed = "#loadRollFlow_feed"
    load_roll_feed_video = "#loadRollFlow_feed #VideoLayout #VideoItem"
    load_roll_feed_drawer = "#loadRollFlow_feedDrawer"
    load_roll_feed_drawer_video = "#loadRollFlow_feedDrawer #VideoLayout #VideoItem"
    load_roll_remove_loading_accessory = "#loadRollFlow_errorremoveLoadingAccessory"
    load_roll_remove_loading_accessory_header = "#loadRollFlow_errorremoveLoadingAccessory #TitleText SpiceText"
    load_roll_remove_loading_accessory_content_contents_texts = "#loadRollFlow_errorremoveLoadingAccessory #alertDetailDescription #contentItem"
    load_roll_wait_door_closed = "#loadRollFlow_waitForDoorClose"
    load_roll_wait_door_closed_video = "#loadRollFlow_waitForDoorClose #VideoLayout #VideoItem"
    load_roll_wait_drawer_closed = "#loadRollFlow_waitForDrawerClose"
    load_roll_wait_drawer_closed_video = "#loadRollFlow_waitForDrawerClose #VideoLayout #VideoItem"
    load_roll_load = "#loadRollFlow_load"
    load_roll_load_header = "#loadRollFlow_load #wizardProgressHeader SpiceText"
    load_roll_load_content = "#loadRollFlow_load #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_checking = "#loadRollFlow_checking"
    load_roll_checking_header = "#loadRollFlow_checking #wizardProgressHeader SpiceText"
    load_roll_checking_content = "#loadRollFlow_checking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_form_feed_and_cut = "#loadRollFlow_formFeedAndCut"
    load_roll_form_feed_and_cut_header = "#loadRollFlow_formFeedAndCut #wizardProgressHeader SpiceText"
    load_roll_form_feed_and_cut_content = "#loadRollFlow_formFeedAndCut #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_select_options = "#loadRollFlow_errorselectOptions"
    load_roll_select_options_header = "#loadRollFlow_errorselectOptions #TitleText SpiceText"
    load_roll_select_options_content_contents_texts = "#loadRollFlow_errorselectOptions #alertDetailDescription #contentItem"
    load_roll_correcting = "#loadRollFlow_skewHandling"
    load_roll_correcting_header = "#loadRollFlow_skewHandling #wizardProgressHeader SpiceText"
    load_roll_correcting_content = "#loadRollFlow_skewHandling #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_processing = "#loadRollFlow_processing"
    load_roll_processing_header = "#loadRollFlow_processing #wizardProgressHeader SpiceText"
    load_roll_processing_content = "#loadRollFlow_processing #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_finished_ok = "#loadRollFlow_finished"
    load_roll_finished_ok_header = "#loadRollFlow_finished #wizardCompletionHeader SpiceText"
    load_roll_finished_ok_content_images = "#loadRollFlow_finished #wizardCompletionImages SpiceImage"
    load_roll_finished_ok_content_texts = "#loadRollFlow_finished #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    load_roll_load_recomendation_curing = "#loadRollFlow_errorloadRecomendationCuring"
    load_roll_load_recomendation_curing_header = "#loadRollFlow_errorloadRecomendationCuring #TitleText SpiceText"
    load_roll_load_recomendation_curing_content_contents_texts = "#loadRollFlow_errorloadRecomendationCuring #alertDetailDescription #contentItem"
    load_roll_load_recommendation_tur = "#loadRollFlow_errorloadRecomendationTur"
    load_roll_load_recommendation_tur_header = "#loadRollFlow_errorloadRecomendationTur #TitleText SpiceText"
    load_roll_load_recommendation_tur_content_contents_texts = "#loadRollFlow_errorloadRecomendationTur #alertDetailDescription #contentItem"
    load_roll_lateral_media_edge_not_found = "#loadRollFlow_errorlateralMediaEdgeNotFound"
    load_roll_lateral_media_edge_not_found_header = "#loadRollFlow_errorlateralMediaEdgeNotFound #TitleText SpiceText"
    load_roll_lateral_media_edge_not_found_content_contents_texts = "#loadRollFlow_errorlateralMediaEdgeNotFound #alertDetailDescription #contentItem"
    load_roll_error_load = "#loadRollFlow_errorload"
    load_roll_error_load_header = "#loadRollFlow_errorload #TitleText SpiceText"
    load_roll_error_load_content_contents_texts = "#loadRollFlow_errorload #alertDetailDescription #contentItem"
    load_roll_too_narrow = "#loadRollFlow_errorrollTooNarrow"
    load_roll_too_narrow_header = "#loadRollFlow_errorrollTooNarrow #TitleText SpiceText"
    load_roll_too_narrow_content_contents_texts = "#loadRollFlow_errorrollTooNarrow #alertDetailDescription #contentItem"
    load_roll_winding_dir_not_found = "#loadRollFlow_errorwindingDirNotFound"
    load_roll_winding_dir_not_found_header = "#loadRollFlow_errorwindingDirNotFound #TitleText SpiceText"
    load_roll_winding_dir_not_found_content_contents_texts = "#loadRollFlow_errorwindingDirNotFound #alertDetailDescription #contentItem"
    load_roll_front_media_edge_not_found = "#loadRollFlow_errorfrontMediaEdgeNotFound"
    load_roll_front_media_edge_not_found_header = "#loadRollFlow_errorfrontMediaEdgeNotFound #TitleText SpiceText"
    load_roll_front_media_edge_not_found_content_contents_texts = "#loadRollFlow_errorfrontMediaEdgeNotFound #alertDetailDescription #contentItem"
    load_roll_feeding_error = "#loadRollFlow_errorrollFeedingError"
    load_roll_feeding_error_header = "#loadRollFlow_errorrollFeedingError #TitleText SpiceText"
    load_roll_feeding_error_content_contents_texts = "#loadRollFlow_errorrollFeedingError #alertDetailDescription #contentItem"
    load_roll_width_detection_error = "#loadRollFlow_errorrollWidthDetectionError"
    load_roll_width_detection_error_header = "#loadRollFlow_errorrollWidthDetectionError #TitleText SpiceText"
    load_roll_width_detection_error_content_contents_texts = "#loadRollFlow_errorrollWidthDetectionError #alertDetailDescription #contentItem"
    load_roll_radious_out_of_range = "#loadRollFlow_errorrollRadiousOutOfRange"
    load_roll_radious_out_of_range_header = "#loadRollFlow_errorrollRadiousOutOfRange #TitleText SpiceText"
    load_roll_radious_out_of_range_content_contents_texts = "#loadRollFlow_errorrollRadiousOutOfRange #alertDetailDescription #contentItem"
    load_roll_core_attached_error = "#loadRollFlow_errorrollCoreAttachedError"
    load_roll_core_attached_error_header = "#loadRollFlow_errorrollCoreAttachedError #TitleText SpiceText"
    load_roll_core_attached_error_content_contents_texts = "#loadRollFlow_errorrollCoreAttachedError #alertDetailDescription #contentItem"
    load_roll_media_tracking_information_error = "#loadRollFlow_errormediaTrackingInformation"
    load_roll_media_tracking_information_error_content_contents_texts = "#loadRollFlow_errormediaTrackingInformation #alertDetailDescription #contentItem"
    load_roll_drawer_jam_modal = "#loadRollFlow_jamModal"
    load_roll_drawer_jam_modal_header = "#loadRollFlow_jamModal #TitleText SpiceText"
    load_roll_drawer_jam_modal_content_contents_texts = "#loadRollFlow_jamModal #alertDetailDescription #contentItem"
    load_roll_drawer_jam_modal_help_button = "#loadRollFlow_jamModal #helpButton"
    load_roll_drawer_jam_help_screen_modal = "#HelpVideoView"
    load_roll_drawer_jam_help_screen_video = "#HelpVideoView #VideoLayout #VideoItem"
    load_roll_jam_checking = "#loadRollFlow_jamChecking"
    load_roll_jam_checking_header = "#loadRollFlow_jamChecking #wizardProgressHeader SpiceText"
    load_roll_jam_checking_content = "#loadRollFlow_jamChecking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    load_roll_jam_resolved_successfully = "#loadRollFlow_jamSuccessfullySolved"
    load_roll_jam_resolved_successfully_header = "#loadRollFlow_jamSuccessfullySolved #wizardCompletionHeader SpiceText"
    load_roll_jam_resolved_successfully_content_images = "#loadRollFlow_jamSuccessfullySolved #wizardCompletionImages SpiceImage"
    load_roll_jam_resolved_successfully_content_texts = "#loadRollFlow_jamSuccessfullySolved #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    load_roll_open_curing_module = "#loadRollFlow_openCuringModule"
    load_roll_open_curing_module_header = "#loadRollFlow_openCuringModule #TitleText SpiceText"
    load_roll_open_curing_module_content_text = "#loadRollFlow_openCuringModule #alertDetailDescription #contentItem"
    load_roll_close_curing_module = "#loadRollFlow_closeCuringModule"
    load_roll_close_curing_module_header = "#loadRollFlow_closeCuringModule #TitleText SpiceText"
    load_roll_close_curing_module_content_text = "#loadRollFlow_closeCuringModule #alertDetailDescription #contentItem"
    load_roll_install_ink_collector_foams = "#loadRollFlow_installInkCollectorFoams"
    load_roll_install_ink_collector_foams_header = "#loadRollFlow_installInkCollectorFoams #TitleText SpiceText"
    load_roll_install_ink_collector_foams_content_text = "#loadRollFlow_installInkCollectorFoams #alertDetailDescription #contentItem"
    load_roll_uninstall_ink_collector_foams = "#loadRollFlow_uninstallInkCollectorFoams"
    load_roll_uninstall_ink_collector_foams_header = "#loadRollFlow_uninstallInkCollectorFoams #TitleText SpiceText"
    load_roll_uninstall_ink_collector_foams_content_text = "#loadRollFlow_uninstallInkCollectorFoams #alertDetailDescription #contentItem"

    # Maintenance cartridge flow
    maintenance_cartridge_to_start_cover = "#maintenanceCartridgeFlow_toStartCover"
    maintenance_cartridge_to_start_cover_header = "#maintenanceCartridgeFlow_toStartCover #TitleText SpiceText"
    maintenance_cartridge_to_start_cover_content_contents_texts = "#maintenanceCartridgeFlow_toStartCover #alertDetailDescription  SpiceText[visible=true]"
    maintenance_cartridge_to_start_cover_replace_button = "#maintenanceCartridgeFlow_toStartCover #startAction"
    maintenance_cartridge_wait_door_closed = "#maintenanceCartridgeFlow_waitForDoorClose"
    maintenance_cartridge_wait_door_closed_video = "#maintenanceCartridgeFlow_waitForDoorClose #VideoLayout #VideoItem"
    maintenance_cartridge_wait_user_confirmation = "#maintenanceCartridgeFlow_waitUserConfirmationToStart"
    maintenance_cartridge_wait_user_confirmation_header = "#maintenanceCartridgeFlow_waitUserConfirmationToStart #waitUserConfirmationHeader SpiceText"
    maintenance_cartridge_wait_user_confirmation_content_images = "#maintenanceCartridgeFlow_waitUserConfirmationToStart #waitUserConfirmationContent SpiceImage"
    maintenance_cartridge_wait_user_confirmation_content_contents_texts = "#maintenanceCartridgeFlow_waitUserConfirmationToStart #waitUserConfirmationContent #contentItem"
    maintenance_cartridge_wait_user_confirmation_start_button = "#maintenanceCartridgeFlow_waitUserConfirmationToStart #startAction"
    maintenance_cartridge_servicing_begin_mc_replacement = "#maintenanceCartridgeFlow_servicingBeginMCReplacement"
    maintenance_cartridge_servicing_begin_mc_replacement_progress_bar = "#maintenanceCartridgeFlow_servicingBeginMCReplacement #progressBar"
    maintenance_cartridge_servicing_begin_mc_replacement_content = "#maintenanceCartridgeFlow_servicingBeginMCReplacement #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    maintenance_cartridge_preparing = "#maintenanceCartridgeFlow_preparing"
    maintenance_cartridge_preparing_progress_bar = "#maintenanceCartridgeFlow_preparing #progressBar"
    maintenance_cartridge_preparing_content = "#maintenanceCartridgeFlow_preparing #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    maintenance_cartridge_wait_door_open = "#maintenanceCartridgeFlow_waitForDoorOpen"
    maintenance_cartridge_wait_door_open_video = "#maintenanceCartridgeFlow_waitForDoorOpen #VideoLayout #VideoItem"
    maintenance_cartridge_wait_for_mc_extraction = "#maintenanceCartridgeFlow_waitForMCExtraction"
    maintenance_cartridge_wait_for_mc_extraction_video = "#maintenanceCartridgeFlow_waitForMCExtraction #VideoLayout #VideoItem"
    maintenance_cartridge_wait_for_mc_insertion = "#maintenanceCartridgeFlow_waitForMCInsertion"
    maintenance_cartridge_wait_for_mc_insertion_video = "#maintenanceCartridgeFlow_waitForMCInsertion #VideoLayout #VideoItem"
    maintenance_cartridge_on_checking_mc_cause_not_detected = "#maintenanceCartridgeFlow_onCheckingMcCauseNotDetected"
    maintenance_cartridge_on_checking_mc_cause_not_detected_header = "#maintenanceCartridgeFlow_onCheckingMcCauseNotDetected #TitleText SpiceText"
    maintenance_cartridge_on_checking_mc_cause_not_detected_content_contents_texts = "#maintenanceCartridgeFlow_onCheckingMcCauseNotDetected #alertDetailDescription  SpiceText[visible=true]"
    maintenance_cartridge_on_checking_mc_cause_not_detected_continue_button = "#maintenanceCartridgeFlow_onCheckingMcCauseNotDetected #restartAction"
    maintenance_cartridge_on_checking_mc_cause_not_detected_ok_button = "#maintenanceCartridgeFlow_onCheckingMcCauseNotDetected #okAction"
    maintenance_cartridge_checking = "#maintenanceCartridgeFlow_checking"
    maintenance_cartridge_checking_progress_bar = "#maintenanceCartridgeFlow_checking #progressBar"
    maintenance_cartridge_checking_content = "#maintenanceCartridgeFlow_checking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    maintenance_cartridge_on_checking_mc_not_detected_persistent = "#maintenanceCartridgeFlow_onCheckingMcNotDetectedPersistent"
    maintenance_cartridge_on_checking_mc_not_detected_persistent_header = "#maintenanceCartridgeFlow_onCheckingMcNotDetectedPersistent #TitleText SpiceText"
    maintenance_cartridge_on_checking_mc_not_detected_persistent_content_contents_texts = "#maintenanceCartridgeFlow_onCheckingMcNotDetectedPersistent #alertDetailDescription #contentItem"
    maintenance_cartridge_on_checking_mc_cause_full = "#maintenanceCartridgeFlow_onCheckingMcCauseFull"
    maintenance_cartridge_on_checking_mc_cause_full_header = "#maintenanceCartridgeFlow_onCheckingMcCauseFull #TitleText SpiceText"
    maintenance_cartridge_on_checking_mc_cause_full_content_contents_texts = "#maintenanceCartridgeFlow_onCheckingMcCauseFull #alertDetailDescription #contentItem"
    maintenance_cartridge_servicing_end_of_mc_replacement = "#maintenanceCartridgeFlow_servicingEndMCReplacement"
    maintenance_cartridge_servicing_end_of_mc_replacement_progress_bar = "#maintenanceCartridgeFlow_servicingEndMCReplacement #progressBar"
    maintenance_cartridge_servicing_end_of_mc_replacement_content = "#maintenanceCartridgeFlow_servicingEndMCReplacement #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    maintenance_cartridge_finished_ok = "#maintenanceCartridgeFlow_finished"
    maintenance_cartridge_finished_ok_header = "#maintenanceCartridgeFlow_finished #wizardCompletionHeader SpiceText"
    maintenance_cartridge_finished_ok_content_images = "#maintenanceCartridgeFlow_finished #wizardCompletionImages SpiceImage"
    maintenance_cartridge_finished_ok_content_texts = "#maintenanceCartridgeFlow_finished #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    maintenance_cartridge_ask_user_input = "#maintenanceCartridgeFlow_askUserInput"
    maintenance_cartridge_ask_user_input_yes_button = "#maintenanceCartridgeFlow_askUserInput #okAction"
    maintenance_cartridge_wait_for_waste_collector_insertion = "#maintenanceCartridgeFlow_inkCollectionUnitWaitForInsertion"
    maintenance_cartridge_wait_for_waste_collector_insertion_video = "#maintenanceCartridgeFlow_inkCollectionUnitWaitForInsertion #VideoLayout #VideoItem"
    
    # Maintenance servicing flow
    maintenance_in_progress = "#servicingMaintenanceFlow_InProgress"
    maintenance_cancelling = "#servicingMaintenanceFlow_cancelling"
    maintenance_in_progress_progress = "#servicingMaintenanceFlow_InProgress #progressBar"
    maintenance_cancelling_progress = "#servicingMaintenanceFlow_cancelling #progressBar"
    maintenance_in_progress_header = "#servicingMaintenanceFlow_InProgress #wizardProgressHeader SpiceText"
    maintenance_cancelling_header = "#servicingMaintenanceFlow_cancelling #wizardProgressHeader SpiceText"
    
    # Printhead recovery flow
    printhead_recovery_printhead_inserted = "#phRecoveryFlow_selectPrintheads"
    printhead_recovery_printhead_inserted_header = "#phRecoveryFlow_selectPrintheads #printheadsContainerHeader SpiceText"
    printhead_recovery_printhead_inserted_ph_container_content = "#phRecoveryFlow_selectPrintheads #printheadsContainerContent"
    printhead_recovery_printhead_inserted_select_all_action = "#phRecoveryFlow_selectPrintheads #selectAllAction"
    printhead_recovery_printhead_checking = "#phRecoveryFlow_checking"
    printhead_recovery_printhead_checking_header = "#phRecoveryFlow_checking #wizardProgressHeader SpiceText"
    printhead_recovery_printhead_checking_content = "#phRecoveryFlow_checking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    printhead_recovery_printhead_finishing = "#phRecoveryFlow_finishing"
    printhead_recovery_printhead_finishing_header = "#phRecoveryFlow_finishing #TitleText SpiceText"
    printhead_recovery_printhead_finishing_content_contents_texts = "#phRecoveryFlow_finishing #alertDetailDescription #contentItem"
    printhead_recovery_printhead_finished_ok = "#phRecoveryFlow_finished"
    printhead_recovery_printhead_finished_ok_header = "#phRecoveryFlow_finished #wizardCompletionHeader SpiceText"
    printhead_recovery_printhead_finished_ok_content_images = "#phRecoveryFlow_finished #wizardCompletionImages SpiceImage"
    printhead_recovery_printhead_finished_ok_content_texts = "#phRecoveryFlow_finished #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    printhead_recovery_printhead_cancelling = "#phRecoveryFlow_cancelling"
    printhead_recovery_printhead_cancelling_header = "#phRecoveryFlow_cancelling #wizardProgressHeader SpiceText"
    printhead_recovery_printhead_cancelling_content = "#phRecoveryFlow_cancelling #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    printhead_recovery_printhead_cancelled = "#phRecoveryFlow_cancelled"
    printhead_recovery_printhead_cancelled_header = "#phRecoveryFlow_cancelled #wizardCompletionHeader SpiceText"
    printhead_recovery_printhead_cancelled_content_images = "#phRecoveryFlow_cancelled #wizardCompletionImages SpiceImage"
    printhead_recovery_printhead_cancelled_content_texts = "#phRecoveryFlow_cancelled #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"

    # Water tank flow
    water_tank_refill_how_to_instructions = "#waterTankRefill_howToInstructions"
    water_tank_refill_how_to_instructions_video = "#waterTankRefill_howToInstructions #VideoLayout #VideoItem"
    water_tank_refill_not_enough_water = "#waterTankRefill_notEnoughWater"
    water_tank_refill_not_enough_water_header = "#waterTankRefill_notEnoughWater #TitleText SpiceText"
    water_tank_refill_not_enough_water_content = "#waterTankRefill_notEnoughWater #alertDetailDescription #contentItem"
    water_tank_refill_not_enough_water_accept_action = "#waterTankRefill_howToInstructions #acceptAction"
    water_tank_refill_execute_liquid_dispenser_purge = "#waterTankRefill_executeLiquidDispenserPurge"
    water_tank_refill_execute_liquid_dispenser_purge_header = "#waterTankRefill_executeLiquidDispenserPurge #wizardProgressHeader SpiceText"
    water_tank_refill_execute_liquid_dispenser_purge_progress = "#waterTankRefill_executeLiquidDispenserPurge #progressBar"
    water_tank_refill_finished = "#waterTankRefill_finished"
    water_tank_refill_finished_header = "#waterTankRefill_finished #wizardCompletionHeader SpiceText"
    water_tank_refill_finished_content_images = "#waterTankRefill_finished #wizardCompletionImages SpiceImage"
    water_tank_refill_wait_for_door_open = "#waterTankRefill_waitForDoorOpen"
    water_tank_refill_wait_for_door_open_video = "#waterTankRefill_waitForDoorOpen #VideoLayout #VideoItem"
    water_tank_refill_wait_user_confirmation = "#waterTankRefill_recoveryCheck"
    water_tank_refill_wait_user_confirmation_header = "#waterTankRefill_recoveryCheck #TitleText SpiceText"
    water_tank_refill_wait_user_confirmation_accept_action = "#waterTankRefill_recoveryCheck #acceptAction"
    water_tank_refill_wait_user_confirmation_retry_action = "#waterTankRefill_recoveryCheck #repeatAction"
    water_tank_refill_wait_user_last_confirmation = "#waterTankRefill_lastRecoveryCheck"
    water_tank_refill_wait_user_last_confirmation_skip_action = "#waterTankRefill_lastRecoveryCheck #skipAction"
    water_tank_refill_wait_help_message_accept_action = "#waterTankRefill_purgeFailure #acceptAction"
    water_tank_refill_wait_for_door_close = "#waterTankRefill_waitForDoorClose"
    water_tank_refill_wait_for_door_close_video = "#waterTankRefill_waitForDoorClose #VideoLayout #VideoItem"


    # Printhead servicing flow
    servicing_ph_replacement_processing = "#servicingPrintheadReplacementFlow_processing"
    servicing_ph_replacement_processing_header = "#servicingPrintheadReplacementFlow_processing #wizardProgressHeader SpiceText"
    servicing_ph_replacement_processing_content = "#servicingPrintheadReplacementFlow_processing #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"

    home_dock_area = "#homeDock"
    home_dock_hscroll = "#hScroll"
    home_dock_hscrollbar = "#hScroll #hScrollhorizontalScroll"

     # ouptput stacker flow
    output_stacker_jam_modal = "#outputStackerFlow_jamModal"
    output_stacker_jam_checking = "#outputStackerFlow_jamChecking"
    output_stacker_jam_checking_header = "#outputStackerFlow_jamChecking #wizardProgressHeader SpiceText"
    output_stacker_jam_checking_content = "#outputStackerFlow_jamChecking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    output_stacker_jam_modal_header = "#outputStackerFlow_jamModal #TitleText SpiceText"
    output_stacker_jam_modal_content_contents_texts = "#outputStackerFlow_jamModal #alertDetailDescription #contentItem"
    output_stacker_jam_modal_help_button = "#outputStackerFlow_jamModal #helpButton"
    output_stacker_jam_help_screen_modal = "#HelpVideoView"
    output_stacker_jam_help_screen_video = "#HelpVideoView #VideoLayout #VideoItem"
    output_stacker_jam_help_screen_button = "#HelpVideoView #SpiceHeaderVar1 #rightBlockObject {}"
    output_stacker_jam_resolved_successfully = "#outputStackerFlow_jamSuccessfullySolved"
    output_stacker_jam_resolved_successfully_header = "#outputStackerFlow_jamSuccessfullySolved #wizardCompletionHeader SpiceText"
    output_stacker_jam_resolved_successfully_content_images = "#outputStackerFlow_jamSuccessfullySolved #wizardCompletionImages SpiceImage"
    output_stacker_jam_resolved_successfully_content_texts = "#outputStackerFlow_jamSuccessfullySolved #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"

     # ouptput basket flow
    output_basket_jam_modal = "#outputBasketFlow_jamModal"
    output_basket_jam_modal_header = "#outputBasketFlow_jamModal #TitleText SpiceText"
    output_basket_jam_modal_content_contents_texts = "#outputBasketFlow_jamModal #alertDetailDescription #contentItem"
    output_basket_jam_modal_help_button = "#outputBasketFlow_jamModal #helpButton"
    output_basket_jam_help_screen_modal = "#HelpVideoView"
    output_basket_jam_help_screen_video = "#HelpVideoView #VideoLayout #VideoItem"
    output_basket_jam_checking = "#outputBasketFlow_jamChecking"
    output_basket_jam_checking_header = "#outputBasketFlow_jamChecking #wizardProgressHeader SpiceText"
    output_basket_jam_checking_content = "#outputBasketFlow_jamChecking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    output_basket_jam_resolved_successfully = "#outputBasketFlow_jamSuccessfullySolved"
    output_basket_jam_resolved_successfully_header = "#outputBasketFlow_jamSuccessfullySolved #wizardCompletionHeader SpiceText"
    output_basket_jam_resolved_successfully_content_images = "#outputBasketFlow_jamSuccessfullySolved #wizardCompletionImages SpiceImage"
    output_basket_jam_resolved_successfully_content_texts = "#outputBasketFlow_jamSuccessfullySolved #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"

     # photostaking_mode flow
    photostaking_mode_attended_mode_screen = "#attendedModeRequired"
    photostaking_mode_cancel_screen = "#photoStakingModeFlow_cancel"
    
    photostaking_mode_attended_mode_continue_button = "#AttendedModeContunueButton"
    photostaking_mode_ok_button = "#okAction"
    photostaking_mode_cancel_button = "#cancelAction"
    photostaking_mode_cancel_button_yes = "#photoStakingModeFlow_cancel #cancelAction"

    photostaking_mode_printing = "#photoStakingModeFlow_printing"
    photostaking_mode_printing_header = "#photoStakingModeFlow_printing #wizardProgressHeader SpiceText"
    photostaking_mode_printing_content = "#photoStakingModeFlow_printing #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    photostaking_mode_canceling = "#photoStakingModeFlow_canceling"
    photostaking_mode_canceling_header = "#photoStakingModeFlow_canceling #wizardProgressHeader SpiceText"
    photostaking_mode_canceling_content = "#photoStakingModeFlow_canceling #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    photostaking_mode_collect = "#photoStakingModeFlow_collect"
    photostaking_mode_collect_header = "#photoStakingModeFlow_collect #wizardCompletionHeader SpiceText"
    photostaking_mode_collect_content_images = "#photoStakingModeFlow_collect #wizardCompletionImages SpiceImage"
    photostaking_mode_collect_content_texts = "#photoStakingModeFlow_collect #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    photostaking_mode_completed = "#photoStakingModeFlow_completed"
    photostaking_mode_completed_header = "#photoStakingModeFlow_completed #wizardCompletionHeader SpiceText"
    photostaking_mode_completed_content_images = "#photoStakingModeFlow_completed #wizardCompletionImages SpiceImage"
    photostaking_mode_completed_content_texts = "#photoStakingModeFlow_completed #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"

    # Move cut flow
    move_cut_preparing = "#moveAndCutMediaFlow_preparing"
    move_cut_preparing_progress_bar = "#moveAndCutMediaFlow_preparing #progressBar"
    move_cut_preparing_header = "#moveAndCutMediaFlow_preparing #wizardProgressHeader SpiceText"
    move_cut_preparing_content = "#moveAndCutMediaFlow_preparing #secondaryAreaTextImage #titleSmallItem"
    move_cut_ready = "#moveAndCutMediaFlow_ready"
    move_cut_ready_header = "#moveAndCutMediaFlow_ready #TitleText SpiceText"
    move_cut_ready_content_description = "#moveAndCutMediaFlow_ready #alertDetailDescription SpiceText[visible=true]"
    move_cut_ready_content_image = "#moveAndCutMediaFlow_ready #alertStatusImage SpiceImage"
    move_cut_ready_up_action = "#moveAndCutMediaFlow_ready #FooterView #upAction"
    move_cut_ready_down_action = "#moveAndCutMediaFlow_ready #FooterView #downAction"
    move_cut_ready_cut_action = "#moveAndCutMediaFlow_ready #FooterView #cutAction"
    move_cut_form_feed_and_cut = "#moveAndCutMediaFlow_cutting #progressBar"
    move_cut_form_feed_and_cut_progress_bar = "#moveAndCutMediaFlow_cutting #progressBar"
    move_cut_form_feed_and_cut_header = "#moveAndCutMediaFlow_cutting #wizardProgressHeader SpiceText"
    move_cut_form_feed_and_cut_content = "#moveAndCutMediaFlow_cutting #secondaryAreaTextImage #titleSmallItem"
    move_cut_media_cannot_be_cut = "#moveAndCutMediaFlow_cannotBeCut"
    move_cut_media_cannot_be_cut_header = "#moveAndCutMediaFlow_cannotBeCut #TitleText SpiceText"
    move_cut_media_cannot_be_cut_content = "#moveAndCutMediaFlow_cannotBeCut #alertDetailDescription #contentItem"
    move_cut_warn_residual_cut_media = "#moveAndCutMediaFlow_warnResidualCutMedia"
    move_cut_warn_residual_cut_media_header = "#moveAndCutMediaFlow_warnResidualCutMedia #TitleText SpiceText"
    move_cut_warn_residual_cut_media_content = "#moveAndCutMediaFlow_warnResidualCutMedia #alertDetailDescription #contentItem"

    # ouptput folder flow
    output_folder_jam_modal = "#outputFolderFlow_jamModal"
    output_folder_jam_modal_header = "#outputFolderFlow_jamModal #TitleText SpiceText"
    output_folder_jam_modal_content_contents_texts = "#outputFolderFlow_jamModal #alertDetailDescription #contentItem"
    output_folder_jam_modal_help_button = "#outputFolderFlow_jamModal #helpButton"
    output_folder_jam_help_screen_modal = "#HelpVideoView"
    output_folder_jam_help_screen_video = "#HelpVideoView #VideoLayout #VideoItem"
    output_folder_help_message = "#outputFolderFlow_jamHowToSolve"
    output_folder_help_message_video= "#outputFolderFlow_jamHowToSolve #VideoLayout #VideoItem"
    output_folder_jam_checking = "#outputFolderFlow_jamChecking"
    output_folder_jam_checking_header = "#outputFolderFlow_jamChecking #wizardProgressHeader SpiceText"
    output_folder_jam_checking_content = "#outputFolderFlow_jamChecking #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    output_folder_jam_resolved_successfully = "#outputFolderFlow_jamSuccessfullySolved"
    output_folder_jam_resolved_successfully_header = "#outputFolderFlow_jamSuccessfullySolved #wizardCompletionHeader SpiceText"
    output_folder_jam_resolved_successfully_content_images = "#outputFolderFlow_jamSuccessfullySolved #wizardCompletionImages SpiceImage"
    output_folder_jam_resolved_successfully_content_texts = "#outputFolderFlow_jamSuccessfullySolved #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    output_folder_jam_clear_full = "#outputFolderFlow_clearFull"
    output_folder_jam_clear_full_header = "#outputFolderFlow_clearFull #TitleText SpiceText"
    output_folder_jam_clear_full_content_contents_texts = "#outputFolderFlow_clearFull #alertDetailDescription #contentItem"
    output_folder_updating_firmware = "#outputFolderFlow_firmwareUpdate"
    output_folder_updating_firmware_header = "#outputFolderFlow_firmwareUpdate #wizardProgressHeader SpiceText"
    output_folder_updating_firmware_content = "#outputFolderFlow_firmwareUpdate #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    output_folder_installation_accessory_info = "#outputFolderFlow_installationAccessoryInfo"
    output_folder_installation_accessory_info_header = "#outputFolderFlow_installationAccessoryInfo #TitleText SpiceText"
    output_folder_installation_accessory_info_content_texts = "#outputFolderFlow_installationAccessoryInfo #alertDetailDescription #contentItem"
    output_folder_installing = "#outputFolderFlow_InstallationInstalling"
    output_folder_installing_header = "#outputFolderFlow_InstallationInstalling #wizardProgressHeader SpiceText"
    output_folder_installing_content = "#outputFolderFlow_InstallationInstalling #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    output_folder_installation_successfully = "#outputFolderFlow_installationSuccessfully"
    output_folder_installation_successfully_header = "#outputFolderFlow_installationSuccessfully #wizardCompletionHeader SpiceText"
    output_folder_installation_successfully_content_images = "#outputFolderFlow_installationSuccessfully #wizardCompletionImages SpiceImage"
    output_folder_installation_successfully_content_texts = "#outputFolderFlow_installationSuccessfully #wizardCompletionTexts SpiceText[objectName=titleSmallItem]"
    output_folder_installationFails_modal = "#outputFolderFlow_installationFails"
    output_folder_installationFails_modal_header = "#outputFolderFlow_installationFails #TitleText SpiceText"
    output_folder_installationFails_modal_content_contents_texts = "#outputFolderFlow_installationFails #alertDetailDescription #contentItem"
    output_folder_uninstall_info = "#outputFolderFlow_uninstallInfo"
    output_folder_uninstall_info_header = "#outputFolderFlow_uninstallInfo #TitleText SpiceText"
    output_folder_uninstall_info_info_content_texts = "#outputFolderFlow_uninstallInfo #alertDetailDescription #contentItem"
    output_folder_uninstall_success = "#outputFolderFlow_firmwareUpdateSuccessfully"
    output_folder_uninstall_success_header = "#outputFolderFlow_firmwareUpdateSuccessfully #wizardCompletionHeader SpiceText"
    output_folder_uninstall_success_content_images = "#outputFolderFlow_firmwareUpdateSuccessfully #wizardCompletionImages SpiceImage"
    output_folder_uninstall_success_content_texts = "#outputFolderFlow_firmwareUpdateSuccessfully #titleSmallItem"
    output_folder_configure_output = "#outputFolderFlow_configureMediaDestination"
    output_folder_configure_output_media_destination_radio_button0 = "#outputFolderFlow_configureMediaDestination #mediaDestinationRadioButton0"
    output_folder_configure_output_media_destination_radio_button1 = "#outputFolderFlow_configureMediaDestination #mediaDestinationRadioButton1"
    output_folder_configure_folding_style = "#outputFolderFlow_configureFoldingStyles"
    output_folder_configure_folding_style_radio_button0 = "#outputFolderFlow_configureFoldingStyles #foldingStyleRadioButton0"
    output_folder_configure_folding_style_radio_button1 = "#outputFolderFlow_configureFoldingStyles #foldingStyleRadioButton1"
    output_folder_close_cover = "#outputFolderFlow_closeCover"
    output_folder_close_cover_header = "#outputFolderFlow_closeCover #TitleText SpiceText"
    output_folder_close_cover_content_texts = "#outputFolderFlow_closeCover #alertDetailDescription #contentItem"
    output_folder_checking_close_door = "#outputFolderFlow_checkingCover"
    output_folder_checking_close_door_header = "#outputFolderFlow_checkingCover #wizardProgressHeader SpiceText"
    output_folder_checking_close_door_content = "#outputFolderFlow_checkingCover #secondaryAreaTextImage SpiceText[objectName=titleSmallItem]"
    output_folder_remove_media_before_printing_modal = "#outputFolderFlow_moveMediaBeforePrintingRecommended"
    output_folder_remove_media_before_printing_modal_header = "#outputFolderFlow_moveMediaBeforePrintingRecommended #TitleText SpiceText"
    output_folder_remove_media_before_printing_modal_content_contents_texts = "#outputFolderFlow_moveMediaBeforePrintingRecommended #alertDetailDescription #contentItem"

    # MIMO accessory flow
    mimo_installation_confirmation = "#mimoAccessoryFlow_installationConfirmation" 
    mimo_installation_confirmation_header = "#mimoAccessoryFlow_installationConfirmation #TitleText SpiceText"
    mimo_installation_confirmation_content = "#mimoAccessoryFlow_installationConfirmation #contentItem"
    mimo_installing = "#mimoAccessoryFlow_installing"
    mimo_installing_header ="#mimoAccessoryFlow_installing #wizardProgressHeader SpiceText"
    mimo_installing_content ="#mimoAccessoryFlow_installing #secondaryAreaTextImage #titleSmallItem"
    mimo_installation_progress = "#mimoAccessoryFlow_installing #progressBar"
    mimo_installation_fails = "#mimoAccessoryFlow_installationFails"
    mimo_installation_fails_header = "#mimoAccessoryFlow_installationFails #TitleText SpiceText"
    mimo_installation_fails_content= "#mimoAccessoryFlow_installationFails #contentItem"
    mimo_installation_success = "#mimoAccessoryFlow_installationSuccess"
    mimo_installation_success_header = "#mimoAccessoryFlow_installationSuccess #wizardCompletionHeader SpiceText"
    mimo_installation_success_content_image = "#mimoAccessoryFlow_installationSuccess #wizardCompletionImages SpiceImage"
    mimo_installation_success_content = "#mimoAccessoryFlow_installationSuccess #titleSmallItem"
    mimo_uninstallation_confirmation = "#mimoAccessoryFlow_uninstallationConfirmation"
    mimo_uninstallation_confirmation_content = "#mimoAccessoryFlow_uninstallationConfirmation #contentItem"
    mimo_uninstallation_success = "#mimoAccessoryFlow_uninstallationSuccess"
    mimo_uninstallation_success_header = "#mimoAccessoryFlow_uninstallationSuccess #wizardCompletionHeader SpiceText"
    mimo_uninstallation_success_content_image = "#mimoAccessoryFlow_uninstallationSuccess #wizardCompletionImages SpiceImage"
    mimo_uninstallation_success_content = "#mimoAccessoryFlow_uninstallationSuccess #titleSmallItem"

    # Jam workflow: Carriage and Media #
    # Carriage jam
    carriage_jam_main_window = "#carriageStallFlow1Window"
    carriage_jam_main_window_job = "#carriageStallFlow2Window"
    carriage_jam_main_window_footer_ok_button = "{} #AlertFooter #FooterViewRight #OK"
    carriage_jam_main_window_footer_ok_button_text = "{} #AlertFooter #FooterViewRight #OK #ContentItemText"
    carriage_jam_main_window_footer_cancel_button_text = "{} #AlertFooter #FooterViewRight #Cancel #ContentItemText"
    carriage_jam_main_window_footer_hide_button_text = "{} #AlertFooter #FooterViewRight #Hide #ContentItemText"

    # Media jam
    media_jam_main_window = "#mediaJamFlow_modal"
    media_jam_main_window_header_close_button_icon = "#mediaJamFlow_modal #TitleTextHeaderView #rightBlockObject #closeButton #ButtonControlIcon"
    media_jam_main_window_footer_ok_button_text = "#mediaJamFlow_modal #AlertFooter #FooterViewRight #okAction #ContentItemText"
    media_jam_main_window_footer_cancel_button_text = "#mediaJamFlow_modal #AlertFooter #FooterViewRight #cancelAction #ContentItemText"
    media_jam_checking_window = "#mediaJamFlow_checking"
    media_jam_checking_window_content = "#mediaJamFlow_checking #secondaryAreaTextImage #titleSmallItem"
    media_jam_checking_window_progress = "#mediaJamFlow_checking #progressBar"
    media_jam_checking_window_header = "#mediaJamFlow_checking #wizardProgressHeader #leftBlockObject #titleObject"
    media_jam_completed_window = "#mediaJamFlow_successfullySolved"
    media_jam_completed_window_content_image = "#mediaJamFlow_successfullySolved #wizardCompletionImages #imageContainer"
    media_jam_completed_window_content_descr = "#mediaJamFlow_successfullySolved #wizardCompletionTexts #titleSmallItem"
    media_jam_completed_window_header = "#mediaJamFlow_successfullySolved #wizardCompletionHeader #leftBlockObject #titleObject"
    media_jam_completed_window_footer_ok_button = "#mediaJamFlow_successfullySolved #wizardCompletionFooter #FooterViewRight #okAction"
    media_jam_completed_window_footer_ok_button_text = "#mediaJamFlow_successfullySolved #wizardCompletionFooter #FooterViewRight #okAction #ContentItemText"

    # Common jam screens
    jam_main_window_content = "{} #LayoutHorizontalIconsGrid #alertDetailDescription #contentItem"
    jam_main_window_header_title = "{} #TitleTextHeaderView #leftBlockObject #titleObject"
    jam_main_window_header_title_image = "{} #TitleTextHeaderView #leftBlockObject #imageObject"
    jam_main_window_header_help_button_icon = "{} #TitleTextHeaderView #rightBlockObject #helpButton #ButtonControlIcon"
    jam_help_window = "#AlertHelpView"
    jam_help_button = "#TitleTextHeaderView #rightBlockObject #helpButton"
    jam_close_button = "#AlertHelpView #AlertHelpViewHeader #rightBlockObject #CloseView #ButtonControl"
    jam_close_button_icon = "#AlertHelpView #AlertHelpViewHeader #rightBlockObject #CloseView #ButtonControlIcon"
    jam_help_title = "#AlertHelpView #AlertHelpViewHeader #leftBlockObject #titleObject"
    jam_help_title_icon = "#AlertHelpView #AlertHelpViewHeader #leftBlockObject #imageObject"
    jam_help_howto_content = "#AlertHelpView #rowList #VideoHelp #infoBlockRow #contentItem"
    jam_help_howto_image = "#AlertHelpView #rowList #VideoHelp #infoBlockRow #imageItem"
    jam_help_qrcode_content = "#AlertHelpView #rowList #OnlineHelp #infoBlockRow #contentItem"
    jam_help_qrcode_image = "#AlertHelpView #rowList #OnlineHelp #infoBlockRow #imageItem"
    jam_help_window_animations = "#HelpVideoView"
    jam_help_window_animations_header_title = "#HelpVideoView #SpiceHeaderVar1 #leftBlockObject #titleObject"
    ham_help_window_animations_close_button = "#HelpVideoView #SpiceHeaderVar1 #rightBlockObject #ButtonControl #ButtonControlIcon"
    ham_help_window_animations_close_button_icon = "#HelpVideoView #SpiceHeaderVar1 #rightBlockObject #buttonContainer #ButtonControl"
    jam_help_window_qrcode = "#HelpQRCodeView"
    jam_help_window_qrcode_content_image = "#HelpQRCodeView #QRCodeGrid #qrHelpImage #imageContainer"
    jam_help_window_qrcode_content_descr = "#HelpQRCodeView #QRCodeGrid #qrHelpImageDetailBlock #qrHelpDetailDescription #contentItem"
    jam_help_window_qrcode_header_title = "#HelpQRCodeView #SpiceHeaderVar1 #leftBlockObject #titleObject"
    jam_help_window_qrcode_close_button = "#HelpQRCodeView #SpiceHeaderVar1 #rightBlockObject #ButtonControl #ButtonControlIcon"
    ham_help_window_qrcode_close_button_icon = "#HelpQRCodeView #SpiceHeaderVar1 #rightBlockObject #buttonContainer #ButtonControl"
    # End of Jam workflow: Carriage and Media #
