from dunetuf.ui.uioperations.WorkflowOperations.SubstrateLibraryAppWorkflowUICommonOperations import SubstrateLibraryAppWorkflowUICommonOperations

class SubstrateLibraryAppWorkflowUIXSOperations(SubstrateLibraryAppWorkflowUICommonOperations):
    pass