class CopyAppWorkflowObjectIds:

    # -------------------------------Function Keywords------------------------ #
    button_copyApp = "#cedab422-33b3-4638-b6a1-604e54525215"
    button_id_card_copy = "#c74293eb-04c1-4dff-b469-1c0e99fdbe8b"
    button_startCopy = "#mainActionButtonOfDetailPanel"
    button_copyMoreOptions = "#DetailPanelverticalLayout #FooterViewRight #optionsDetailPanelButton"
    done_button = "#mainActionButtonOfDetailPanel"
    copy_button = "#mainActionButtonOfDetailPanel"
    eject_button = "#ejectMainPanelButton"
    eject_button_detail_panel = "#ejectDetailPanelButton"
    ok_button = "#okButton"
    start_button_text = "Start"
    view_copySettingsView = "#copySettingsPage_list1"
    view_copyScreen = "#copyLandingView"
    view_ui_MainApp = "#HomeScreenView"
    detailPanel_layout = "#DetailPanelverticalLayout"
    vertical_layout_scrollbar = "#DetailPanelverticalLayoutScrollBar"

    spinBox_numberOfCopies = "#copy_numberOfCopiesMenuSpinBox"
    row_spinBox_numberOfCopies = "#copy_numberOfCopiesSettingsSpinBox"
    spinBox_numberOfCopies_plus = "#copy_numberOfCopiesMenuSpinBox #upBtn"
    spinBox_numberOfCopies_minus = "#copy_numberOfCopiesMenuSpinBox #downBtn"
    spinBox_numberOfCopies_textArea = "#SpinBoxTextInput"

    row_combo_copySettings_quality = "#copy_qualitySettingsComboBox"
    combo_copySettings_quality="#copy_qualityComboBox"
    view_copySettings_quality = "#copy_qualityComboBoxpopupList"
    combo_quality_option_standard = "#ComboBoxOptionsnormal"
    combo_quality_option_draft = "#ComboBoxOptionsdraft"
    combo_quality_option_best = "#ComboBoxOptionsbest"

    row_combo_copySettings_pagesPerSheet = "#copy_pagesPerSheetSettingsComboBox"
    combo_copySettings_pagesPerSheet = "#copy_pagesPerSheetComboBox"
    view_copySettings_pagesPerSheet = "#copy_pagesPerSheetComboBoxpopupList"
    view_copySettings_pagesPerSheetpopup = "#copy_pagesPerSheetComboBoxpopup"
    combo_pagesPerSheet_option_1 = "#ComboBoxOptionsoneUp"
    combo_pagesPerSheet_option_2 = "#ComboBoxOptionstwoUp"
    combo_pagesPerSheet_option_4_rightThenDown = "#ComboBoxOptionsfourRightThenDown"
    combo_pagesPerSheet_option_4_downThenRight = "#ComboBoxOptionsfourDownThenRight"
    list_copySettings_pagesPerSheet = "#copySettingPagesPerSheet"
    list_view_copySettings_pagesPerSheet = "#copy_pagesPerSheetView"
    list_copySettings_pagesPerSheet_value = "#copySettingPagesPerSheet_2infoBlockRow"
    check_addPageBorders_option = "#CheckBoxOptionsAddPageBorders"
    row_addPageBorders_option = "#AddPageBorders"
    copy_pagesPerSheet_options_scrollbar = "#copy_pagesPerSheetViewScrollBar"

    row_combo_copySettings_sides = "#copy_sidesMenuComboBox"
    combo_copySettings_sides = "#SettingsSpiceComboBox"
    view_copySettings_sides_popup_list = "#SettingsSpiceComboBoxpopupList"
    view_copySettings_sides_popup = "#SettingsSpiceComboBoxpopup"
    combo_sides_option_1_1_sided = "#Copy1to1Sided"
    combo_sides_option_1_2_sided = "#Copy1to2Sided"
    combo_sides_option_2_1_sided = "#Copy2to1Sided"
    combo_sides_option_2_2_sided = "#Copy2to2Sided"

    combo_sides_option_1_1_sided_radio_button = "#Copy1to1SidedRadioButtonModel"
    combo_sides_option_1_2_sided_radio_button = "#Copy1to2SidedRadioButtonModel"
    combo_sides_option_2_1_sided_radio_button = "#Copy2to1SidedRadioButtonModel"
    combo_sides_option_2_2_sided_radio_button = "#Copy2to2SidedRadioButtonModel"

    scan_mode_settings_option          = "#scan_scanModeSettingsTextImage"
    row_scan_mode_settings_option      = "#scan_scanModeSettingsTextImage_2infoBlockRow" 
    view_scan_mode_settings_view       = "#copy_scanModeList"
    scan_mode_option_standard_document = "#scan_scanModestandard"
    scan_mode_option_job_build         = "#scan_scanModejobBuild"
    scan_mode_option_id_card           = "#scan_scanModeidCard"
    scan_mode_option_book_mode         = "#scan_scanModebookMode"
    scan_mode_option_prompt_for_additonal_pages_checkbox = "#promptCheckBoxForAdditionalPages"
    scan_mode_option_prompt_for_scan_both_sided = "#promptCheckBoxForScanBothSides"
    scan_mode_settings_scrollbar       = "#copy_scanModeListScrollBar"

    row_combo_copySettings_contentType = "#scan_contentTypeSettingsComboBox"
    combo_copySettings_contentType = "#scan_contentTypeComboBox"
    view_copySettings_contentType = "#scan_contentTypeComboBoxpopupList"
    combo_contentType_option_text = "#ComboBoxOptionstext"
    combo_contentType_option_photograph = "#ComboBoxOptionsphoto"
    combo_contentType_option_linedraw = "#ComboBoxOptionslineDrawing"
    combo_contentType_option_image = "#ComboBoxOptionsimage"
    combo_contentType_option_mixed = "#ComboBoxOptionsmixed"

    setings_openSettings_option = "#optionsDetailPanelButton"
    settings_copySettings_view = "#copySettingsView"
    
    setings_contentType_option = "#copySettingsPage_list1 #scan_contentTypeSettingsComboBox #scan_contentTypeComboBox"
    setings_contentType_option_linedraw = "#ComboBoxOptionslineDrawing"
    setings_contentType_option_image = "#ComboBoxOptionsimage"
    setings_contentType_option_mixed = "#ComboBoxOptionsmixed"

    setings_originalPaper_option = "#scan_originalMediaTypeComboBox"
    setings_originalPaper_option_white = "#ComboBoxOptionswhitePaper"
    setings_originalPaper_option_photo = "#ComboBoxOptionsphotoPaper"
    setings_originalPaper_option_translucent = "#ComboBoxOptionstranslucentPaper"
    setings_originalPaper_option_oldRecycled = "#ComboBoxOptionsoldRecycledPaper"
    setings_originalPaper_option_blueprints = "#ComboBoxOptionsblueprints"
    setings_originalPaper_option_darkBlueprints = "#ComboBoxOptionsdarkBlueprints"
    setings_originalPaper_option_list = "#scan_originalMediaTypeComboBoxpopupList"

    setings_resolution_option = "#scan_resolutionSettingsComboBox #scan_resolutionComboBox"
    setings_resolution_option_list = "#scan_resolutionComboBoxpopupList"
    setings_resolution_option_200 = "#ComboBoxOptionse200Dpi"
    setings_resolution_option_300 = "#ComboBoxOptionse300Dpi"
    setings_resolution_option_600 = "#ComboBoxOptionse600Dpi"
    settings_copy_orientation = "#scan_contentOrientationComboBox"
    view_copy_settings_orientation_screen = "#scan_contentOrientationComboBoxpopupList"
    orientation_landscape_option = "#ComboBoxOptionslandscape"
    orientation_portrait_option = "#ComboBoxOptionsportrait"

    settings_longPlot_option = "#scan_longPlotScanSettingsSwitch"
    settings_edgeToEdge_option = "#scan_edgeToEdgeScanSettingsSwitch"
    
    slider_sharpness = "#scan_sharpnessMenuSlider"
    row_slider_sharpness = "#scan_sharpnessSettingsSlider"

    toggle_button_scan_long_original_output = "#scan_longPlotScanMenuSwitch"
    toggle_button_scan_edge_to_edge_output = "#scan_edgeToEdgeScanMenuSwitch"

    long_plot_confirmation_screen = "#LongPLotConfirmationScreen"
    long_plot_confirmation_screen_ok_button = "#OKButton"

    settings_scan_auto_straighten = "#scan_autoStraightenSettingsSwitch"
    toggle_button_scan_auto_straighten = "#scan_autoStraightenMenuSwitch"
    settings_scan_auto_straighten_text = "#scan_autoStraightenSettingsSwitch #contentItem"

    setings_autoRelease_option = "#scan_autoReleaseMenuSwitch"
    
    flatbed_cancel_screen = "#FlatbedCancelPrompt"
    flatbed_two_sided_screen = "#flatbedAddPage"
    button_copy_add_page_add = "#addButton"
    button_copy_add_page_scan = "#scanButton"
    button_copy_add_page_done = "#doneButton"
    button_copy_add_page_cancel = "#addPagePromptView #cancelButton"
    button_copy_add_page_cancel_yes = "#yesButton"
    button_copy_add_page_cancel_no = "#noButton"
    view_add_page_prompt_view = "#addPagePromptView"
    add_page_prompt_scroll_bar = "#addPageContentScrollBar"
    add_page_content_id = "#addPageContent"

    button_duplex_add_page_add = "#addMoreButton"
    button_duplex_add_page_finish = "#finish"
    button_duplex_add_page_cancel = "#cancel"

    setings_background_color_i_image = "#scan_backgroundColorRemovalSettingsSwitch #scan_backgroundColorRemovalMenuSwitch SpiceImage"
    row_object_copy_background_color_removal = "#scan_backgroundColorRemovalSettingsSwitch"
    switch_button_copy_background_color_removal = "#copySettingsPage_list1 #scan_backgroundColorRemovalSettingsSwitch #scan_backgroundColorRemovalMenuSwitch"
    toggle_button_copy_background_color_removal = "#scan_backgroundColorRemovalMenuSwitch"
    scrollbar_option_screen = "#scanMenuListlist1ScrollBar"
    setings_invertBlueprintColor_option = "#scan_invertBlueprintColorSettingsSwitch"
    toggle_button_invert_blueprint = "#scan_invertBlueprintColorsMenuSwitch"

    row_copy_background_noise_removal = "#scan_backgroundNoiseRemovalSettingsSwitch"
    row_copy_background_noise_removal_item = "#scan_backgroundNoiseRemovalMenuSwitch"
    row_copy_background_noise_removal_switch = "#copySettingsPage_list1 #scan_backgroundNoiseRemovalSettingsSwitch #scan_backgroundNoiseRemovalMenuSwitch"

    row_black_enhancements = "#scan_blackEnhancementLevelSettingsSpinBox"
    row_black_enhancements_textinput = "#scan_blackEnhancementLevelMenuSpinBox"

    row_copy_original_paper_type = "#scan_originalMediaTypeSettingsComboBox"
    row_copy_original_paper_type_item = "#scan_originalMediaTypeComboBox"
    
    setings_scanSpeed_option = "#scan_scanSpeedMenuSwitch"

    setings_color_option = "#copySettingsPage_list1 #scan_colorModeSettingsComboBox #scan_colorModeComboBox"
    
    setings_close_option = "#copySettingsPage_list1 #closeButton"

    row_combo_copySettings_color = "#scan_colorModeSettingsComboBox"
    combo_copySettings_color = "#scan_colorModeComboBox"
    view_copySettings_color = "#scan_colorModeComboBoxpopupList"
    combo_color_option_automatic = "#ComboBoxOptionsautoDetect"
    combo_color_option_color = "#ComboBoxOptionscolor"
    combo_color_option_grayscale = "#ComboBoxOptionsgrayscale"
    combo_color_option_blackonly="#ComboBoxOptionsmonochrome"
    
    color_mode_value = "#scan_colorModeComboBox SpiceText[visible=true]"
    quality_value = "#copy_qualityComboBox SpiceText[visible=true]"
    content_type_value = "#scan_contentTypeComboBox SpiceText[visible=true]"
    paper_source_value = "#copy_detailedPaperSourceComboBox SpiceText[visible=true]"
    number_of_copies_value = "#copy_numberOfCopiesMenuSpinBox #SpinBoxTextInput"

    row_combo_copySettings_copyMargins = "#copy_marginsSettingsComboBox"
    combo_copySettings_copyMargins ="#copy_marginsComboBox"
    view_copySettings_copyMargins = "#copy_marginsComboBoxpopupList"
    combo_copyMargins_option_clipContents = "#ComboBoxOptionsclipContents"
    combo_copyMargins_option_addToContents = "#ComboBoxOptionsaddToContents"

    row_combo_copySettings_copyPrintingOrder = "#copy_printingOrderSettingsComboBox"
    combo_copySettings_copyPrintingOrder ="#copy_printingOrderComboBox"
    view_copySettings_copyPrintingOrder = "#copy_printingOrderComboBoxpopupList"
    combo_copyPrintingOrder_option_firstPageOnTop = "#ComboBoxOptionsfirstPageOnTop"
    combo_copyPrintingOrder_option_lastPageOnTop = "#ComboBoxOptionslastPageOnTop"

    row_paper_type_matte_dash_90gsm = "#com_dot_hp_dot_matte_dash_90gsmcopy_paperType"  #HP Matte(90g)
    row_paper_type_matte_dash_105gsm = "#com_dot_hp_dot_matte_dash_105gsmcopy_paperType"  #HP Matte(105g)
    row_paper_type_matte_dash_120gsm = "#com_dot_hp_dot_matte_dash_120gsmcopy_paperType"  #HP Matte(120g)
    row_paper_type_envelope = "#envelopecopy_paperType"  #Envelope
    row_paper_type_extra_heavy = "#com_dot_hp_dot_extra_dash_heavycopy_paperType"  #Extra Heavy(131-175g)
    row_paper_type_brochure_matte_150gsm = "#com_dot_hp_dot_matte_dash_160gsmcopy_paperType" #HP Brochure Matte(150g)
    row_paper_type_hp_glossy_150gsm = "#com_dot_hp_dot_glossy_dash_160gsmcopy_paperType"  #HP Glossy(150g)
    row_paper_type_any = "#anycopy_paperType"  #Any Type
    row_paper_type_plain = "#stationerycopy_paperType"  #Plain
    row_paper_type_hp_ecofficient = "#com_dot_hp_dot_EcoSMARTLitecopy_paperType"  #HP EcoFFICIENT
    row_paper_type_hp_matte_200g = "#com_dot_hp_dot_matte_dash_200gsmcopy_paperType"  #HP Matte(200g)
    row_paper_type_hp_glossy_120g = "#com_dot_hp_dot_glossy_dash_130gsmcopy_paperType"  #HP Glossy(120g)
    row_paper_type_hp_glossy_200g = "#com_dot_hp_dot_glossy_dash_220gsmcopy_paperType"  #HP Glossy(200g)
    row_paper_type_hp_tri_fold_glossy_150g = "#com_dot_hp_dash_trifold_dash_brochure_dash_glossy_dash_150gsmcopy_paperType"  #HP Tri-Fold Glossy(150g)
    row_paper_type_intermediate = "#com_dot_hp_dot_intermediatecopy_paperType"  #Intermediate(85-95g)
    row_paper_type_mid_weight = "#com_dot_hp_dot_midweightcopy_paperType"  #Mid-Weight(96-110g)
    row_paper_type_heavy = "#stationery_dash_heavyweightcopy_paperType"  #Heavy(111-130g)
    row_paper_type_cardstock = "#cardstockcopy_paperType"  #Cardstock(176-220g)
    row_paper_type_heavy_glossy = "#com_dot_hp_dot_heavy_dash_glossycopy_paperType"  #Heavy Glossy(111-130g)
    row_paper_type_cardstock_glossy = "#com_dot_hp_dot_cardstock_dash_glossycopy_paperType"  #Cardstock Glossy(176-220g)
    row_paper_type_lables = "#labelscopy_paperType"  #Lables
    row_paper_type_heavy_envelope = "#envelope_dash_heavyweightcopy_paperType"  #Heavy Envelope
    row_paper_type_bond = "#stationery_dash_bondcopy_paperType"  #Bond
    row_paper_type_recycled = "#com_dot_hp_dot_recycledcopy_paperType"  #Recycled  
    row_paper_type_rough = "#com_dot_hp_dot_roughcopy_paperType"  #Rough   
    row_paper_type_opaque_film = "#com_dot_hp_dot_film_dash_opaquecopy_paperType"	#Opaque Film
    row_paper_type_color_Transparency = "#transparencycopy_paperType"   #Color Transparency
    row_paper_type_heavy_rough = "#com_dot_hp_dot_heavy_dash_roughcopy_paperType"   #Heavy Rough
    row_paper_type_light = "#stationery_dash_lightweightcopy_paperType"  #Light(60-74g)
    row_paper_type_extra_heavy_glossy = "#com_dot_hp_dot_extra_dash_heavy_dash_glosscopy_paperType" #Extra Heavy Glossy(131-175g)
    row_paper_type_letterhead = "#stationery_dash_letterheadcopy_paperType"  #Letterhead
    row_paper_type_preprinted = "#stationery_dash_preprintedcopy_paperType"  #Preprinted
    row_paper_type_prepunched = "#stationery_dash_prepunchedcopy_paperType" #Prepunched
    row_paper_type_colored = "#stationery_dash_coloredcopy_paperType"  #Colored
    row_paper_type_user_defined_10 = "#com_dot_hp_dot_usertype_dash_10_paperType"  #UserDefined 10

    copy_settings_rotation = "#copy_rotateMenuComboBox"
    copy_settings_rotation_combobox = "#copy_rotateMenuComboBox #SettingsSpiceComboBox #control"
    copy_settings_rotation_list_combobox = "#SettingsSpiceComboBoxpopupList"
    combo_option_rotation_auto = "#Auto"
    combo_option_rotation_0 = "#0rot"
    combo_option_rotation_90 = "#90rot"
    combo_option_rotation_180 = "#180rot"
    combo_option_rotation_270 = "#270rot"

    copy_landing_view_back_button = "#copyLandingView #BackButton"
    button_home = "#CopyAppApplicationStackView #HomeButton #ButtonControl"
    button_back = "#BackButton"
    close_button = "#closeButton"
    text_view = "SpiceText[visible=true]"
    copy_options_scrollbar = "#copySettingsPage_list1ScrollBar"
    copy_resize_scrollbar = "#copyResizeViewScrollBar"
    copy_papersize_scrollbar = "#copy_mediaSizeMenuSelectionListScrollBar"
    copy_paperType_scrollbar = "#copy_paperTypeMenuSelectionListScrollBar"
    copy_paperTray_scrollbar = "#comboBoxScrollBar"
    copy_originalSize_scrollbar = "#scan_originalSizeMenuSelectionListScrollBar"
    copy_side_scrollbar = "#comboBoxScrollBar"
    copy_toast_hide_button = "#toastHideButton"

    row_toggle_copySettings_collate ="#copy_collateToggleSettingsSwitch"
    toggle_copySettings_collate = "#copy_collateToggleMenuSwitch"
    toggle_copySettings_pageFlipUp = "#scan_pageFlipUpEnabledMenuSwitch"
    row_toggle_copySettings_pageFlipup = "#copyPageFlipUp"
    
    view_copySettings_blankPageSuppression = "#scan_blankPageSuppressionComboBoxpopupList"
    row_combo_copySettings_blankPageSuppression ="#scan_blankPageSuppressionSettingsComboBox"
    combo_copySettings_blankPageSuppression ="#scan_blankPageSuppressionComboBox"
    combo_option_blankPageSuppression_on = "#ComboBoxOptionstrue_"
    combo_option_blankPageSuppression_off = "#ComboBoxOptionsfalse_"

    list_copySettings_originalSize = "#scan_originalSizeSettingsTextImage"
    view_copySettings_originalSize = "#scan_originalSizeMenuSelectionList"
    view_originalSetting = "#scan_originalSizeSettingsTextImage_2infoBlockRow"
    radio_original_size_any="#MenuValueany"
    radio_originalSize_iso_a4_210x297mm = "#MenuValueiso_a4_210x297mm"
    radio_originalSize_rotate_iso_a4_210x297mm = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_iso_a4_210x297mm_dot_rotated"
    radio_originalSize_iso_a5_148x210mm = "#MenuValueiso_a5_148x210mm"
    radio_originalSize_rotate_iso_a5_148x210mm = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_iso_a5_148x210mm_dot_rotated"
    radio_originalSize_iso_a6_105x148mm = "#MenuValueiso_a6_105x148mm"
    radio_originalSize_jis_b5_182x257mm = "#MenuValuejis_b5_182x257mm"
    radio_originalSize_rotate_jis_b5_182x257mm = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_jis_b5_182x257mm_dot_rotated"
    radio_originalSize_na_letter_8_5x11in = "#MenuValuena_letter_8_dot_5x11in"
    radio_originalSize_rotate_na_letter_8_5x11in = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_na_letter_8_dot_5x11in_dot_rotated"  
    radio_originalSize_na_legal_8_5x14in = "#MenuValuena_legal_8_dot_5x14in"
    radio_originalSize_na_invoice_5_5x8_5in = "#MenuValuena_invoice_5.5x8.5in"
    radio_originalSize_na_executive_7_25x10_5in = "#MenuValuena_executive_7.25x10.5in"
    radio_originalSize_na_foolscap_8_5x13in = "#MenuValuena_foolscap_8.5x13in"
    radio_originalSize_na_index_4x6_4x6in = "#MenuValuena_index-4x6_4x6in"
    radio_originalSize_na_index_5x8_5x8in = "#MenuValuena_index-5x8_5x8in"
    radio_originalSize_mixed_a4_a3 = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_mixed_dash_a4_dash_a3"
    radio_originalSize_mixed_letter_legal = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_mixed_dash_letter_dash_legal"
    radio_originalSize_mixed_letter_ledger = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_mixed_dash_letter_dash_ledger"
    radio_originalSize_index_5x8_5x8in = "#MenuValuena_index_dash_5x8_5x8in"
    radio_originalSize_oficio_216x340 = "#MenuValuena_oficio_8_dot_5x13_dot_4in"
    radio_originalSize_16k_195x270 = "#om_16k_195x270mmscan_originalSize"
    radio_originalSize_16k_184x260 = "#MenuValueom_16k_184x260mm"
    radio_originalSize_16k_197x273 = "#MenuValueroc_16k_7_dot_75x10_dot_75in"
    radio_originalSize_double_ostcard_jis_148x200mm = "#MenuValuejpn_oufuku_148x200mm"
    radio_originalSize_invoice_5_5x8_5in = "#MenuValuena_invoice_5_dot_5x8_dot_5in"
    radio_originalSize_jis_b6_128x182mm = "#MenuValuejis_b6_128x182mm"
    radio_originalSize_10x15 = "#MenuValueom_small_dash_photo_100x150mm"
    radio_originalSize_postcard_jis_100x148mm = "#MenuValuejpn_hagaki_100x148mm"
    radio_originalSize_envelope_10 = "#MenuValuena_number_dash_10_4_dot_125x9_dot_5in"
    radio_originalSize_envelope_monarch = "#na_monarch_3_dot_875x7_dot_5inscan_originalSize"
    radio_originalSize_envelope_b5 = "#MenuValueiso_b5_176x250mm"
    radio_originalSize_envelope_c5 = "#MenuValueiso_c5_162x229mm"
    radio_originalSize_envelope_dl = "#MenuValueiso_dl_110x220mm"
    radio_originalSize_index_4x6_4x6in = "#MenuValuena_index_dash_4x6_4x6in"
    radio_originalSize_2l_127x178 = "#MenuValuejpn_photo_dash_2l_127x177_8mm"
    radio_originalSize_5x5in = "#MenuValueoe_square_dash_photo_5x5in"
    radio_originalSize_5x7in = "#MenuValuena_5x7_5x7in"
    radio_originalSize_8x10in = "#MenuValuena_govt_dash_letter_8x10in"
    radio_originalSize_ofuku_hagaki = "#MenuValuecom_dot_hp_dot_ext_dot_mediaSize_dot_jpn_oufuku_148x200mm_dot_rotated"
    radio_originalSize_envelope_6 = "#MenuValuena_personal_3_dot_625x6_dot_5in"
    radio_originalSize_3x5in = "#MenuValuena_index_dash_3x5_3x5in"
    radio_originalSize_chou4 = "#MenuValuejpn_chou4_90x205mm"
    radio_originalSize_hagaki_100x148 = "#MenuValuejpn_hagaki_100x148mm"
    radio_originalSize_4x12in = "#MenuValueoe_photo_dash_4x12_4x12in"
    radio_originalSize_envelope_a2 = "#MenuValuena_a2_4_dot_375x5_dot_75in"
    radio_originalSize_chou3 = "#MenuValuejpn_chou3_120x235mm"
    radio_originalSize_b4 = "#MenuValuejis_b4_257x364mm"
    radio_originalSize_11x14in = "#MenuValuena_edp_11x14in"
    radio_originalSize_tabloid_11x17 = "#MenuValuena_ledger_11x17in"
    radio_originalSize_a3 = "#MenuValueiso_a3_297x420mm"
    radio_originalSize_custom = "#MenuValuecustom"


    row_original_size_any= "#anyscan_originalSize"
    row_original_size_iso_a4_210x297mmn = "#iso_a4_210x297mmscan_originalSize"
    row_original_size_rotate_iso_a4_210x297mmn = "#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a4_210x297mm_dot_rotatedscan_originalSize"
    row_original_size_iso_a5_148x210mm = "#iso_a5_148x210mmscan_originalSize"
    row_original_size_rotate_iso_a5_148x210mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a5_148x210mm_dot_rotatedscan_originalSize"
    row_original_size_iso_a6_105x148mm = "#iso_a6_105x148mmscan_originalSize"
    row_original_size_jis_b5_182x257mm = "#jis_b5_182x257mmscan_originalSize"
    row_original_size_jis_b6_128x182mm = "#jis_b6_128x182mmscan_originalSize"
    row_original_size_rotate_jis_b5_182x257mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_jis_b5_182x257mm_dot_rotatedscan_originalSize"
    row_original_size_na_letter_8_5x11in = "#na_letter_8_dot_5x11inscan_originalSize"
    row_original_size_rotate_na_letter_8_5x11in = "#com_dot_hp_dot_ext_dot_mediaSize_dot_na_letter_8_dot_5x11in_dot_rotatedscan_originalSize"
    row_original_size_na_legal_8_5x14in = "#na_legal_8_dot_5x14inscan_originalSize"
    row_original_size_invoice_5_5x8_5in = "#na_invoice_5_dot_5x8_dot_5inscan_originalSize"
    row_original_size_executive_7_25x10_5in = "#na_executive_7_dot_25x10_dot_5inscan_originalSize"
    row_original_size_foolscap_8_5x13in = "#na_foolscap_8_dot_5x13inscan_originalSize"
    row_original_size_index_4x6_4x6in = "#na_index_dash_4x6_4x6inscan_originalSize"
    row_original_size_index_5x8_5x8in = "#na_index_dash_5x8_5x8inscan_originalSize"
    row_original_size_double_ostcard_jis_148x200mm = "#jpn_oufuku_148x200mmscan_originalSize"
    row_original_size_statement_5_5x8_5in = "#jpn_oufuku_148x200mmscan_originalSize"
    row_originalSize_mixed_a4_a3 = "#com_dot_hp_dot_ext_dot_mediaSize_dot_mixed_dash_a4_dash_a3scan_originalSize"
    row_originalSize_mixed_letter_legal = "#com_dot_hp_dot_ext_dot_mediaSize_dot_mixed_dash_letter_dash_legalscan_originalSize"
    row_originalSize_mixed_letter_ledger = "#com_dot_hp_dot_ext_dot_mediaSize_dot_mixed_dash_letter_dash_ledgerscan_originalSize"
    row_original_size_oficio_216x340 = "#na_oficio_8_dot_5x13_dot_4inscan_originalSize"
    row_original_size_16k_195x270 = "#om_16k_195x270mmscan_originalSize"
    row_original_size_16k_184x260 = "#om_16k_184x260mmscan_originalSize"
    row_original_size_16k_197x273 = "#roc_16k_7_dot_75x10_dot_75inscan_originalSize"
    row_original_size_10x15 = "#om_small_dash_photo_100x150mmscan_originalSize"
    row_original_size_postcard_jis_100x148mm = "#jpn_hagaki_100x148mmscan_originalSize"
    row_original_size_envelope_10 = "#na_number_dash_10_4_dot_125x9_dot_5inscan_originalSize"
    row_original_size_envelope_monarch = "#na_monarch_3_dot_875x7_dot_5inscan_originalSize"
    row_original_size_envelope_b5 = "#iso_b5_176x250mmscan_originalSize"
    row_original_size_envelope_c5 = "#iso_c5_162x229mmscan_originalSize"
    row_original_size_envelope_dl = "#iso_dl_110x220mmscan_originalSize"
    row_original_size_2l_127x178 = "#jpn_photo_dash_2l_127x177_8mmscan_originalSize"
    row_original_size_5x5in = "#oe_square_dash_photo_5x5inscan_originalSize"
    row_original_size_5x7in = "#na_5x7_5x7inscan_originalSize"
    row_original_size_8x10in = "#na_govt_dash_letter_8x10inscan_originalSize"
    row_original_size_ofuku_hagaki = "#com_dot_hp_dot_ext_dot_mediaSize_dot_jpn_oufuku_148x200mm_dot_rotatedscan_originalSize"
    row_original_size_l_89x127 = "#oe_photo_dash_l_3_dot_5x5inscan_originalSize"
    row_original_size_envelope_6 = "#na_personal_3_dot_625x6_dot_5inscan_originalSize"
    row_original_size_3x5in = "#na_index_dash_3x5_3x5inscan_originalSize"
    row_original_size_chou4 = "#jpn_chou4_90x205mmscan_originalSize"
    row_original_size_hagaki_100x148 = "#jpn_hagaki_100x148mmscan_originalSize"
    row_original_size_4x12in = "#oe_photo_dash_4x12_4x12inscan_originalSize"
    row_original_size_envelope_a2 = "#na_a2_4_dot_375x5_dot_75inscan_originalSize"
    row_original_size_chou3 = "#jpn_chou3_120x235mmscan_originalSize"
    row_original_size_b4 = "#jis_b4_257x364mmscan_originalSize"
    row_original_size_11x14in = "#na_edp_11x14inscan_originalSize"
    row_original_size_tabloid_11x17 = "#na_ledger_11x17inscan_originalSize"
    row_original_size_a3 = "#iso_a3_297x420mmscan_originalSize"
    row_original_size_custom = "#customscan_originalSize"
    row_object_copy_orientation = "#scan_contentOrientationSettingsComboBox" 


    row_media_size_any= "#anycopy_mediaSize"
    view_paperSetting_first_option = "#copyPaperSelection_firstinfoBlockRow"
    view_paperSetting = "#copyPaperSelection_2infoBlockRow"
    row_media_size_iso_a2_420x594mm = "#iso_a2_420x594mmcopy_mediaSize"
    row_media_size_iso_a3_297x420mm = "#iso_a3_297x420mmcopy_mediaSize"
    row_media_size_iso_a4_210x297mm = "#iso_a4_210x297mmcopy_mediaSize"
    row_media_size_rotate_iso_a4_210x297mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a4_210x297mm_dot_rotatedcopy_mediaSize"
    row_media_size_iso_a5_148x210mm = "#iso_a5_148x210mmcopy_mediaSize"
    row_media_size_rotate_iso_a5_148x210mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a5_148x210mm_dot_rotatedcopy_mediaSize"
    row_media_size_iso_a6_105x148mm = "#iso_a6_105x148mmcopy_mediaSize"
    row_media_size_jis_b5_182x257mm = "#jis_b5_182x257mmcopy_mediaSize"
    row_media_size_jis_b6_128x182mm = "#jis_b6_128x182mmcopy_mediaSize"
    row_media_size_rotate_jis_b5_182x257mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_jis_b5_182x257mm_dot_rotatedcopy_mediaSize"
    row_media_size_na_letter_8_5x11in = "#na_letter_8_dot_5x11incopy_mediaSize"
    row_media_size_rotate_na_letter_8_5x11in = "#com_dot_hp_dot_ext_dot_mediaSize_dot_na_letter_8_dot_5x11in_dot_rotatedcopy_mediaSize"
    row_media_size_na_legal_8_5x14in = "#na_legal_8_dot_5x14incopy_mediaSize"
    row_media_size_invoice_5_5x8_5in = "#na_invoice_5_dot_5x8_dot_5incopy_mediaSize"
    row_media_size_executive_7_25x10_5in = "#na_executive_7_dot_25x10_dot_5incopy_mediaSize"
    row_media_size_foolscap_8_5x13in = "#na_foolscap_8_dot_5x13incopy_mediaSize"
    row_media_size_index_4x6_4x6in = "#na_index_dash_4x6_4x6incopy_mediaSize"
    row_media_size_index_5x7_5x7in = "#na_5x7_5x7incopy_mediaSize"
    row_media_size_index_5x8_5x8in = "#na_index_dash_5x8_5x8incopy_mediaSize"
    row_media_size_oficio_8_5x13in = "#na_foolscap_8_dot_5x13incopy_mediaSize" 
    row_media_size_oficio_8_5x13_4in = "#na_oficio_8_dot_5x13_dot_4incopy_mediaSize" 
    row_media_size_l_89x127 = "#oe_photo_dash_l_3_dot_5x5incopy_mediaSize"
    row_media_size_16k_195x270 = "#om_16k_195x270mmcopy_mediaSize"
    row_media_size_16k_184x260 = "#om_16k_184x260mmcopy_mediaSize"
    row_media_size_16k_197x273 = "#roc_16k_7_dot_75x10_dot_75incopy_mediaSize"
    row_media_size_10x15 = "#om_small_dash_photo_100x150mmcopy_mediaSize"
    row_media_size_postcard_jis_100x148mm = "#jpn_hagaki_100x148mmcopy_mediaSize"
    row_media_size_double_postcard_jis_148x200mm = "#jpn_oufuku_148x200mmcopy_mediaSize"
    row_media_size_envelope_10 = "#na_number_dash_10_4_dot_125x9_dot_5incopy_mediaSize"
    row_media_size_envelope_monarch = "#na_monarch_3_dot_875x7_dot_5incopy_mediaSize"
    row_media_size_envelope_b5 = "#iso_b5_176x250mmcopy_mediaSize"
    row_media_size_envelope_c5 = "#iso_c5_162x229mmcopy_mediaSize"
    row_media_size_envelope_dl = "#iso_dl_110x220mmcopy_mediaSize"
    row_media_size_custom = "#customcopy_mediaSize"
    row_media_size_jpn_chou3_120x235mm = "#jpn_chou3_120x235mmcopy_mediaSize"
    row_media_size_jpn_chou4_90x205mm = "#jpn_chou4_90x205mmcopy_mediaSize"
    row_media_size_envelope_c6 = "#iso_c6_114x162mmcopy_mediaSize"
    row_media_size_index_3x5_3x5in= "#na_index_dash_3x5_3x5incopy_mediaSize"

    copy_mediasize_custom_str_id = "cMediaSizeIdCustom"
    copy_mediasize_arch_a_str_id = "cMediaSizeIdArchA"
    copy_mediasize_arch_b_str_id = "cMediaSizeIdArchB"
    copy_mediasize_arch_c_str_id = "cMediaSizeIdArchC"
    copy_mediasize_arch_d_str_id = "cMediaSizeIdArchD"
    copy_mediasize_arch_e_str_id = "cMediaSizeIdArchE"
    copy_mediasize_arch_e2_str_id = "cMediaSizeIdArchE2"
    copy_mediasize_arch_e3_str_id = "cMediaSizeIdArchE3"
    copy_mediasize_a2_str_id = "cMediaSizeIdA2"
    copy_mediasize_a3_str_id = "cMediaSizeIdA3"
    copy_mediasize_a4_str_id = "cMediaSizeIdA4"
    copy_mediasize_a5_str_id = "cMediaSizeIdA5"
    copy_mediasize_a6_str_id = "cMediaSizeIdA6"
    copy_mediasize_a4_rotate_str_id = "cMediaSizeIdA4Rotated"
    copy_mediasize_a5_rotate_str_id = "cMediaSizeIdA5Rotated"
    copy_mediasize_iso_b0_str_id = "cMediaSizeIdISOB0"
    copy_mediasize_iso_b1_str_id = "cMediaSizeIdISOB1"
    copy_mediasize_iso_b2_str_id = "cMediaSizeIdISOB2"
    copy_mediasize_iso_b3_str_id = "cMediaSizeIdISOB3"
    copy_mediasize_iso_b4_str_id = "cMediaSizeIdISOB4"
    copy_mediasize_b5_rotate_str_id = "cMediaSizeIdJisB5Rotated"
    copy_mediasize_envelope_b5_str_id = "cMediaSizeIdB5Envelope"
    copy_mediasize_jis_b6_str_id = "cMediaSizeIdJisB6"
    copy_mediasize_envelope_monarch_str_id = "cMediaSizeIdMonarchEnvelope"
    copy_mediasize_c0_str_id = "cMediaSizeIdC0"
    copy_mediasize_c1_str_id = "cMediaSizeIdC1"
    copy_mediasize_c2_str_id = "cMediaSizeIdC2"
    copy_mediasize_c3_str_id = "cMediaSizeIdC3"
    copy_mediasize_c4_str_id = "cMediaSizeIdC4"
    copy_mediasize_envelope_c5_str_id = "cMediaSizeIdC5Envelope"
    copy_mediasize_envelope_c6_str_id = "cMediaSizeIdEnvelopeC6"
    copy_mediasize_envelope_dl_str_id = "cMediaSizeIdDLEnvelope"
    copy_mediasize_j_envelope_chou3_str_id = "cMediaSizeIdJChou3Envelope"
    copy_mediasize_j_envelope_chou4_str_id = "cMediaSizeIdJChou4Envelope"
    copy_mediasize_hagaki_str_id = "cMediaSizeIdHagaki"
    copy_mediasize_double_postcard_str_id = "cMediaSizeIdOfukuHagaki"
    copy_mediasize_4x6_str_id = "cMediaSizeIdFourXSix"
    copy_mediasize_5x7_str_id = "cMediaSizeIdFiveXSeven"
    copy_mediasize_5x8_str_id = "cMediaSizeIdFiveXEight"
    copy_mediasize_letter_str_id = "cMediaSizeIdLetter"
    copy_mediasize_letter_rotate_str_id = "cMediaSizeIdLetterRotated"
    copy_mediasize_legal_str_id = "cMediaSizeIdLegal"
    copy_mediasize_envelope_com10_id = "cMediaSizeIdCOM10Envelope"
    copy_mediasize_executive_str_id = "cMediaSizeIdExecutive"
    copy_mediasize_oficio_str_id = "cMediaSizeIdOficio"
    copy_mediasize_16k_184x260_str_id = "cMediaSizeIdSize16K184x260"
    copy_mediasize_16k_195x270_str_id = "cMediaSizeIdSize16k195x270"
    copy_mediasize_16k_str_id = "cMediaSizeIdSixteenK"
    copy_mediasize_5x8_str_id = "cMediaSizeIdFiveXEight"
    copy_mediasize_double_postcard_jis_str_id = "cMediaSizeIdOfukuHagaki"
    copy_mediasize_b5_str_id = "cMediaSizeIdJisB5"
    copy_mediasize_statement_str_id = "cMediaSizeIdStatement"
    copy_mediasize_oficio_8_5x13_4_str_id = "cMediaSizeIdOficio216x340"
    copy_mediasize_ledger_11x17_str_id = "cMediaSizeIdLedger"
    copy_mediasize_100x150mm_str_id = "cMediaSizeId10x15cm"
    copy_mediasize_d_22x34in_str_id = "cMediaSizeIdANSID"
    copy_mediasize_e_34x44in_str_id = "cMediaSizeIdANSIE"
    copy_mediasize_2l_127x178_str_id = "cMediaSizeIdSize2L"
    copy_mediasize_envelope_6_three_quarter_str_id = "cMediaSizeIdEnvelope6ThreeQuarter"
    copy_mediasize_super_b_13x19in_str_id = "cMediaSizeIdSuperB"
    copy_mediasize_arch_e1_762x1067mm_str_id = "cMediaSizeIdArchE1"
    copy_mediasize_l_3_5x5in_str_id = "cMediaSizeIdSizeL9x13cm"
    copy_mediasize_envelope_9_str_id = "cMediaSizeIdEnvelope9"
    copy_mediasize_4x12in_str_id = "cMediaSizeIdFourXTwelveTenXThirty"
    copy_mediasize_4x5in_str_id = "cMediaSizeIdFourXFiveTenXThirteen"
    copy_mediasize_5x5in_str_id = "cMediaSizeIdFiveXFiveThirteenXThirteen"
    copy_mediasize_8k_260x368mm_str_id = "cMediaSizeIdSize8K260x368"
    copy_mediasize_8k_270x390mm_str_id = "cMediaSizeIdSize8K270x390"
    copy_mediasize_8k_273x394mm_str_id = "cMediaSizeIdEightK"
    copy_mediasize_ra3_305x430mm_str_id = "cMediaSizeIdRA3"
    copy_mediasize_ra4_215x305mm_str_id = "cMediaSizeIdRA4"
    copy_mediasize_sra3_320x450mm_str_id = "cMediaSizeIdSra3"
    copy_mediasize_sra4_225x320mm_str_id = "cMediaSizeIdSra4"
    copy_mediasize_b0_jis_1030x1456mm_str_id = "cMediaSizeIdJISB0"
    copy_mediasize_b1_jis_728x1030mm_str_id = "cMediaSizeIdJISB1"
    copy_mediasize_b2_jis_515x728mm_str_id = "cMediaSizeIdJISB2"
    copy_mediasize_b3_jis_364x515mm_str_id = "cMediaSizeIdJISB3"
    copy_mediasize_b4_jis_257x364mm_str_id = "cMediaSizeIdJisB4"
    copy_mediasize_ansi_c_17x22in_str_id = "cMediaSizeIdANSIC"
    copy_mediasize_11x14in_str_id = "cMediaSizeIdElevenXFourteen"
    copy_mediasize_letter_8x10in_str_id = "cMediaSizeIdEightXTen"
    copy_mediasize_index_3x5in_str_id = "cMediaSizeIdThreeXFive"
    copy_mediasize_any_str_id = "cMediaSizeIdAny"
    copy_mediasize_envelope_a2_str_id = "cMediaSizeIdA2Envelope"
    copy_mediasize_mixed_letter_legal = "cMediaSizeIdMixedLetterLegal"
    copy_mediasize_mixed_letter_ledger = "cMediaSizeIdMixedLetterLedger"
    copy_mediasize_mixed_a4_a3 = "cMediaSizeIdMixedA4A3"

    list_copySettings_outputScale = "#copySettingResize"
    view_copySettings_outputScale = "#copyResizeView"
    view_copySettings_outputScale_back_button = "#copyResizeView #BackButton"
    list_copySettings_outputScale_value = "#copySettingResize_2infoBlockRow"
    radio_outputScale_none = "#none"
    row_outputScale_none = "#noneRow"
    radio_copySettings_outputScale_custom = "#customRadioButton"
    row_copySettings_outputScale_custom = "#customRow"
    spinbox_copySettings_outputScale_custom = "#custom"
    radio_outputScale_fitToPage = "#fitToPage"
    row_outputScale_fitToPage = "#fitToPageRow"
    radio_outputScale_fullPage = "#fullPage"
    row_outputScale_fullPage ="#fullPageRow"
    radio_outputScale_legalToLetter = "#legalToLetter"
    row_outputScale_legalToLetter = "#legalToLetterRow"
    radio_outputScale_letterToA4_94 = "#letterToA4"
    row_outputScale_letterToA4_94 = "#letterToA4Row"
    radio_outputScale_a4ToLetter_91 = "#a4ToLetter"
    row_outputScale_a4ToLetter_91 = "#a4ToLetterRow"
    check_outputScale_includeMargins = "#fitToPageIncludeMargin"
    row_outputScale_includeMargins = "#CheckBoxOptionsfitToPageIncludeMargin"

    list_copySettings_paperSelection = "#copyPaperSelection"
    view_copySettings_paperSelection = "#copy_paperSelectionMenuList"
    view_copySettings_paperSelection_scrollbar = "#copy_paperSelectionMenuListScrollBar"
    copy_settings_paper_selection_media_size_custom_size_view = "#CopySettingsPaperSizeCustomView"
    copy_settings_paper_selection_media_size_custom_size_view_scroll = "#CopySettingsPaperSizeCustomViewScrollBar"
    copy_settings_paper_selection_media_size_custom_size_unit_measurement_combo_box = "#CopySettingsPaperSizeCustomView #SettingsSpiceComboBox"

    copy_settings_paper_selection_source = "#copy_paperSourceSettingsComboBox"
    copy_settings_paper_selection_source_combobox = "#copy_paperSourceComboBox"
    copy_settings_paper_selection_source_list_combobox = "#copy_paperSourceComboBoxpopupList"
    combo_option_paper_selection_source_auto = "#ComboBoxOptionsauto_"
    combo_option_paper_selection_source_roll1 = "#ComboBoxOptionsroll_dash_1"
    combo_option_paper_selection_source_roll2 = "#ComboBoxOptionsroll_dash_2"

    copy_settings_paper_selection_family = "#copy_mediaFamilySettingsComboBox"
    copy_settings_paper_selection_family_combobox = "#copy_mediaFamilyComboBox"
    copy_settings_paper_selection_family_list_combobox = "#copy_mediaFamilyComboBoxpopupList"
    combo_option_paper_selection_family_unknown = "#ComboBoxOptionsunknown"
    combo_option_paper_selection_family_poster = "#ComboBoxOptionsposter"
    combo_option_paper_selection_family_technical = "#ComboBoxOptionstechnical"
    combo_option_paper_selection_family_photo = "#ComboBoxOptionsphoto"
    combo_option_paper_selection_family_film = "#ComboBoxOptionsfilm"
    combo_option_paper_selection_family_bondandcoated = "#ComboBoxOptionsbondAndCoated"
    combo_option_paper_selection_family_blueprint = "#ComboBoxOptionsblueprint"
    combo_option_paper_selection_family_banner = "#ComboBoxOptionsbannerAndSign"
    combo_option_paper_selection_family_backlit = "#ComboBoxOptionsbacklit"
    combo_option_paper_selection_family_adhesive = "#ComboBoxOptionsadhesive"
    combo_option_paper_selection_family_custom = "#ComboBoxOptionscustom"

    copy_settings_folding_style = "#copy_foldingStyleMenuComboBox"
    copy_settings_folding_style_combobox = "#copy_foldingStyleComboBox"
    copy_settings_folding_style_combobox_list = "#copy_foldingStyleComboBoxpopupList"
    combo_option_folding_style_256 = "#foldingStyleComboBox256"
    combo_option_folding_style_259 = "#foldingStyleComboBox259"

    row_combo_copySettings_paperTray = "#copy_paperSourceSettingsComboBox"
    combo_copySettings_paperTray = "#copy_paperSourceComboBox"
    view_copySettings_paperSelection_paperTray = "#copy_paperSourceComboBoxpopupList"
    combo_paperTray_option_tray1 = "#ComboBoxOptionstray_dash_1"
    combo_paperTray_option_tray2 = "#ComboBoxOptionstray_dash_2"
    combo_paperTray_option_tray3 = "#ComboBoxOptionstray_dash_3"
    combo_paperTray_option_tray4 = "#ComboBoxOptionstray_dash_4"
    combo_paperTray_option_tray5 = "#ComboBoxOptionstray_dash_5"
    combo_paperTray_option_tray6 = "#ComboBoxOptionstray_dash_6"
    combo_paperTray_option_auto = "#ComboBoxOptionsauto_"
    combo_paperTray_option_alternate = "#ComboBoxOptionsalternate"
    combo_paperTray_option_manual = "#ComboBoxOptionsmanual"
    combo_paperTray_option_main = "#ComboBoxOptionsmain"

    slider_lighterDarker = "#scan_lighterDarkerMenuSlider"
    row_slider_lighterDarker = "#scan_lighterDarkerSettingsSlider"
    
    slider_backGroundCleanup = "#scan_backGroundCleanUpMenuSlider"
    row_slider_backGroundCleanup = "#scan_backGroundCleanUpSettingsSlider"
    
    slider_contrast = "#scan_contrastMenuSlider"
    row_slider_contrast = "#scan_contrastSettingsSlider"
    
    slider_autoTone = "#scan_autoToneLevelMenuSlider"
    checkbox_autoTone = "#scan_autoToneMenuCheckbox"
    switch_autoTone = "#scan_autoToneMenuSwitch"
    row_scanSettings_autoTone = "#scan_autoToneSettingsView"
    
    slider_autoPaperColorRemoval = "#scan_autoPaperColorRemovalLevelMenuSlider"
    checkbox_autoPaperColorRemoval = "#scan_autoPaperColorRemovalMenuCheckbox"
    switch_autoPaperColorRemoval = "#scan_autoPaperColorRemovalMenuSwitch"
    row_scanSettings_autoPaperColorRemoval = "#scan_autoPaperColorRemovalSettingsView"

    spinBox_numberOfCopies_textMouseArea = "#SpinBoxTextFieldMouseArea"

    list_copySettings_paperSize = "#copy_mediaSizeSettingsTextImage"
    view_copySettings_paperSelection_paperSize = "#copy_mediaSizeMenuSelectionList"
    view_copySettings_paperSize = "#copy_mediaSizeSettingsTextImage_2infoBlockRow"
    radio_paperSize_iso_a4_210x297mm = "#iso_a4_210x297mm"
    radio_paperSize_rotate_iso_a4_210x297mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a4_210x297mm_dot_rotated"
    radio_paperSize_iso_a5_148x210mm = "#iso_a5_148x210mm"
    radio_paperSize_rotate_iso_a5_148x210mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a5_148x210mm_dot_rotated"
    radio_paperSize_iso_a6_105x148mm = "#iso_a6_105x148mm"
    radio_paperSize_jis_b5_182x257mm = "#jis_b5_182x257mm"
    radio_paperSize_rotate_jis_b5_182x257mm = "#com_dot_hp_dot_ext_dot_mediaSize_dot_jis_b5_182x257mm_dot_rotated"
    radio_paperSize_na_letter_8_5x11in = "#na_letter_8_dot_5x11in"
    radio_paperSize_rotate_na_letter_8_5x11in = "#com_dot_hp_dot_ext_dot_mediaSize_dot_na_letter_8_dot_5x11in_dot_rotated" 
    radio_paperSize_na_legal_8_5x14in = "#na_legal_8_dot_5x14in"
    radio_paperSize_na_invoice_5_5x8_5in = "#na_invoice_5_dot_5x8dotdot_5in"
    radio_paperSize_na_executive_7_25x10_5in = "#na_executive_7_dot_25x10_dot_5in"
    radio_paperSize_na_foolscap_8_5x13in = "#na_foolscap_8_dot_5x13in"
    radio_paperSize_na_index_4x6_4x6in = "#na_index-4x6_4x6in"
    radio_paperSize_jpn_chou3_120x235mm ="#jpn_chou3_120x235mm"
    radio_paperSize_jpn_chou4_90x205mm ="#jpn_chou4_90x205mm"
    radio_paperSize_oe_photo_dash_l_3_dot_5x5incopy = "#oe_photo_dash_l_3_dot_5x5incopy"
    radio_paperSize_iso_c6_114x162mm = "#iso_c6_114x162mm"

    list_copySettings_paperType = "#copy_paperTypeSettingsTextImage"
    view_copySettings_paperSelection_paperType = "#copy_paperTypeMenuSelectionList"
    view_copySettings_paperType = "#copy_paperTypeSettingsTextImage_2infoBlockRow"
    radio_paperType_any = "#MenuValueany"
    radio_paperType_plain = "#MenuValuestationery"
    radio_paperType_ecoEfficient = "#MenuValuecom.hp.EcoSMARTLite"
    radio_paperType_matte_90gsm = "#MenuValuecom.hp.matte-90gsm"
    radio_paperType_matte_105gsm = "#MenuValuecom.hp.matte-105gsm"
    radio_paperType_matte_120gsm = "#MenuValuecom.hp.matte-120gsm"
    radio_paperType_matte_150gsm = "#MenuValuecom.hp.matte-150gsm"
    radio_paperType_matte_200gsm = "#MenuValuecom.hp.matte-200gsm"
    radio_paperType_brochure_matte = "#MenuValuecom.hp.brochure-matte"
    radio_paperType_glossy_130gsm = "#MenuValuecom.hp.glossy-130gsm"
    radio_paperType_glossy_160gsm = "#MenuValuecom.hp.glossy-160gsm"
    radio_paperType_glossy_200gsm = "#MenuValuecom.hp.glossy-200gsm"
    radio_paperType_glossy_tri_fold = "#com_dot_hp_dash_trifold_dash_brochure_dash_glossy_dash_150gsmcopy_paperType"
    radio_paperType_cardstock_glossy = "#com_dot_hp_dot_cardstock_dash_glossycopy_paperType"
    radio_paperType_user_defined_10 = "#MenuValuecom_dot_hp_dot_usertype_dash_10"

    load_paper_alert_detail = "#InformationTemplate #rowPiece1 #columnforText1 #alertDetailDescription1 #textColumn #contentItem"
    
      
    	 

    view_systemToastMessagesScreen = "#SpiceToast"
    copy_2sided_prompt = "#scanManualDuplexSecondPage"

    copy_color_automatic_str_id = "cAutomatic"
    copy_color_str_id = "cColor"
    copy_color_grayScale_str_id = "cChromaticModeGrayscale"

    copy_content_type_mixed_str_id = "cMixed"
    copy_content_type_photo_str_id = "cPhotographQuickSet"
    copy_content_type_text_str_id = "cText"
    copy_content_type_auto_str_id = "cAutomatic"
    copy_content_type_fine_str_id = "cFine"
    copy_content_type_image_str_id = "cImage"
    copy_content_type_glossy_str_id = "cGlossy"
    
    copy_blank_page_suppression_on_str_id = "cOn"
    copy_blank_page_suppression_off_str_id = "cOff"
    
    list_copySettings_booklet = "#copySettingBooklet"
    list_view_copySettings_booklet = "#copy_bookletView"
    list_copySettings_booklet_value = "#copySettingBooklet_2infoBlockRow"
    copy_booklet_format_on_str_id = "cBookletFormatOn"
    copy_booklet_format_off_str_id = "cBookletFormatOff"
    check_booklet_format_option = "#CheckBoxOptionsBookletFormat"
    row_booklet_format_option = "#bookletFormat"
    check_borders_on_each_page_option = "#CheckBoxOptionsBordersOnEachPage"
    row_borders_on_each_page_option = "#bordersOnEachPage"
    copy_booklet_options_scrollbar = "#copy_bookletViewScrollBar"
    row_booklet_fold_and_stitch_option  = "#foldAndStitch"
    copy_booklet_format_saddleStitch_str_id = "cFinishingBookletMaker"
    row_booklet_fold_and_stitch_custom_option  = "#Custom"
    
    list_watermark = "#scanSettingswatermark"
    list_view_watermark = "#scan_watermarkMenuList"
    list_watermark_value = "#scanSettingswatermark_2infoBlockRow"
    copy_watermark_options_scrollbar = "#scan_watermarkMenuListScrollBar"
    copy_watermark_text_none_str_id = "cNone"
    copy_watermark_text_draft_str_id = "cDraft"
    copy_watermark_text_confidential_str_id = "cConfidential"
    copy_watermark_text_secret_str_id = "cSecret"
    copy_watermark_text_top_secret_str_id = "cTopSecret"
    copy_watermark_text_urgent_str_id = "cUrgent"
    row_combo_watermarkType = "#scan_watermarkTypeSettingsComboBox"
    combo_watermarkType = "#scan_watermarkTypeComboBox"
    view_watermarkType = "#scan_watermarkTypeComboBoxpopupList"
    combo_watermarkType_option_none = "#ComboBoxOptionsnone"
    combo_watermarkType_option_text = "#ComboBoxOptionstextWatermark"
    button_watermark_text_MoreOptions = "#fromMoreOptions"
    view_watermark_text_MoreOptions_view = "#scan_watermarkTextView"
    watermark_done_button = "#scan_watermarkMenuList #doneButton"
    copy_combobox_scrollbar = "#comboBoxScrollBar"
    scan_settings_watermark_text_view_scrollbar = "#scan_watermarkTextViewScrollBar"
    scan_settings_watermark_constraints_message = "cUserWatermarkLimit"

    list_watermark_text = "#scan_watermarkText"
    list_watermark_first_page_only = "#scan_firstPageOnly"
    list_watermark_text_font = "#scan_watermarkTextFontComboBox"
    list_watermark_text_size = "#scan_watermarkTextSizeComboBox"

    list_darkness = "#scan_watermarkDarknessMenuSlider"
    row_darkness = "#scan_watermarkDarknessSettingsSlider"

    radio_watermark_text_draft = "#draftRadioButton"
    row_watermark_text_draft = "#draftRadioButtonRow"
    radio_watermark_text_confidential = "#confidentialRadioButton"
    row_watermark_text_confidential = "#confidentialRadioButtonRow"
    radio_watermark_text_secret = "#secretRadioButton"
    row_watermark_text_secret = "#secretRadioButtonRow"
    radio_watermark_text_top_secret = "#topSecretRadioButton"
    row_watermark_text_top_secret = "#topSecretRadioButtonRow"
    radio_watermark_text_urgent = "#urgentRadioButton"
    row_watermark_text_urgent = "#urgentRadioButtonRow"

    checkbox_first_page_only = "#onlyFirstPageCheckbox"
    row_combo_text_font = "#scan_watermarkTextFontSettingsComboBox"
    combo_text_font = "#scan_watermarkTextFontComboBox"
    view_text_font = "#scan_watermarkTextFontComboBoxpopupList"
    combo_text_font_letter_gothic = "#ComboBoxOptionsletterGothic"
    combo_text_font_antique_olive = "#ComboBoxOptionsantiqueOlive"
    combo_text_font_century_schoolbook = "#ComboBoxOptionscenturySchoolbook"
    combo_text_font_garamond = "ComboBoxOptionsgaramond"

    row_combo_text_size = "#scan_watermarkTextSizeSettingsComboBox"
    combo_text_size = "#scan_watermarkTextSizeComboBox"
    view_text_size = "#scan_watermarkTextSizeComboBoxpopupList"
    combo_text_size_thirtyPoint = "#ComboBoxOptionsthirtyPoint"
    combo_text_size_fortyPoint = "#ComboBoxOptionsfortyPoint"
    combo_text_size_sixtyPoint = "#ComboBoxOptionssixtyPoint"

    list_text_color = "#scanSettingsStampWatermarkTextcolor"
    list_text_color_value = "#scanSettingsStampWatermarkTextcolor_2infoBlockRow"
    list_view_text_color = "#scanSettingsStampWatermarkTextColorView"
    text_color_options_scrollbar = "#scanSettingsStampWatermarkTextColorViewScrollBar"
    radio_text_color_black = "#blackRadioButton"
    row_text_color_black = "#blackRadioButtonRow"
    radio_text_color_yellow = "#yellowRadioButton"
    row_text_color_yellow = "#yellowRadioButtonRow"
    radio_text_color_green = "#greenRadioButton"
    row_text_color_green = "#greenRadioButtonRow"
    radio_text_color_red = "#redRadioButton"
    row_text_color_red = "#redRadioButtonRow"
    radio_text_color_blue = "#blueRadioButton"
    row_text_color_blue = "#blueRadioButtonRow"
    radio_text_color_skyBlue = "#skyBlueRadioButton"
    row_text_color_skyBlue = "#skyBlueRadioButtonRow"
    radio_text_color_purple = "#purpleRadioButton"
    row_text_color_purple = "#purpleRadioButtonRow"

    watermark_text_field = "#scan_watermarkText"
    watermark_text_field_text = "#watermarkText"
    text_input = "#TextInput"
    button_keyboard_ok = "#enterKey1"

    slider_watermark_darkness = "#scan_watermarkDarknessMenuSlider"
    row_slider_watermark_darkness = "#scan_watermarkDarknessSettingsSlider"

    copy_paper_type_any_str_id = "cMediaTypeIdAnySupportedType"
    copy_paper_type_plain_str_id = "cMediaTypeIdPlain"
    copy_paperType_ecoEfficient_str_id = "cMediaTypeIdHPEcoSmartLite"
    copy_paperType_matte_90_str_id = "cMediaTypeIdHPMatte90gsm"
    copy_paperType_matte_105_str_id = "cMediaTypeIdHPMatte105gsm"
    copy_paperType_matte_120_str_id = "cMediaTypeIdHPMatte120Gsm"
    copy_paperType_matte_150_str_id = "cMediaTypeIdHPMatte160gsm"
    copy_paperType_matte_200_str_id = "cMediaTypeIdHPMatte200gsm"
    copy_paperType_prem_matte_str_id = "cMediaTypeIdHPPremMattePhotoPaper"
    copy_paperType_brochure_glossy_str_id = "cMediaTypeIdHPBrochureGlossy"
    copy_paperType_glossy_120_str_id = "cMediaTypeIdHPGlossy130gsm"
    copy_paperType_glossy_150_str_id = "cMediaTypeIdHPGlossy160gsm"
    copy_paperType_glossy_200_str_id = "cMediaTypeIdHPGlossy220gsm"
    copy_paperType_glossy_tri_fold_str_id = "cMediaTypeIdHPTrifoldBrochureGlossy"
    copy_paperType_light_str_id = "cMediaTypeIdPlainLightRecycled"
    copy_paperType_intermediate_str_id = "cMediaTypeIdIntermediate"
    copy_paperType_mid_weight_str_id = "cMediaTypeIdMidWeight"
    copy_paperType_heavy_str_id = "cMediaTypeIdPlainThick"
    copy_paperType_extra_heavy_str_id = "cMediaTypeIdExtraHeavy"
    copy_paperType_card_stock_str_id = "cMediaTypeIdCardstock"
    copy_paperType_heavy_glossy_str_id = "cMediaTypeIdHeavyGlossy"
    copy_paperType_labels_str_id = "cMediaTypeIdLabels"
    copy_paperType_envelope_str_id = "cMediaTypeIdEnvelope"
    copy_paperType_heavy_envelope_str_id = "cMediaTypeIdHeavyEnvelope"
    copy_paperType_bond_str_id = "cMediaTypeIdBond"
    copy_paperType_light_bond_str_id = "cMediaTypeIdLightBond"
    copy_paperType_recycled_str_id = "cMediaTypeIdRecycled"
    copy_paperType_rough_str_id = "cMediaTypeIdRough"
    copy_paperType_heavy_rough_str_id = "cMediaTypeIdHeavyRough"
    copy_paperType_light_rough_str_id = "cMediaTypeIdLightRough"
    copy_paperType_preprinted_str_id = "cMediaTypeIdStationeryPreprinted"
    copy_paperType_letterhead_str_id = "cMediaTypeIdStationeryLetterhead"
    copy_paperType_extra_heavy_glossy_str_id = "cMediaTypeIdExtraHeavyGloss"
    copy_paperType_cardstock_glossy_str_id = "cMediaTypeIdCardstockGlossy"
    copy_paperType_prepunched_str_id = "cMediaTypeIdStationeryPrepunched"
    copy_paperType_colored_str_id = "cMediaTypeIdColor"
    copy_paperType_opaque_film_str_id = "cMediaTypeIdFilmOpaque"
    copy_paperType_transparency_str_id = "cMediaTypeIdTransparency"
    copy_paperType_photographic_glossy_str_id = "cMediaTypeIdPhotoGlossPaper"
    copy_paperType_trifold_brochure_glossy_str_id = "cMediaTypeIdTriFoldBrochureGlossy"
    copy_paperType_heavy_paperboard_str_id = "cMediaTypeIdHeavyPaperboard"
    copy_paperType_paperboard_str_id = "cMediaTypeIdPaperboard"
    copy_paperType_light_paperboard_str_id = "cMediaTypeIdLightPaperboard"
    copy_paperType_tab_stock_str_id = "cMediaTypeIdTabStock"
    copy_paperType_hp_advanced_photo_str_id = "cMediaTypeIdHPAdvancedPhoto"
    copy_paperType_hp_soft_gloss_120g_str_id = "cMediaTypeIdHPSoftGloss120gsm"
    copy_paperType_hp_midweight_glossy_str_id = "cMediaTypeIdMidWeightNinetySix"
    copy_paperType_hp_photographic_inkjet_str_id = "cMediaTypeIdOtherPhotoInkjet"
    copy_paperType_hp_matte_brochure_str_id = "cMediaTypeIdMatteBrochureProfessional"
    copy_paperType_hp_matte_presentation_str_id = "cMediaTypeIdMattePresentation"
    copy_paperType_hp_matte_inkjet_str_id = "cMediaTypeIdOtherMatteInkjet"
    copy_paperType_hp_specialty_glossy_str_id = "cMediaTypeIdGlossyBrochureProfessional"
    copy_paperType_hp_specialty_glossy_inkjet_str_id = "cMediaTypeIdOtherGlossyInkjet"
    copy_paperType_hp_specialty_hagaki_str_id = "cMediaTypeIdInkjetHagaki"
    copy_paperType_hp_matte_photo_duplex_str_id = "cMediaTypeIdHPMattePhoto"
    

    copy_paperTray_tray1_str_id = ["cTrayN", 1]
    copy_paperTray_tray2_str_id = ["cTrayN", 2]
    copy_paperTray_tray3_str_id = ["cTrayN", 3]
    copy_paperTray_auto_str_id = "cAutomatic"

    copy_pagesPerSheet_oneup_str_id = "cOutputNupCountTypeONE"
    copy_pagesPerSheet_twoup_str_id = "cTwo"
    copy_pagesPerSheet_fourup_right_then_down_str_id = "cFourRightThenDown"
    copy_pagesPerSheet_fourup_down_then_right_str_id = "cOutputNupCountTypeFour"

    copy_contentType_mixed_str_id = "cMixed"
    copy_contentType_photo_str_id = "cScanModeGlossy"
    copy_contentType_text_str_id = "cScanModeText"
    copy_contentType_lines_str_id = "cLines"
    copy_contentType_image_str_id = "cImage"

    copy_quality_standard_str_id = "cStandard"
    copy_quality_best_str_id = "cBestLabel"
    copy_quality_draft_str_id = "cDraft"

    copy_printOptions_str_id = "cPrintOptions"
    copy_numberOfCopies_str_id = "cNumberOfCopies"
    copy_quality_str_id = "cQuality"
    copy_pagesPerSheet_str_id = "cPagesPerSheet"
    copy_resize_str_id = "cOutputScale"
    copy_collateToggle_str_id = "cCollate"
    copy_margins_str_id = "cCopyMargins"
    copy_paperSelection_str_id = "cPaperSelectTitle"
    copy_mediaSize_str_id = "cMediaSize"
    copy_paperType_str_id = "cPaperType"
    copy_paperTray_str_id = "cPaperTray"
    copy_sides_str_id = "cSides"
    scan_scanOptions_str_id = "cScanOptions"
    scan_contentType_str_id = "cContentType"
    scan_colorMode_str_id = "cColorMode"
    scan_pageFlipUpEnabled_str_id = "c2SidedPages"
    scan_originalSize_str_id = "cOriginalSize"
    scan_lighterDarker_str_id = "cLighterDarker"
    copy_contrast_str_id = "cContrast"
    copy_booklet_str_id = "cBooklet"
    copy_background_cleanup_str_id = "cBackgroundCleanup"
    copy_automatically_straighten_str_id = "cAutomaticallyStraighten"
    copy_scan_mode_str_id = "cScanMode"
    copy_sharpness_str_id = "cSharpness"
    copy_trays_str_id = "cTrays"
    copy_output_bin_str_id = "cOutputDestination"
    copy_content_orientation_str_id = "cContentOrientation"
    copy_fold_str_id = "cFold"
    copy_watermark_str_id = "cWatermarkTitle"
    copy_stamp_str_id = "cStamps"

    copy_options_printOptions_title = "#copy_printOptionsSettingsTitleText"
    copy_options_scanOptions_title = "#scan_scanOptionsSettingsTitleText"

    copy_button_copy_str_id = "cCopy"
    copy_button_preview_str_id = "cPreviewLabel"
    done_string_id_button = "cDoneButton"
    start_string_id_button = "cStart"
    constraint_string_msg = "#ConstraintMessage"

    copy_sides_1to1_str_id = "c1To1Sided"
    copy_sides_1to2_str_id = "c1To2Sided"
    copy_sides_2to1_str_id = "c2To1Sided"
    copy_sides_2to2_str_id = "c2To2Sided"

    copy_outputScale_none_str_id = "cNone"
    copy_outputScale_fitToPage_str_id = "cFitToPage"
    copy_outputScale_fullPage_str_id = "cFullPage"
    copy_outputScale_legalToletter_str_id = "cLegalToLetter"
    copy_outputScale_letterToA4_str_id = "cLettertoA4"
    copy_outputScale_A4Toletter_str_id = "cA4ToLetter"
    copy_outputScale_custom_str_id ="cCustomPara"

    list_copy_staple = "#copy_stapleSettingsTextImage"
    list_copy_staple_value = "#copy_stapleSettingsTextImage_2infoBlockRow"
    copy_stapleMenuSelectionList = "#copy_stapleMenuSelectionList"
    
    radio_staple_none = "#MenuValuenone"
    row_staple_none = "#nonecopy_staple"
    
    radio_staple_topAnyOnePointAny = "#MenuValuetopAnyOnePointAny"
    row_staple_topAnyOnePointAny = "#topAnyOnePointAnycopy_staple"
    
    radio_staple_topLeftOnePointAny = "#MenuValuetopLeftOnePointAny"
    row_staple_topLeftOnePointAny = "#topLeftOnePointAnycopy_staple"

    radio_staple_topRightOnePointAngled= "#MenuValuetopRightOnePointAngled"
    row_staple_topRightOnePointAngled = "#topRightOnePointAngledcopy_staple"

    radio_staple_leftTwoPoints = "#MenuValueleftTwoPoints"
    row_staple_leftTwoPoints = "#leftTwoPointscopy_staple"


    copy_staple_none_str_id = "cNone"
    copy_staple_topAnyOnePointAny_str_id = "cStapleTopLeftOrRight"
    copy_staple_leftTwoPoints_str_id = "cStapleLeftTwoPoints"
    copy_staple_topLeftOnePointAngled_str_id = "cStapleTopLeftOnePointAngled"
    copy_staple_topRightOnePointAngled_str_id = "cStapleTopRightOnePointAngled"

    list_copy_punch = "#copy_punchSettingsTextImage"
    list_copy_punch_value = "#copy_punchSettingsTextImage_2infoBlockRow"
    copy_punchMenuSelectionList = "#copy_punchMenuSelectionList"
    
    radio_punch_none = "#MenuValuenone"
    row_punch_none = "#nonecopy_punch"
    radio_punch_leftTwoPointDin = "#MenuValueleftTwoPointDin"
    row_punch_leftTwoPointDin = "#leftTwoPointDincopy_punch"
    radio_punch_rightTwoPointDin = "#MenuValuerightTwoPointDin"
    row_punch_rightTwoPointDin = "#rightTwoPointDincopy_punch"

    copy_punch_none_str_id = "cNone"
    copy_punch_leftTwoPointDin_str_id = "cStapleLeftTwoPoints"
    copy_punch_rightTwoPointDin_str_id = "cStapleRightTwoPoints"

    list_copy_fold = "#copySettingsfold"
    list_copy_fold_value = "#copySettingsfold_2infoBlockRow"
    copy_foldMenuSelectionList = "#copyFoldView"

  
    radio_fold_Vfold = "#V-fold"
    row_fold_Vfold = "#V-foldRow"

    radio_fold_Cfold = "#C-fold"
    row_fold_Cfold = "#C-foldRow"

    copy_fold_none_str_id = "cNone"
    copy_fold_cInwardTop_str_id = "cInwardcFoldLeftUp"
    copy_fold_vInwardTop_str_id = "cInwardVFold"

    row_fold_none = "#nonecopy_fold"

    view_menu_screen = "#landingPageMenuAppList"
    copyFolder_home_screen = "#copy"
    button_menu_copy = "#copyMenuApp"
    view_menu_copy_screen = "#copyMenuAppList"
    button_menu_copy_copy = "#cedab422-33b3-4638-b6a1-604e54525215MenuApp"
    scrollBar_menucopyFolderLanding = "#copyMenuAppListScrollBar" 
    copyFolderPage_column_name =  "#copyMenuAppListcolumn"
    copyFolderPage_Content_Item =  "#copyMenuAppListlistItem"

    #Copy Widget objects
    spinBox_widget_numberOfCopies = "#copyWidgetSpinBox"
    button_widget_startCopy = "#copyWidgetStartButton"
    button_widget_gotoCopyApp = "#copyWidgetSettingsButton"
    button_widget_incrementCopyCount = "#upBtn"
    button_widget_decrementCopyCount = "#downBtn"
    save_as_default_button = "#savePanelButton"

    default_quickset_button = "#Default"
    mixed_content_quicksetId = "61b72f38-1945-11ed-bf29-87d40f139a32"
    blueprint_quicksetId = "eba1f540-239d-11ed-83d5-0b139473ea60"
    color_quicksetId = "34cc69d4-194f-11ed-89dc-4be3ffadc2eb"
    greyscale_quicksetId = "ccf3c448-250a-11ed-851e-d37653ac82ab"
    image_quicksetId = "dba2ec94-250a-11ed-b62b-eb3183c3f17f"
    blueprint_red_stamp_quicksetId =  "c2306e7e-c4b7-11ed-a0a1-8776890b7239"

    #Save as Default
    view_menu_save_options = "#SaveOptionsForQSlist1"
    copy_as_defaults_option = "#AsDefaults"
    save_as_default_alert_view = "#ConfirmMessage"
    
    save_as_default_alert_save_button = "#messageSave"
    #need to update ok button id when DUNE-72337 is fixed.
    ok_under_save_option_veiw = "#saveoptionFooter #FooterViewRight #ContentItemText"

    defaults_and_quick_sets_view = "#SpiceListViewView"
    quickset_list_box = "#QSListofApp"
    quickset_selection_view = "#qsScroll"
    # need to update close button id when HMDE-630 is fixed.
    # close_button_under_quick_sets_view = "#QSListofAppHeader #rightBlockObject #ContentItem"
    close_button_under_quick_sets_view = "#CloseQuicksetList"

    qs_scroll_horizontal_bar = "#qsScrollhorizontalScroll"
    view_all_locator = "#ViewAll"
    ok_button_menu_quickset_no_quickset = "#OKButton"
    close_copy_settings_button = "#closeButton"

    text_toastInfoText = "#infoTextToastMessage"
    keyboard_view = "#spiceKeyboardView"
    ok_enterKeyPositiveIntegerKeypad = "#enterKeyPositiveIntegerKeypad"

    view_constraint_message = "#ConstraintMessage"
    constraint_message_text = "#ConstraintMessage #constraintDescription SpiceText[objectName=contentItem]"
    ok_button_constrained_message = "#ConstraintMessage #okButton"

    button_preview="#previewButton"
    button_preview_large="#previewButtonLargeScreen"
    refresh_preview_button = "#refreshPanelButton"
    refresh_modal_dialog_screen = "#refreshPreviewPanel"
    preview_image = "#image_0"
    refresh_modal_dialog_refresh_button = "#refreshPreviewButton"
    button_collapse_secondarypanel="#_CollapseButton"
    button_expand_secondarypanel="#_ExpandButton"
    preview_panel="#itempreview"
    button_startCopy_mainpanel="#mainActionButtonOfMainPanel"
    button_startCopy_preivewpanel="#mainActionButtonOfMainPanel"
    fitapge_layout="#FitPage"
    first_preview_image="#image_0"
    cancel_button_previewpanel="#cancelButtonPreviewPanel"
    pre_preview_layout ="#prePreview"
    pre_preview_content = "#contentText"
    pre_preview_animation = "#animationImage"
    copy_cancel_button= "#cancelButton"
    duplex_copy_continue = "#Continue"
    drop_down_button = "#dropDownButton"

    prepreview_enabled_string_id = "cConfigurePreviewSettings"
    prepreview_disabled_string_id = "cDisablePreviewSettings"

    media_mismatch_flow="#mediaMismatchSizeFlowWindow"
    media_mismatch_alert_ok="#OK"
    media_mismatch_alert_print = "#Print"
    media_mismatch_alert_hide = "#Hide"

    # output_scale_options
    option_output_scale_menu_loctor = "#copySettingResize"
    output_scale_str_id = "cOutputScale"
    option_output_scale_button_locator = "#copySettingResize_2infoBlockRow"
    option_output_scale_set_loaded_paper = "#scaleToOutputRowRadioButton"
    option_output_scale_set_loaded_paper_detail ="#scaleToOutputRowComboBox"
    option_output_scale_set_loaded_paper_detail_roll ="#main_dash_roll"
    option_output_scale_set_loaded_paper_detail_tray = "#main"
    option_output_scale_set_loaded_paper_detail_roll_1 = "#roll_dash_1"
    option_output_scale_set_loaded_paper_detail_sheet = "#top"
    option_output_scale_set_standard_sizes = "#standardSizeScalingRowRadioButton"
    option_output_scale_set_standard_sizes_detail = "#standardSizeScalingRowComboBox"
    option_output_scale_set_standard_sizes_detail_a0 = "#iso_a0_841x1189mm"
    option_output_scale_set_standard_sizes_detail_a1 = "#iso_a1_594x841mm"
    option_output_scale_set_standard_sizes_detail_a2 = "#iso_a2_420x594mm"
    option_output_scale_set_standard_sizes_detail_a3 = "#iso_a3_297x420mm"
    option_output_scale_set_standard_sizes_detail_a4 = "#iso_a4_210x297mm"
    option_output_scale_set_standard_sizes_detail_b1 = "#iso_b1_707x1000mm"
    option_output_scale_set_standard_sizes_detail_b2 = "#iso_b2_500x707mm"
    option_output_scale_set_standard_sizes_detail_b3 = "#iso_b3_353x500mm"
    option_output_scale_set_standard_sizes_detail_b4 = "#iso_b4_250x353mm"
    option_output_scale_set_standard_sizes_detail_letter = "#na_letter_8_dot_5x11in"
    option_output_scale_set_standard_sizes_detail_ledger = "#na_ledger_11x17in"
    option_output_scale_set_standard_sizes_detail_ansi_c = "#na_c_17x22in"
    option_output_scale_set_standard_sizes_detail_ansi_d = "#na_d_22x34in"
    option_output_scale_set_standard_sizes_detail_ansi_e = "#na_e_34x44in"
    option_output_scale_set_standard_sizes_detail_arch_a = "#na_arch_dash_a_9x12in"
    option_output_scale_set_standard_sizes_detail_arch_b = "#na_arch_dash_b_12x18in"
    option_output_scale_set_standard_sizes_detail_arch_c = "#na_arch_dash_c_18x24in"
    option_output_scale_set_standard_sizes_detail_arch_d = "#na_arch_dash_d_24x36in"
    option_output_scale_set_standard_sizes_detail_arch_e = "#na_arch_dash_e_36x48in"
    standard_sizes_optionView = "#standardSizeScalingRowComboBoxpopupList"
    standard_sizes_scrollbar = "#comboBoxScrollBar"

    options_view = "#copySettingsPage_"
    options_view_scrollbar = "#copySettingsPage_list1ScrollBar"
    view_optionView = "#copySettingsPage_list1"

    copy_release_pagePrompt_pagebtn ="#CopyReleasePagebtn"
    copy_relase_pagePrompt = "#mdfEjectPage"

    spiceView = "#SpiceView"

    copy_active_job_modal = "#ActiveJobModalView"
    copy_active_job_modal_text_locator = copy_active_job_modal +" #textImage2 SpiceText[objectName=titleSmallItem]"
    copy_active_job_modal_header_text_locator = copy_active_job_modal + " #SpiceHeaderVar1 SpiceText[objectName=titleObject]"
    copy_wizard_completion_active_job_modal_ok_button = copy_active_job_modal +" #okButton"
    copy_adf_warning_modal_dialog = "#adfLoadedWarningModal"

    jobs_app_job_reprint_screen_cancel_btn = "#cancelButtonJobReprintScreen"
    jobs_app_job_reprint_screen_spin_box = "#SpinCopiesJobReprintScreen"
    jobs_app_job_reprint_screen_reprint_btn = "#reprintButtonJobReprintScreen"
    jobs_app_reprint_btn = "#reprintButton"
    jobs_app_deletejob_btn = "#deleteJobButton"
    jobs_app_deletejob_confirm_btn = "#deleteJobDeleteAnywayButton"
    
    copy_cancel_job_warning_prompt = "#CancelJobWarningPrompt"
    copy_cancel_job_warning_prompt_primary_button = copy_cancel_job_warning_prompt + " #cancelJobWarningPrimaryButton"
    copy_cancel_job_warning_prompt_secondary_button = copy_cancel_job_warning_prompt + " #cancelJobWarningSecondaryButton"

    copy_option_header_section = "#SpiceHeaderVar2"
    view_copy_widgetCardCopyApp_screen = "#widgetCardCopyApp"
    view_idCopyScreen = "#idCopyLandingView"
    button_idCopyMoreOptions = "#optionsDetailPanelButton"
    view_idCopySettingsView = "#idCardCopySettingsPagelist1"
    app_copy_home_screen = "#copy"
    
    collate_limit_warning_alert = "#collateProblemWindow"
    collate_limit_warning_alert_ok_button = "#OK"

    more_pages_detected_for_collate_window = "#morePagesDetectedForCollateWindow"
    more_pages_collate_window_copy_continue_button = "#CopyContinueButton"
    more_pages_collate_window_copy_cancel_button = "#CopyCancelButton"

    button_add_page = "#previewFitPageContainer #scrollArea #grid #gridLayoutView  #gridLayout #addPageButton"
    button_ok_button_add_page = "#addPageOkButton"
    preview_add_page_prompt= "#previewAddPagePrompt"
    add_page_header = "#addpageHeader"
    pre_preview = "#prePreview"
    preview_warning_icon = "#icon_0"
    
    # related to stamp option
    stamp_none_string_id = "cNone"
    stamp_multiple_string_id = "cMultiple"
    stamp_required_string_id = "cRequiredFieldLabel"
    stamp_ipAddress_string_id = "cIPAddress"
    stamp_userName_string_id = "cUserName"
    stamp_productInformation_string_id = "cProductInformation"
    stamp_pageNumber_string_id = "cPageNumber"
    stamp_dateAndTime_string_id = "cDateAndTime"
    stamp_date_string_id = "cDate"
    
    stamp_number_strig = "cPageNumberingFormatTypePageFormat2"
    stamp_page_plus_number_strig = "cPageNumberingFormatTypePageFormat1"
    stamp_hyphen_number_strig = "cPageNumberingFormatTypePageFormat5"
    
    stamp_antique_string = "cAntiqueOlive"
    stamp_century_string = "cCenturySchoolbookFont"
    stamp_garamond_string = "cGaramond"
    stamp_letter_string = "cLetterGothic"
    
    stamp_eight_point_string = "cStampTextSizeTypeSize8"
    stamp_twelve_point_string = "cStampTextSizeTypeSize12"
    stamp_twenty_point_string = "cStampTextSizeTypeSize20"
    
    stamp_black_text_color_string = "cColorBlack"
    stamp_blue_text_color_string = "cColorBlue"
    stamp_green_text_color_string = "cColorGreen"
    stamp_purple_text_color_string = "cColorPurple"
    stamp_red_text_color_string = "cColorRed"
    stamp_skyBlue_text_color_string = "cColorLightBlue"
    stamp_yellow_text_color_string = "cColorYellow"
    
    list_stamp_menu = "#scanSettingsStampsMenu"
    list_stamp_value = "#scanSettingsStampsMenu_2infoBlockRow"
    list_stamp_view = "#scan_stampsMenuList"
    stamp_location_view_back_button = "#scan_stampsMenuList #BackButton"
    stamp_view_scroll_bar = "#scan_stampsMenuListScrollBar"
    
    list_stamp_topLeft = "#scan_stampTopLeftList"
    list_stamp_topLeft_value = "#scan_stampTopLeftList_2infoBlockRow"
    
    list_stamp_topCenter = "#scan_stampTopCenterList"
    list_stamp_topCenter_value = "#scan_stampTopCenterList_2infoBlockRow"
    
    list_stamp_topRight = "#scan_stampTopRightList"
    list_stamp_topRight_value = "#scan_stampTopRightList_2infoBlockRow"
    
    list_stamp_bottomLeft = "#scan_stampBottomLeftList"
    list_stamp_bottomLeft_value = "#scan_stampBottomLeftList_2infoBlockRow"
    
    list_stamp_bottomCenter = "#scan_stampBottomCenterList"
    list_stamp_bottomCenter_value = "#scan_stampBottomCenterList_2infoBlockRow"
    
    list_stamp_bottomRight = "#scan_stampBottomRightList"
    list_stamp_bottomRight_value = "#scan_stampBottomRightList_2infoBlockRow"
    
    list_stamp_settings_view = "#stampSettingsView"
    stamp_settings_view_scroll_bar = "#stampSettingsViewScrollBar"
    
    stamp_settings_text_feild = "#stampContentTextFeild #TextInput"
    stamp_settings_bubbule = "#stampContentTextFeild #bubbleItem"
    stamp_settings_bubbule1 = "#stampContentTextFeild #bubbleItem0 #bubbleMouseArea"
    stamp_settings_bubbule_text1 = "#stampContentTextFeild #bubbleItem0 #EmailText"
    stamp_settings_content_button = "#stampContentButton"
    stamp_settings_done_button = "#stampSettingDoneButton"
    
    row_stamp_starting_page_spinBox = "#stampStartingPageSpinBoxRow"
    stamp_starting_page_spinBox = "#stampStartingPageSpinBox"
    stamp_starting_page_plus = "#stampStartingPageSpinBox #upBtn"
    stamp_starting_page_minus = "#stampStartingPageSpinBox #downBtn"
    stamp_starting_page_textArea = "#stampStartingPageSpinBox #SpinBoxTextInput"
    
    row_stamp_starting_number_spinBox = "#stampStartingNumberSpinBoxRow"
    stamp_starting_number_spinBox = "#stampStartingNumberSpinBox"
    stamp_starting_number_plus = "#stampStartingNumberSpinBox #upBtn"
    stamp_starting_number_minus = "#stampStartingNumberSpinBox #downBtn"
    stamp_starting_number_textArea = "#stampStartingNumberSpinBox #SpinBoxTextInput"
    
    row_stamp_number_of_digit_spinBox = "#stampNumberOfDigitsSpinBoxRow"
    stamp_number_of_digit_spinBox = "#stampNumberOfDigitsSpinBox"
    stamp_number_of_digit_plus = "#stampNumberOfDigitsSpinBox #upBtn"
    stamp_number_of_digit_minus = "#stampNumberOfDigitsSpinBox #downBtn"
    stamp_number_of_digit_textArea = "#stampNumberOfDigitsSpinBox #SpinBoxTextInput"
    
    stamp_comboBox_scrollbar = "#comboBoxScrollBar"
    view_stamp_comboBox = "#SettingsSpiceComboBoxpopupList"
    
    row_stamp_page_numbering_comboBox = "#stampPageNumberingComboBoxRow"
    stamp_page_numbering_comboBox = "#stampPageNumberingComboBoxRow #SettingsSpiceComboBox"
    combo_stamp_number = "#numberComboBox"
    combo_stamp_page_plus_number = "#pagePlusNumberComboBox"
    combo_stamp_hyphen_number = "#hyphenNumberHyphenComboBox"
    
    row_stamp_text_color = "#stampTextColorImageTextBranchRow"
    row_stamp_text_color_value = "#stampTextColorImageTextBranchRow_2infoBlockRow"
    
    row_stamp_text_font_comboBox = "#stampTextFontComboBoxRow"
    stamp_text_font_comboBox = "#stampTextFontComboBoxRow #SettingsSpiceComboBox"
    combo_stamp_antiqueOlive = "#antiqueOliveComboBox"
    combo_stamp_centurySchoolbook = "#centurySchoolbookComboBox"
    combo_stamp_garamond = "#garamondComboBox"
    combo_stamp_letterGothic = "#letterGothicComboBox"
    
    row_stamp_text_size_comboBox = "#stampTextSizeComboBoxRow"
    stamp_text_size_comboBox = "#stampTextSizeComboBoxRow #SettingsSpiceComboBox"
    combo_stamp_eightPoint = "#eightPointComboBox"
    combo_stamp_twelvePoint = "#twelvePointComboBox"
    combo_stamp_twentyPoint = "#twentyPointComboBox"
    
    row_stamp_white_background_checkBox = "#stampWhiteBackgroundCheckBoxRow"
    stamp_white_background_checkBox = "#stampWhiteBackgroundCheckBox"
    
    list_stamp_content_view = "#stampContentView"
    stamp_content_done_button = "#stampContentDoneButton"
    stamp_content_edit_button = "#stampContentEditButton"
    stamp_content_view_scrollbar = "#stampContentViewScrollBar"
    
    row_stamp_ipAddress_checkBox = "#ipAddressCheckBoxRow"
    stamp_ipAddress_checkBox = "#ipAddressCheckBox"
    row_stamp_userName_checkBox = "#userNameCheckBoxRow"
    stamp_userName_checkBox = "#userNameCheckBox"
    row_stamp_productInformation_checkBox = "#productInformationCheckBoxRow"
    stamp_productInformation_checkBox = "#productInformationCheckBox"
    row_stamp_page_number_checkBox = "#pageNumberCheckBoxRow"
    stamp_page_number_checkBox = "#pageNumberCheckBox"
    row_stamp_dateAndTime_checkBox = "#dateAndTimeCheckBoxRow"
    stamp_dateAndTime_checkBox = "#dateAndTimeCheckBox"
    row_stamp_date_checkBox = "#dateCheckBoxRow"
    stamp_date_checkBox = "#dateCheckBox"
    row_stamp_user_defined_1_checkBox = "#userDefined1CheckBoxRow"
    stamp_user_defined_1_checkBox = "#userDefined1CheckBox"
    row_stamp_user_defined_2_checkBox = "#userDefined2CheckBoxRow"
    stamp_user_defined_2_checkBox = "#userDefined2CheckBox"
    row_stamp_user_defined_3_checkBox = "#userDefined3CheckBoxRow"
    stamp_user_defined_3_checkBox = "#userDefined3CheckBox"
    row_stamp_admin_defined_1_checkBox = "#adminDefined1CheckBoxRow"
    stamp_admin_defined_1_checkBox = "#adminDefined1CheckBox"
    row_stamp_admin_defined_2_checkBox = "#adminDefined2CheckBoxRow"
    stamp_admin_defined_2_checkBox = "#adminDefined2CheckBox"
    row_stamp_admin_defined_3_checkBox = "#adminDefined3CheckBoxRow"
    stamp_admin_defined_3_checkBox = "#adminDefined3CheckBox"
    
    list_stamp_edit_order_view = "#stampEditOrderView"
    stamp_edit_order_down_button = "#downButton"
    stamp_edit_order_up_button = "#upButton"
    stamp_edit_order_done_button = "#stampEditOrderDoneButton"
    stamp_edit_order_view_scrollbar = "#stampEditOrderViewScrollBar"
    
    row_stamp_ipAddress_radioButton = "#ipAddressRadioButtonRow"
    stamp_ipAddress_radioButton = "#ipAddressRadioButton"
    row_stamp_userName_radioButton = "#userNameRadioButtonRow"
    stamp_userName_radioButton = "#userNameRadioButton"
    row_stamp_productInformation_radioButton = "#productInformationRadioButtonRow"
    stamp_productInformation_radioButton = "#productInformationRadioButton"
    row_stamp_page_number_radioButton = "#pageNumberRadioButtonRow"
    stamp_page_number_radioButton = "#pageNumberRadioButton"
    row_stamp_dateAndTime_radioButton = "#dateAndTimeRadioButtonRow"
    stamp_dateAndTime_radioButton = "#dateAndTimeRadioButton"
    row_stamp_date_radioButton = "#dateRadioButtonRow"
    stamp_date_radioButton = "#dateRadioButton"
    row_stamp_user_defined_1_radioButton = "#userDefined1RadioButtonRow"
    stamp_user_defined_1_radioButton = "#userDefined1RadioButton"
    row_stamp_user_defined_2_radioButton = "#userDefined2RadioButtonRow"
    stamp_user_defined_2_radioButton = "#userDefined2RadioButton"
    row_stamp_admin_defined_1_radioButton = "#adminDefined1RadioButtonRow"
    stamp_admin_defined_1_radioButton = "#adminDefined1RadioButton"
    row_stamp_admin_defined_2_radioButton = "#adminDefined2RadioButtonRow"
    stamp_admin_defined_2_radioButton = "#adminDefined2RadioButton"

    # Copy Mode items related to Copy App
    copymode_button = "#copyModeMainPanelButton"
    copymode_modal_indirect_copy_menu_radio_button = "#copyJobMode_afterScanningMenuRadioButton"
    copymode_modal_direct_copy_menu_radio_button = "#copyJobMode_whileScanningMenuRadioButton"
    copymode_modal_interrupt_copy_menu_radio_button = "#copyJobMode_interruptToggleMenuSwitch"
    copymode_modal_close_button = "#closeButton"

    copy_load_paper_alert="#mediaLoadFlowWindow"
    copy_adf_load_paper_alert="#titleObject"
    adf_add_prompt_start_button = "#adfAddPageWindow #bodyLayoutverticalLayout #FooterView #startButton"
    adf_add_prompt_cancel_button = "#adfAddPageWindow #bodyLayoutverticalLayout #FooterView #CancelButton"
    copy_load_paper_ok="#OK"
    copy_load_paper_hide="#hide"

    copy_preview_header = "#previewHeader"
    copy_preview_header_dropDown = "#dropDown"
    copy_preview_edit_header="#PreviewEditHeader"

    copy_preview_fitpage_container = "#previewFitPageContainer"
    copy_switch_preview_layout_button = "#switchPreviewLayoutButton"
    copy_preview_gridview_container = "#previewGridViewContainer"

    quickCopyFooterSpinBox = "#quickCopySpinBox"
    homeScreenFooter = "#HomeScreenFooter"
    quickCopyFooter = "#copyQuickFooter"
    homeScreenFooterCopyButton = "#QuickCopyButton"

    scan_both_sides_for_book_mode = "#bookModeBothSidesRBModel"
    scan_skip_left_side_for_book_mode = "#bookModeSkipLeftSideRBModel"
    scan_skip_right_side_for_book_mode = "#bookModeSkipRightSideRBModel"
    button_scan_book_mode_instructions_scan = "#scanButton"
    book_mode_instructions_view = "#bookModeInstructionsView"
    button_scan_book_mode_instructions_finish = "#finishButton"
    scan_mode_done_button = "#copy_scanModeList #footerDoneButton"
    button_scan_book_mode_instructions_cancel = "#bookModeCancelButton"
    button_scan_add_page_flatbed_duplex_cancel_yes = "#yesButton"

    button_menupreviewSettings = "#imagePreviewSettingsSettingsTextImage"
    view_previewScreen = "#imagePreviewSettingsMenuList"
    view_copy_preview_configuration = "#copyPreviewSettingsTextImage_2infoBlockRow"
   
    scan_mode_back_button = "#copy_scanModeList #BackButton"
    copy_2_sided_id_prompt = "#scanManualDuplexSecondSide"
    copy_2_sided_id_scan_button = "#ScanButton"
    copy_2_sided_id_done_button = "#DoneButton"
    copy_2_sided_id_cancel_button = "#scanManualDuplexSecondSide #cancelButton" 
    copy_2_sided_id_prompt_text = "#scanManualDuplexSecondSide #alertDetailDescription SpiceText[objectName=contentItem]"
    copy_flatbed_cancel_job_prompt_yes_button = "#FlatbedCancelPrompt #yesButton"

    spinbox_copy = "#CopyQuickWidget #SpinBoxTextFieldMouseArea"
    spinbox_ok_key = "#keyboard #enterKeyPositiveIntegerKeypad"
    select_best_quality = "#ComboBoxOptionsbest #ComboBoxOptionsbestRadioButtonModel"

    #beam copy cancel job prompt
    button_cancel_job = "#JobModalView #cancelButton"
    button_active_job_cancel = "#ActiveJobModalView #cancelJobButton"

    alert_app_landing_view = "#alertAppView #alertAppHeader"
    alert_app_landing_view_close_button = "#alertAppView #alertAppHeader #closeButton"

    row_output_destination_comboBox = "#copy_outputDestinationSettingsComboBox"
    output_destination_comboBox = "#copy_outputDestinationComboBox"
   
    stop_scan_button = "#stopScanButtonDetailRightBlock"
    no_access_view = "#noAccessView"
    no_access_ok_button = "#noAccessOkButton"
    cartridgeMissingWindow = "#cartridgeMissing1Window"
    cartridgeHideButton = "#Hide"
