@startuml
title
<size:20><b>Copy Job Ticket Constraints</b></size>
end title
header HP Confidential
left footer \t(C) Copyright 2022 HP Development Company, L.P.\l\tAll rights reserved

participant JobTicketResourceManagerStandard as jtrm
participant CopyJobService as js
participant JobTicketResourceHelper as rh
participant TicketAdapter as ta
participant CopyJobConstraintsStandard as cs
participant CopyJobDynamicConstraintsStandard as dcst
participant CopyJobDynamicConstraintsLargeFormat as dclf

activate jtrm
activate js
activate rh
activate cs
activate dcst
activate dclf

jtrm -> rh : createTicketAdapter()
rh -> ta : (jobTicket, jobService)
activate ta
rh <-- ta
jtrm <-- rh 

jtrm -> ta : getConstraints()
ta -> js : getCopyJobConstraints()
note right of js
    CopyJobService got connected to CopyJobConstraints by graph
end note
ta <-- js

ta -> cs : getConstraints()
note right of cs
    Reads/Loads static constraints from csf file
end note
cs -> cs : getStaticConstraints()

cs -> dcst : updateTicketAndConstraints(jobTicket, constraintsSet)
cs <-- dcst

cs -> dclf : updateTicketAndConstraints(jobTicket, constraintsSet)
cs <-- dclf

ta <-- cs : constraintsSet
jtrm <-- ta : constraintsSet

@enduml