DUNE_ADD_FLAVOR()
    DUNE_LINK_LIBRARIES(
        framework/core/uuid
        framework/data/constraints
        framework/data/DataStore
        framework/resources/configuration
        localization/StringIds
        ws/cdm/framework/MicroServiceFactory
        ws/cdm/framework/resourceConstraintsHelper
        ws/cdm/services/CommonGlossary
        ws/cdm/services/Copy
        ws/framework/types
        framework/data/backup
        localization/LocaleProvider
    )
    DUNE_ADD_GTEST(framework/component/TestingUtil)
