DUNE_ADD_COMPONENT()
    DUNE_ADD_SRC_COMPONENT()
DUNE_LINK_LIBRARIES(framework/underware/Interpreter
    framework/component
    framework/data/DataStore
    framework/data/constraints
    framework/core/threadPool
    framework/storage/Nvram
    framework/core/uuid
    localization/LocaleProvider
    localization/StringIds
    job/Job
    job/JobService
    job/JobServiceManager
    job/JobManager
    job/PipeObject
    job/PipeQueue
    job/ResourceManager
    job/ResourceService
    job/types
    job/cdm/JobManagerCdmAdapter
    job/cdm/JobCdmHelper
    job/JobDetailsHelper
    job/JobDetailsManager
    job/JobTicketHandler
    imaging/types
    imaging/color/types
    imaging/PipeObjects/ImageContainer
    imaging/Resources/MarkingFilter
    imaging/Resources/LayoutFilter
    imaging/Resources/PageAssembler
    imaging/Resources/ImagePersister
    imaging/Resources/ImageRetriever
    imaging/Resources/ImageProcessor
    imaging/PipelineMemoryClientFactory
    imaging/RasterFormatSelectorFactory
    imaging/color/ColorDirector
    imaging/asset/ImagingAttributeManager
    scan/Resources/ScanDevice
    print/Resources/PrintDevice
    print/JobAccounting/StatsHelper
    copy/Jobs/Copy
    copy/Jobs/Copy/JobConstraints
    copy/Jobs/Copy/CopyJobDynamicConstraintRules
    copy/Jobs/Copy/CopyTicketConverter
    scan/Jobs/Scan
    scan/Jobs/Scan/ScanPipeline
    print/Resources/RtpFilter
    print/IntentsManager)
    if(DUNE_JPEG_HARDWARE_AVAILABLE)
        message("[CopyJobService] Jpeg hardware is available")
        DUNE_SET_CFLAGS(-DJPEG_HARDWARE_AVAILABLE)
    endif()
    if(DUNE_JPEG_DECODER_YCC_RGB_CONVERSION)
        message("[CopyJobService] Jpeg decoder YCC_RGB conversion is available")
        DUNE_SET_CFLAGS(-DJPEG_DECODER_YCC_RGB_CONVERSION)
    else()
        message("[CopyJobService] Jpeg decoder YCC_RGB conversion is NOT available")
    endif()
    if(${DUNE_INCLUDE_EFIVAR})
        DUNE_SET_CFLAGS(-DEFIVAR_EXIST)
    endif()
    #workaround to be able to build without errors
    DUNE_SET_CFLAGS("-Wno-error=parentheses")
    DUNE_SET_CFLAGS("-Wno-error=switch")
    DUNE_ADD_GTEST(framework/component/TestingUtil
                    print/Jobs/Print
                    security/ac/AccessControl)

