from enum import Enum

class BinLevel(Enum):
    Full = 1
    Empty = 2

class TrayLevel(Enum):
    Empty = 0
    Low = 1
    MediumLow = 2
    MediumHigh = 3
    High = 4
    Full = 5

class Edge(Enum):
    Short = 1
    Long = 2

class MediaOrientation(Enum):
    Default = 1
    Portrait = 2
    Landscape = 3

class Doors(Enum):
    NoDoor = 0
    FrontDoor = 1
    LeftDoor = 2
    RightDoor = 3
    Tray3AccessDoor = 4
    Tray4AccessDoor = 5
    Tray5AccessDoor = 6
    MultiTrayAccessDoor = 7
    HciAccessDoor = 8
    StaplerDoor = 9
    TrayTopDoor = 10
    TrayPulledOut = 11
    FinisherFrontDoor = 12
    FinisherTopDoor = 13
    FinisherBridgeDoor = 14
    FinisherJamDoor = 15
    FinisherPulledOut = 16
    FinisherRearDoor = 17
    ConditionerUpperFrontDoor = 18
    ConditionerInternalAccessDoor = 19
    FinisherUpperInternalDoor = 20
    ReloadableSuppliesAccessDoor = 21
    TopCover = 22
    RearDoor = 23

class MediaSize(Enum):
    Letter = 0
    Legal = 1
    Executive = 2
    Statement = 3
    EightPointFiveByThirteen = 4
    ThreeXFive = 5
    FourXSix = 6
    FiveXSeven = 7
    FiveXEight = 8
    A4 = 9
    A5 = 10
    A5Rotated = 11
    A6 = 12
    RA4 = 13
    JisB5 = 14
    JisB6 = 15
    Size10x15cm = 16
    Size16K195x270 = 17
    Size16K184x260 = 18
    SixteenK = 19
    JPostcard = 20
    JDoublePostcard = 21
    Envelope9 = 22
    COM10Envelope = 23
    MonarchEnvelope = 24
    B5Envelope = 25
    C5Envelope = 26
    EnvelopeC6 = 27
    DLEnvelope = 28
    Oficio216x340 = 29
    Any = 30
    Custom = 31
    AnyCustom = 32
    Unknown = 33
    A3 = 34
    A2 = 35
    A1 = 36
    A0 = 37
    Ledger = 38
    JisB4 = 39
    RA3 = 40
    Sra3 = 41
    Sra4 = 42
    TwelveByEighteen = 43
    EightK = 44
    Size8K270x390 = 45
    Size8K260x368 = 46
    SizeL9x13cm = 47
    JChou3Envelope = 48
    JChou4Envelope = 49
    ArchB = 50

class MediaType(Enum):
    Plain = 0
    HPMatte90gsm = 1
    HPMatte105gsm = 2
    HPMatte120Gsm = 3
    HPMatte160gsm = 4
    HPMatte200gsm = 5
    HPSoftGloss120gsm = 6
    HPGlossy130gsm = 7
    HPGlossy160gsm = 8
    HPGlossy220gsm = 9
    Light = 10
    Intermediate = 11
    MidWeight = 12
    Heavy = 13
    ExtraHeavy = 14
    Cardstock = 15
    MidWeightGlossy = 16
    HeavyGlossy = 17
    CardstockGlossy = 18
    Transparency = 19
    Labels = 20
    StationeryLetterhead = 21
    Envelope = 22
    HeavyEnvelope = 23
    StationeryPreprinted = 24
    StationeryPrepunched = 25
    Color = 26
    Bond = 27
    Recycled = 28
    Rough = 29
    FilmOpaque = 30
    HPEcoSmartLite = 31
    LightBond = 32
    HeavyRough = 33
    AnySupportedType = 34
    UserType1 = 35
    UserType2 = 36
    UserType3 = 37
    UserType4 = 38
    UserType5 = 39
    UserType6 = 40
    UserType7 = 41
    UserType8 = 42
    UserType9 = 43
    UserType10 = 44
    Other = 45
    NO_TYPE_ASSOCIATION = 46
    HeavyPaperboard = 47
    HPToughPaper = 48
    ExtraHeavyGloss = 49
    HPEcofficient = 50
    HPGlossyEdgeline180G = 51
    HPMatteBrochureAndFlyer = 52
    HPPremiumPresentationMatte = 53
    ShelfEdgeLabels = 54
    Vellum = 55
    HPBrochureMatte = 56
    HPBrochureGlossy = 57
    HPAdvancedPhoto = 58
    LightPaperboard = 59
    Paperboard = 60
    LightRough = 61
    MattePhotoDuplex = 62
    MattePresentation = 63
    MatteInkjet = 64
    PhotographicGlossy = 65
    PhotographicInkjet = 66
    SpecialityGlossy = 67
    SpecialityGlossyInkjet = 68
    SpecialityHagaki = 69
    HPTriFoldBrochureGlossy = 70
    HPEverydayPhoto = 71
    HPPremiumPlusPhoto = 72
    StationeryFine = 73
    TabStock = 74  
    Matte = 3
    MatteCover = 3
    MatteBrochure = 3
    Custom = 75
    Coated = 76

class Consumables(Enum):
    BlackCartridge = 0
    CyanCartridge = 1
    MagentaCartridge = 2
    YellowCartridge = 3
    BlackToner = 4
    CyanToner  = 5
    MagentaToner = 6
    YellowToner = 7
    BlackDrum = 8
    CyanDrum = 9
    MagentaDrum = 10
    YellowDrum = 11
    BlackDeveloper = 12
    CyanDeveloper = 13
    MagentaDeveloper = 14
    YellowDeveloper = 15
    Fuser = 16
    ImageTransferBelt = 17
    TonerCollector = 18
    ImageTransferBeltCleaner = 19
    TransferRoller = 20
    Tray1PickupRoller = 21
    Tray1FeedRoller = 22
    Tray1SeparationRoller = 23
    Tray2PickupRoller = 24
    Tray2FeedRoller = 25
    Tray2SeparationRoller = 26
    Tray3PickupRoller = 27
    Tray3FeedRoller = 28
    Tray3SeparationRoller = 29

class ConsumableThreshold(Enum):
    Low = 1
    EngineLow = 2
    Out = 3

class ConsumableLevel(Enum):
    Empty = 0 #0%
    Low = 1
    Full = 2 #100%
    EngineLow = 3
    Out = 4
    ExtendedLow = 5
    ExtendedOut = 6
    VeryLow = 7


class ConsumableState(Enum):
    MissingSupply = 0
    MemoryMissing = 1
    MemoryError = 2
    WrongSlot = 3
    UsedMovedBlocking = 4
    UsedMovedOverride = 5
    NonHP = 6
    NonHPOverride = 7
    GenuineHP = 8
    GenuineHPOverride = 9
    IncompatibleSKU = 10
    CartridgeLow = 11
    CartridgeOutPrompt = 12
    CartridgeOutReplace = 13
    CartridgeOutOverride = 14
    CartridgeOutMPACCO = 15
    ShippingLock = 16
    Protected = 17
    CartridgeVeryLow = 18
    UnauthorizedSupply = 19
    MissingMICRSupply = 20
    ReplaceMICRSupply = 21
    IncompatibleZone = 22
    Normal = 23
    DynSecError=24
    Unknown = 25

class ConsumableFeatures(Enum):
    SignatureBrandCoherence = 0
    LifeRisePrevention = 1
    PrinterFunctionalData = 2
    InvalidRegionCheck = 3
    IncompatibleSkuCheck = 4
    TheftDetection = 5
    GraylistCheck = 6
    UnauthorizedDetection = 7
    RefillDetection = 8
    InstalledBelowThresholdDetection = 9
    InstalledInWrongSlot = 10
    Missing= 11
    PercentLifeRemaining =12    
    SupplyLevel = 13 
    EstimatedPagesRemaining =14
    PagesPrintedWithThisSupply = 15
    BrandAuthenticity = 16

class CartridgeStatus(Enum):
    Missing = 0
    Installed = 1
    Defective = 2
    Normal = 3

class SizeUnits(Enum):
    Millimeters = 0
    Inches = 1

class InstallType(Enum):
    Fixed = 0
    Optional = 1
    OnTheFly = 2

class MediaInputIds(Enum):
    MultipurposeTray = 0
    Tray1 = 1
    Tray2 = 2
    Tray3 = 3
    Tray4 = 4
    Tray5 = 5
    Tray6 = 6
    Tray7 = 7
    Tray8 = 8
    Tray9 = 9
    Tray10 = 10
    Duplexer = 11
    Roll1 = 12
    Roll2 = 13
    Roll3 = 14
    Roll4 = 15
    EnvelopeFeed = 16
    ExternalTray1 = 17
    ExternalTray2 = 18
    ExternalTray3 = 19
    ExternalTray4 = 20
    ExternalTray5 = 21
    ExternalTray6 = 22
    ExternalTray7 = 23
    ExternalTray8 = 24
    ExternalTray9 = 25
    ExternalTray10 = 26
    MainRoll = 27
    Main = 28
    Top = 29

class MediaInputClass(Enum):
    MultipurposeFeed = 1 #Multi-purpose feed tray
    CassetteTray = 2 #A fixed cassette tray
    CassetteTray2 = 3 #A secondary fixed cassette tray
    HCI = 4 #High Capacity Input
    DuplexTray = 5
    EnvFeeder = 6 #Envelope Feeder
    CustomMediaCassette = 7
    NonStackable1x500 = 8  #An optional single non-stackable 500/550 sheet tray
    NonStackable1x1500 = 9 #An optional Generic HCI tray
    NonStackable1x1500_2 = 10 #An optional Generic HCI tray
    NonStackable3x500 = 11 #An optional triple non-stackable 550 sheet tray
    NonStackable_1500_2500 = 12
    Stackable1x500 = 13 #An optional single stackable 500/550 sheet tray
    Stackable1x250 = 14
    ExternalFeedClass = 15
    UnknownFeedClass = 16
    NonStackable_1500_2000_1500 = 17
    NonStackable_1500_2000_2000 = 18
    NonStackable_2x500_1500_500 = 19
    NonStackable_2x500_1500_1500 = 20
    EnvelopeCassette = 21
    NonStackable_550_Over_2000_550 = 22
    NonStackable_550_Over_2000_2000 = 23
    EnvelopeOPF = 24
    NonStackable_C1_Over_C2_C1 = 25 #An optional two cassettes, one over the other, the top cassette
    NonStackable_C1_Over_C2_C2 = 26 #An optional two cassettes, one over the other, the bottom cassette
    Stackable_C1 = 27
    NonStackable_C1_SideBySide_C2_C1 = 28 #An optional two cassettes, side by side, the left cassette
    NonStackable_C1_SideBySide_C2_C2 = 29 #An optional two cassettes, side by side, the right cassette
    NonStackable_C1_SideFeed = 30 #An optional side feed HCI
    NonStackable_C1_Over_C2_Over_C3_C1 = 31
    NonStackable_C1_Over_C2_Over_C3_C2 = 32
    NonStackable_C1_Over_C2_Over_C3_C3 = 33
    NonStackable_C1 = 34
    Stackable_C1_SideBySide_C2_C1 = 35 #An optional two cassettes, side by side, the left cassette
    Stackable_C1_SideBySide_C2_C2 = 36 #An optional two cassettes, side by side, the right cassette
    NoTrayClass = 1000

class MediaInputAreaErrorLocations(Enum):
    MediaGuidePlate = 0
    ProcessDirectionMediaLocation = 1
    ScanDirectionMediaLocation = 2
    MediaOverload = 3
    LifterError = 4
    PickupRoller = 5

class MediaOutputIds(Enum):
    StandardBin = 0
    OutputBin1 = 1
    OutputBin2 = 2
    OutputBin3 = 3
    OutputBin4 = 4
    OutputBin5 = 5
    OutputBin6 = 6
    OutputBin7 = 7
    OutputBin8 = 8
    OutputBin9 = 9
    OutputBin10 = 10
    EngineOptionalBin1 = 11
    AutoSelect = 12
    FaceDown = 13
    FaceUp = 14
    Side = 15
    Booklet = 16
    Other = 17
    StandardTop = 18
    Stapler = 19
    Undefined = 20

class FuserErrors(Enum):
    HeatUp = 1
    HighTemp1 = 2
    HighTemp2 = 3
    LowTemp1 = 4
    LowTemp2 = 5
    PowerCircuit = 6
    PressureRelease = 7

class MemoryChipField(Enum):
    MemoryChipModelNumber = 1
    MemoryChipCartridgeLife = 2

class JamTypes(Enum):
    Causal = 1
    Residual = 2
    AutoNav = 3
    
class JamCauses(Enum):
    Nothing = 0
    DelayInput = 1
    StayInput = 2
    DelayFuser = 3
    StayFuser = 4
    DelayOutput = 5
    StayOutput = 6
    DelaySwitchback = 7
    StaySwitchback = 8
    DelayDelivery = 9
    StayDelivery = 10
    DelayReInput = 11
    Wrap = 12
    Multifeed = 13
    ResidualMedia = 14
    DoorOpen = 15
    InappropriateDeliveryPath = 16
    TransferAreaWrap = 17
    TrayPick = 18
    SheetPick = 19
    DuplexPick = 20
    SheetEject = 21

class JamAreas(Enum):
    Unknown = 0
    TurnPath = 1
    DeSkew = 2
    VerticalPath = 3
    TunnelPath = 4
    Duplex = 5
    Eject = 6
    Door = 7
    Output = 8
    PrintZone = 9
    Tray1 = 10
    Tray2 = 11
    Tray3 = 12
    Tray4 = 13
    Tray5 = 14
    InputZone = 15
    MultipleTrayTop = 16
    MultipleTrayMiddle = 17
    MultipleTrayBottom = 18
    SideBySideLeft = 19
    SideBySideRight = 20
    FinisherInput = 21
    FinisherStack = 22
    Unreachable = 23
    PickUpTray1 = 24
    PickUpTray2 = 25
    PickUpTray3 = 26
    PickUpTray4 = 27
    PickUpTray4Dual = 28
    PickUpTray5 = 29
    PickUpTray5Dual = 30
    PickUpTray6 = 31
    FeedInTray3 = 32
    FeedInTray4 = 33
    FeedInTray4Dual = 34
    FeedInTray5Dual1 = 35
    FeedInTray5Dual2 = 36
    FeedInTray5Dual3 = 37
    FeedOutTray1 = 38
    FeedOutTray2 = 39
    FeedOutTray3 = 40
    FeedOutTray4 = 41
    FeedOutTray4Dual = 42
    FeedOutTray5 = 43
    FeedOutTray5Dual = 44
    FeedOutTray6 = 45
    RegInTray1 = 46
    RegInTray2 = 47
    RegInTray3 = 48
    RegInTray4 = 49
    RegInTray4Dual = 50
    RegInTray5 = 51
    RegInTray5Dual = 52
    RegIntTray6 = 53
    RegOut = 54
    FuserIn = 55
    FuserOutIn = 56
    FuserOutOut = 57
    BinFullIn = 58
    Exit2In = 59
    Exit2Out = 60
    Duplex1In = 61
    Duplex1Out = 62
    Duplex2In = 63
    Duplex2Out = 64
    DuplexRegIn = 65
    DuplexRegOut = 66
    IdleFeed1 = 67
    IdleFeed2 = 68
    IdleFeed3 = 69
    IdleFeed4 = 70
    IdleReg = 71
    IdleFuserOut = 72
    IdleFuserIn = 73
    IdleExit2 = 74
    IdleDuplex1 = 75
    IdleDuplex2 = 76
    InnerEntranceInFinisher = 77
    InnerEntranceOutFinisher = 78
    InnerIdleEntranceFinisher = 79
    InnerExitInFinisher = 80
    InnerExitOutFinisher = 81
    InnerIdleExitFinisher = 82
    EntranceInFinisher = 83
    EntranceOutFinisher = 84
    IdleEntranceFinisher = 85
    MainExitInFinisher = 86
    MainExitOutFinisher = 87
    IdleMainExitFinisher = 88
    MainExitOutBufferingFinisher = 89
    TopExitInFinisher = 90
    TopExitOutFinisher = 91
    IdleTopExitFinisher = 92
    BufferExitInBufferingFinisher = 93
    BufferExitInFinisher = 94
    BufferExitOutFinisher = 95
    IdleBufferExitFinisher = 96
    EntranceInBridge = 97
    EntranceOutBridge = 98
    IdleEntranceBridge = 99
    IdlePaperBridge = 100
    EntranceInBooklet = 101
    EntranceOutBooklet = 102
    IdleEntranceBooklet = 103
    CompileInBooklet = 104
    IdleCompileBooklet = 105
    FoldExitInBooklet = 106
    FoldExitOutBooklet = 107
    IdleFoldExitBooklet = 108
    FuserWrapJam = 109
    BridgeCommunicationFailure = 110
    MediaInputDelayTray1 = 111
    MediaInputDelayTray2 = 112
    MediaInputDelayTray3 = 113
    MediaInputDelayTray3WithHiCap = 114
    MediaInputDelayTray4 = 115
    MediaInputDelayTray4WithHiCap = 116
    MediaInputDelayTray5 = 117
    MediaJamTurnRoller = 118
    MediaJamFinisherBin = 119
    RightDoorOpenJam = 120
    LeftDoorOpenJam = 121
    LowerRightDoorOpenJam = 122
    MotoStallTray1 = 123
    MotoStallTray2 = 124
    MotoStallTray3 = 125
    MotoStallTray3WithHiCap = 126
    MotoStallTray4 = 127
    MotoStallTray4WithHiCap = 128
    MotoStallTray5 = 129
    MotoStallDuplexExit = 130
    MotoStallDuplexEntry = 131
    MotoStallFinisher = 132
    Tray6 = 133
    RegistrationDrum = 134
    DrumFuser = 135
    FuserOutput = 136
    Output1 = 137
    Output2 = 138
    DuplexReversing = 139
    DuplexFeeding = 140
    DuplexPickUp = 141

class Calibrations(Enum):
    # canon calibration types
    CPR = 0
    Dhalf = 1
    DmaxDhalf = 2
    ConsecutiveCPRDmaxDhalf = 3
    PWM = 4

    # Bratwrust calibration types
    FullAutoColorRegistration = 5
    AutoColorRegistration = 6
    FullAutoTone = 7
    TCCalibration = 8
    AddMix = 9
    CoolingDown = 10
    ITBBand = 11
    OPCBand = 12
    TonerDrain = 13
    HighCoverageMixing = 14
    Shading1Flatbed = 15
    Shading3ADF = 16
    SettingStandardTone = 17
    EPCalibrationPattern1Contone = 18
    LowTemperatureIdling = 19
    InvalidateFullAutoTone = 20
    NormalAutoTone = 21
    CTDSensorCalibration = 22

class CalibrationRequestType(Enum):
    PowerOn = 0
    Time = 1
    Environmental = 2
    PageCount = 3
    FirstReplacementPart = 4
    YellowCartReplaced = 5
    MagentaCartReplaced = 6
    CyanCartReplaced = 7
    BlackCartReplaced = 8
    ValueChange1 = 9
    ValueChange2 = 10
    ReplacementCartridge = 11

class CalibrationResults(Enum):
    Normal = 0
    YellowOutOfRange = 1
    MagentaOutOfRange = 2
    CyanOutOfRange = 3
    BlackOutOfRange = 4

class CartridgeLocationValues(Enum):
    LocatinValOfYellow = 0
    LocationValOfMagenta = 1
    LocationValOfCyan = 2
    LocationValOfBlack = 3

class CartridgeColorcodes(Enum):
    Yellow = 0
    Magenta = 1
    Cyan = 2
    Black = 3

class SupplyFeatureSet(Enum):
    cartridgefeatureset = 0

class FinisherDeviceNames(Enum):
    Aluminum = 0
    Aluminum_HP_EU = 1
    Aluminum_HP_SW = 2
    Aluminum_HP_US = 3
    Copper = 4
    Copper_HP_EU = 5
    Copper_HP_SW = 6
    Copper_HP_US = 7
    Iron = 8
    Iron_HP_EU = 9
    Iron_HP_SW = 10
    Iron_HP_US = 11

class StapleTypes(Enum):
    none = 0
    Default = 1
    LEFT_1PT = 2
    ONE_STAPLE = 3
    LEFT_1PT_ANGLED = 4
    LEFT_1PT_HORIZ = 5
    LEFT_1PT_VERT = 6
    RIGHT_1PT = 7
    RIGHT_1PT_ANGLED = 8
    RIGHT_1PT_HORIZ = 9
    RIGHT_1PT_VERT = 10
    BOTTOM_LEFT_1PT = 11
    BOTTOM_LEFT_1PT_ANG = 12
    BOTTOM_LEFT_1PT_HOR = 13
    BOTTOM_LEFT_1PT_VERT = 14
    BOTTOM_RIGHT_1PT = 15
    BOTTOM_RIGHT_1PT_ANG = 16
    BOTTOM_RIGHT_1PT_HOR = 17
    BOTTOM_RIGHT_1PT_VERT = 18
    CENTER_1PT = 19
    LEFT_2PT = 20
    TWO_STAPLES = 21
    RIGHT_2PT = 22
    TOP_2PT = 23
    BOTTOM_2PT = 24
    CENTER_2PT = 25
    LEFT_3PT = 26
    THREE_STAPLES = 27
    RIGHT_3PT = 28
    TOP_3PT = 29
    BOTTOM_3PT = 30
    CENTER_3PT = 31
    LEFT_6PT = 32
    SIX_STAPLES = 33
    RIGHT_6PT = 34
    TOP_6PT = 35
    BOTTOM_6PT = 36
    CENTER_6PT = 37
    CUSTOM = 38
    CUSTOM_01 = 39
    CUSTOM_02 = 40
    CUSTOM_03 = 41
    CUSTOM_04 = 42
    CUSTOM_05 = 43
    CUSTOM_06 = 44
    CUSTOM_07 = 45
    CUSTOM_08 = 46
    CUSTOM_09 = 47
    CUSTOM_10 = 48
    OPTION3 = 49
    OPTION4 = 50
    OPTION5 = 51
    OPTION6 = 52

class PunchTypes(Enum):
    none = 0
    Default = 1
    ANY_2PT = 2
    LEFT_2PT_DIN = 3
    RIGHT_2PT_DIN = 4
    TOP_2PT_DIN = 5
    BOTTOM_2PT_DIN = 6
    _2PT_DIN = 7
    LEFT_2PT_US = 8
    RIGHT_2PT_US = 9
    TOP_2PT_US = 10
    BOTTOM_2PT_US = 11
    _2PT_US = 12
    LEFT_3PT_US = 13
    RIGHT_3PT_US = 14
    TOP_3PT_US = 15
    BOTTOM_3PT_US = 16
    _3PT_US = 17
    ANY_3PT = 18
    LEFT_4PT_DIN = 19
    RIGHT_4PT_DIN = 20
    TOP_4PT_DIN = 21
    BOTTOM_4PT_DIN = 22
    _4PT_DIN = 23
    LEFT_4PT_SWD = 24
    RIGHT_4PT_SWD = 25
    TOP_4PT_SWD = 26
    BOTTOM_4PT_SWD = 27
    _4PT_SWD = 28
    ANY_4PT = 29
    LEFT_2PT = 30
    RIGHT_2PT = 31
    TOP_2PT = 32
    BOTTOM_2PT = 33
    OTHER = 34

class CalibrationGroups(Enum):
    FULL_CALIBRATION = 0
    QUICK_CALIBRATION = 1
    HALFTONE_CALIBRATION_SET = 2
