from dunetuf.ui.uioperations.WorkflowOperations.SubstrateLibraryAppWorkflowUICommonOperations import SubstrateLibraryAppWorkflowUICommonOperations

class SubstrateLibraryAppWorkflowUILOperations(SubstrateLibraryAppWorkflowUICommonOperations):
    pass