@startuml

hide unlinked
skinparam lifelineStrategy solid

actor "User" as User
participant "CopyJobTicket" as CJT
participant "CopyPipelineBuilder" as Pipe
participant "JobServiceStandard" as JSS
participant "ScanDevice" as Device
participant "ImageProviderCws" as ImageCws

title Scanner Clipping - Copy Data Path
User -> JSS : Inserts Page
JSS -> JSS :  Read maxSupportedSizes from\nCopy::JobServiceStandard.fbs (scanMaxCm)\ninto maxLengthConfig_
JSS -> Pipe : Send maxLengthConfig_ to the PipelineBuilder

Pipe -> Pipe : setupScanRegion
note over Pipe #yellowgreen: scanDeviceIntent::YExtent is asigned here
Pipe -> Device : doWork(ScanDeviceIntent)
Device -> Device : convertFormatterToScannerTicket
note over Device #yellowgreen: **Both YExtent and YScanSizeSide**\n**are expressed in mm**
Device -> ImageCws : scanProvider_->startScan( ScanTicketStruct )
group Second page
User -> CJT : Inserts Page ( somehow )
CJT -> CJT : addPage()
CJT -> CJT : createIntents(CopyPageTicket)
CJT -> CJT : createScanPageIntent
CJT -> ImageCws : sendPageTicket
note over ImageCws #yellowgreen
It is ImageProviderBase who
replaces the old ScanStructTicket
with the new one
end note
end group

@enduml