@startuml Copy job accounting

loop for 1 to N pages
    -> ImageProviderBase : addNewScanPage
    ImageProviderBase -> JobTicketHandler : addPage()
    create PageTicketHandler
    JobTicketHandler -> PageTicketHandler : new()
    -> ImageProviderBase : endImageContainer
    ImageProviderBase -> ImageProviderBase : update scanPageInfo_
    ImageProviderBase -> ImageProviderBase : populatePageTicketResultsWithScanInfo()
    ImageProviderBase -> PageTicketHandler : updateScanJobInfo(scanPageinfoPtr)
    PageTicketHandler --> ImageProviderBase
end

-> JobStatsStoreStandard : jobCompleted
JobStatsStoreStandard -> CopyJobDetailsProvider : populateJobDetails(jobTicketId)
CopyJobDetailsProvider -> CopyJobDetailsProvider : generateJobDetails(jobTicket)
CopyJobDetailsProvider -> ScanPipelineStandard : populateScanInfo(jobTicketHandler, scanJobIntent)

loop for each pageId
    ScanPipelineStandard -> JobTicketHandler : getPageTicketHandler(pageId)
    ScanPipelineStandard -> PageTicketHandler : get Width and Height
    rnote over of ScanPipelineStandard
        Transform Width (px) and Height (px) into Area (sqcm) and Length (mm)
        and set it to a ScanInfo table
    end note
end
ScanPipelineStandard --> CopyJobDetailsProvider : cdm::jobManagement_1::ScanInfo*
CopyJobDetailsProvider --> JobStatsStoreStandard : cdm::jobManagement_1::StatsTable

JobStatsStoreStandard -> JobStatsStoreStandard : updateScanInfo(jobId, scanInfoTable)

@enduml