@startuml



-> CopyJobPromptController : evalPrompts()

note left
    inputMediaSizeId and outputMediaSizeId are determined at this point
end note

alt scaleFitToPageEnabled == true && scaleSelection == "fitToPage"

CopyJobPromptController -> MediaMetics : convertMediaSizeIdToWidthAndHeight(copyIntent_->getInputMediaSizeId(), orientation);
MediaMetics -> CopyJobPromptController : inputWidth, inputHeight

CopyJobPromptController -> MediaMetics : convertMediaSizeIdToWidthAndHeight(copyIntent_->getOutputMediaSizeId(), orientation);
MediaMetics -> CopyJobPromptController : outputWidth, outputHeight

CopyJobPromptController -> CopyJobPromptController : scalePercent = calculateFitToPageScalePercent(inputWidth, outputWidth)
note right
    scalePercent is calculated based on the input and output widths.
    scalePercent = (outputWidth / inputWidth) * 100
end note
alt fitToPageIncludeMargin == true
    CopyJobPromptController -> CopyJobPromptController : scalePercent = scalePercent * (97/100)
    note right
        When IncludeMargins is enabled, scale percent becomes 97% of the original.
    end note
end

CopyJobPromptController -> CopyJobIntent : setXScalePercent(scalePercent)
CopyJobPromptController -> CopyJobIntent : setYScalePercent(scalePercent)

end

@enduml