@startuml
title <size:20><b>CopyJobTicket Class Diagram</b></size>

interface IJobTicket
{
}

Interface ICopyJobTicket
{
    virtual ICopyJobIntent getIntent()
    virtual void setIntent(ICopyJobIntent)
}

class CopyJobTicket
{
    jobIntent:CopyJobIntent
}

interface ICopyJobIntent
{

}

class CopyJobIntent
{

}

IJobTicket <|-- ICopyJobTicket
ICopyJobTicket <|-- CopyJobTicket
ICopyJobIntent<|-- CopyJobIntent
CopyJobTicket o-- CopyJobIntent

@enduml