@startuml
note top
    condition: Stage::Scan_Basic_Print
end note

partition "onBuildPipeline" {

(*) --> setupScanDevice
    --> setupImageProcessorTicket
    --> setupPrintDevice
    note top
            setCollationCopies() / setUnCollationCopies() are called inside
    end note
    --> === SDB_END ====
}

=== SDB_END === --> (*)
@enduml