@startuml
note top
    Condition: SegmentType::PrepareSegment && Product::LFP
end note

partition "onBuildPipeline" {

(*) --> setupScanDevice
    --> setupBufferingImagePersister
    --> setupBufferingImageRetriever
    --> setupImagePersisterPreview           
}

--> (*)
@enduml