@startuml
note top
    Condition: Stage::Scan_PageAssembler_Print
end note

partition "onBuildPipeline" {

(*) --> setupScanDevice
    --> if " " then
    note top
        (CollateMode::COMPRESSED || ! CopyOutputNumberUpCount::OneUp) && ! Product::LFP
    end note
        --> [true] setupImagePersister
        --> setupImageRetriever
        note top
            setCollationCopies() / setUnCollationCopies() are called inside
        end note
        --> === SDB_END1 ====
        else
        --> [false] === SDB_END1 ====
        === SDB_END1 ==== --> if " " then
                            note top
                                ! Product::LFP
                            end note
                                --> [true] setupImageProcessorTicket
                                --> === SDB_END2 ====
                                else
                                --> [false] === SDB_END2 ====
        === SDB_END2 ==== --> if " " then
                                note top
                                    ScanDiskBuffering
                                end note
                                --> [true] setupBufferingImagePersister
                                --> setupBufferingImageRetriever
                                --> === SDB_END3 ====
                                else
                                --> [false] === SDB_END3 ====
        === SDB_END3 ==== --> if " " then
                                note top
                                    ! Product::LFP
                                end note
                                --> [true] setupMarkingFilter
                                --> setupPageAssembler
                                note top
                                    setCollatedCopies() / setUnCollatedCopies are called inside
                                end note
                                --> === SDB_END4 ====
                                else
                                --> [false] === SDB_END4 ====
        === SDB_END4 ==== --> if " " then
                                note top
                                    Product::LFP
                                end note
                                --> [true] setupImageProcessorTicket2
                                --> setupImagePersister2
                                --> setupImageRetriever2
                                note top
                                    setCollationCopies() / setUnCollationCopies() are called inside
                                end note
                                --> === SDB_END5 ====
                                else
                                --> [false] === SDB_END5 ====
        === SDB_END5 ==== --> setupRtpFilterTicket
        --> setupPrintDevice
        note top
            setCollationCopies() / setUnCollationCopies() are called inside
        end note
        --> === SDB_END ====                                                                       
}

=== SDB_END ==== --> (*)
@enduml