@startuml
note top
    Condition: Stage::ScanFirstPage
end note

partition "onBuildPipeline" {

(*) --> if " " then
note top
    ! CopyOutputNumberUpCount::OneUp
end note
        --> [true] setupScanDevice 
        --> setupImagePersister 
        --> === SDB_END ====
        else
        --> [false] setupScanDevice2
        --> setupImageProcessorTicket
        --> setupPageAssembler
        note top
            setCollatedCopies() / setUnCollatedCopies are called inside
        end note
        --> setupImagePersister2
        --> === SDB_END ====
}

=== SDB_END ==== --> (*)
@enduml