@startuml
note top
    Condition: Stage::PrintAllPages
end note

partition "onBuildPipeline" {

(*) --> if " " then
note top
    ! CopyOutputNumberUpCount::OneUp
end note
        --> [true] setupImageRetriever
        note top
        setCollationCopies() / setUnCollationCopies() are called inside
        end note
        --> setupImageProcessorTicket
        --> setupMarkingFilter
        --> setupPageAssembler
        note top
            setCollatedCopies() / setUnCollatedCopies are called inside
        end note
        --> === SDB_END1 ====
        else
        --> [false] setupImageRetriever2
            note top
                setCollationCopies() / setUnCollationCopies() are called inside
            end note
            --> if " " then
            note left
                ScanCaptureModeType::IDCARD
            end note
                    --> [true] setupMarkingFilter2
                    --> === SDB_END1 ====
                else
                --> [false] === SDB_END1 ====
        === SDB_END1 ==== --> setupRtpFilterTicket
        --> setupPrintDevice
        note left
            setCollationCopies() / setUnCollationCopies() are called inside
        end note
        --> === SDB_END ====                                                           
}

=== SDB_END === --> (*)
@enduml