@startuml
note top
    Condition: ScanCaptureModeType::JOBBUILD && SegmentType::FinalSegment
end note

partition "onBuildPipeline"{

(*) --> setupBufferingImageRetriever
    --> setupImageProcessorTicket
    --> setupImagePersister
    --> setupImageRetriever
    note top
        setCollationCopies() / setUnCollationCopies() are called inside
    end note
    --> setupPrintDevice
    note top
        setCollationCopies() / setUnCollationCopies() are called inside
    end note
}

--> (*)
@enduml