class ContactsAppWorkflowObjectIds:
    # -------------------------------Function Keywords------------------------ #
   # contacts_menu = "#contactsSettingsButton"
    button_home = "#HomeButton"
    button_back = "#BackButton"
    menu_button_contacts = "#2b328d57-7fff-401c-9665-315ada3010f0MenuApp"

    back_button_contacts_landing_view = "#globalHeaderHeaderView #BreadcrumbView #BackButton"

    # New
    view_contacts = "#ContactsAppLandingView"
    button_add_contact = "#addContactObject"
    button_add_group = "#addGroupObject"
    button_more_option = "#moreItem"
    button_address_book = "#customSection #customSectionOptions #addressbookButton"
    enter_name_frame = "#displayNameFieldRow"
    enter_name_frame = "#displayNameFieldRow"
    enter_gname_frame ="#groupNameButtonRow"
    contact_name_inputtextbox = "#TextInputBox"
    contact_name_inputtextarea = "#TextAreaBox"
    # Add Contacts
    header_add_contact = "#addContactHeader"
    footer_add_contact = "#addContactFooter"
    view_add_contacts = "#addContact"  # Need to be replaced later
    button_add_contacts_cancel = "#cancelButton"
    button_add_contacts_save = "#saveContactButton"
    button_display_button = "#displayNameFieldModel"
    button_first_name = "#firstNameFieldModel"
    button_last_name = "#lastNameFieldModel"
    button_keyboard_ok = "#enterKey1"
    button_number_keyboard_ok = "#keyOk"
    textbox_group_name = "#groupNameButtonModel"
    textbox_group_notes = "#groupNotesTextFieldRowModel"
    hide_keyboard_key = "#hideKeyboardKey"
    button_pause_key = "#pause"
    # button1_group_button = "#groupNameButtonModel"
    # button_edit_contacts_save = "#saveContactButton"

    helper_message_text_view = "#HelperText"

    row_display_name = "#displayNameField"
    row_first_name = "#firstNameField"
    row_last_name = "#lastNameField"
    row_email = "#emailAddressFieldRow"
    row_fax = "#faxNumberFieldRow"
    row_notes = "#notesFieldRow"
    row_object_network_folder_path="#networkFolderComboBoxRow"
    row_object_unc_folder_path="#uncFolderPathFieldRow"
    row_object_windows_domain="#windowsDomainFieldRow"
    row_object_username="#userNameFieldRow"
    row_object_password="#passwordFieldRow"
    row_object_verify_access = "#verifyAccessCheckBoxRow"
    

    textbox_display_name = "#displayNameFieldModel"
    textbox_first_name = "#firstNameFieldModel"
    textbox_last_name = "#lastNameFieldModel"
    textbox_email = "#emailAddressFieldModel"
    textbox_fax = "#faxNumberFieldModel"
    textbox_notes = "#notesFieldModel"
    textbox_username= "#userNameFieldModel"
    textbox_password = "#passwordFieldModel"
    textbox_uncFolder_path = "#uncFolderPathFieldModel"
    textbox_descriptionText = "#descriptionText"
    textbox_windows_domain = "#windowsDomainFieldModel"
    checkbox_verify_access = "#verifyAccessCheckBoxModel"
    view_object_network_folder_path = "#networkFolderComboBoxViewModel"
    settings_network_folder_option_none = "#ComboBoxOptionsnone"
    settings_network_folder_option_standard = "#ComboBoxOptionsnetworkFolderStandard"


    combobox_network_folder_path = "#SettingsSpiceComboBox"
    view_contacts_networkFolderType = "#SettingsSpiceComboBoxpopup"
    add_contact_list= "#addContactListView"
    add_contact_list_scrollbar = "#addContactListViewScrollBar"
    scrollbar_combobox = "#comboBoxScrollBar"
    constraint_modal = "#ConstraintMessage"
    constraint_modal_ok_button = "#okButton"
    ok_button_model = "#okButtonModel"


    # Add Group
    view_add_group = "#addGroupListView"
    row_add_group = "#groupNameButtonRow"
    row_add_group_notes = "#groupNotesTextFieldRow"
    view_add_group_member = "#addMembersListViewlist1"
    scroll_bar_add_group_member = "#addMembersListViewlist1ScrollBar"
    view_add_group_member_view = "#addMembersContactsView"
    view_edit_group_list_view = "#editGroupListView"
    add_group_scrollbar = "#addGroupListViewScrollBar"
    # textbox_group_name= "#
    # addButton

    button_add_member = "#groupMembersButtonRow"
    button_group_cancel = "#groupCancelButton"
    button_group_save = "#groupSaveButton"
    button_add_group_member_done = "#doneButton"
    button_add_group_member_add = "#addButton"
    button_add_group_member_cancel = "#cancelButton"

    # Edit contacts
    header_edit_contact = "#editContactHeader"
    footer_edit_contact = "#editContactFooter"
    view_edit_contacts = "#editContactView"  # Need to be replaced later
    view_edit_contacts_list_view = "#editContactListView"
    view_edit_contact_list_scrollbar = "#editContactListViewScrollBar"
    button_edit_contacts = "#editContact"
    button_delete_contacts = "#deleteContactButton"
    enter_edit_frame = "#headerList2Obj"
    edit_name_text = "#ContentItem"

    # Delete Contacts confirmation popup
    button_contacts_delete_confirmation_delete = "#deleteContactButtonModel"
    button_contacts_delete_confirmation_cancel = "#deleteCancelButtonModel"
    button_contacts_delete_confirmation_cancel_for_Beam_MFP = "#deleteCancelButton"
    text_contacts_delete_confirmation_popup = "#LayoutHorizontalIconsGrid"

    # Edit Group
    view_edit_group = "#editGroupView"  # Need to be replaced later
    view_edit_group_members = "#editMembersContactsView"
    list_view_edit_group_member = "#editGrpMemListViewlist1"
    scroll_bar_edit_group_member = "#editGrpMemListViewlist1ScrollBar"
    button_edit_group = "#editContact"
    button_delete_group = "#groupDeleteButton"
    button_group_edit_add = "#addButton"
    button_group_edit_remove = "#removeButton"
    button_group_edit_remove_confirm = "#removeGroupButton"
    button_group_edit_remove_cancel = "#cancelButton"
    button_group_edit_removeall = "#removeAllButton"
    button_group_edit_removeall_confirm = "#removeAllGroupButton"
    button_group_edit_cancel = "#cancelButton"

    # Delete Group confirmation popup
    button_delete_group_confirmation_delete = "#deleteGroupButton"
    button_delete_group_confirmation_cancel = "#deleteCancelButton"

    scroll_bar_menu_contact = "#landingPageMenuAppListScrollBar"
    view_menu_landing_view = "#landingPageMenuAppList"
    scrollbar_combobox = "#comboBoxScrollBar"

    scroll_bar_contact_landing_view = "#ContactsAppLandingViewverticalLayoutScrollBar"
    scroll_bar_group_add_contacts_view = "#bodyLayoutverticalLayoutScrollBar"
    utilities_column_name = "#UtilitieslandingPageMenuAppListcolumn"
    landingPage_Content_Item = "#landingPageMenuAppListlistItem"
    section_bottom_border = "#UtilitiessectionBottomBorder"
    view_menuContacts = "#ContactsAppLandingViewverticalLayout"

    contacts_landing_view_list_scroll_bar = "#ContactsAppLandingViewlist1ScrollBar"
    contacts_landing_view_list = "#ContactsAppLandingViewlist1"
    contacts_details_view_list = "#ContactsAppLandingViewlist"
    row_email_address = "#emailRow"
    row_email_address_text = "#emailRow_2infoBlockRow"
    row_first_name = "#fnameRow"
    row_first_name_text = "#fnameRow_2infoBlockRow"
    row_last_name = "#lnameRow"
    row_last_name_field = "#lastNameFieldRow"
    row_last_name_text = "#lnameRow_2infoBlockRow"
    row_view_notes = "#notesRow"
    row_notes_text = "#notesRow_2infoBlockRow"
    row_fax_number = "#faxRow"
    row_fax_number_text = "#faxRow_2infoBlockRow"
    row_network_path = "#nFPathRow"
    row_network_path_text = "#nFPathRow_2infoBlockRow"
    row_members = "#membersRow"
    row_members_text = "#membersRow_2infoBlockRow"
    row_notes_contact = "#groupNotesRow"
    row_notes_contact_text = "#groupNotesRow_2infoBlockRow"

    verify_access_screeen_view = "#verifyingAccessFolder"
    constrain_description_view = "#constraintDescription"
    message_description_view = "#alertDetailDescription"
    ok_button_constrain_screen = "#FooterViewRight #okButton"
    text_view = "SpiceText[visible=true]"

    ok_button_keyboard = "#enterKey1"
    enter_password_view = "#enterPinField"
    password_edit = "#pinEditor"
    submit_button_locator = "#FooterViewRight #doneButton"
    cancel_button_locator = "#FooterViewRight #cancelButton"

    alert_description = "#alertDetailDescription"
    ok_button_alert_description = "#FooterViewRight #OkButton"
    ok_button_constraint_screen = "#noAccessOkButton"

    # search sort view
    view_search_model = "#searchModelView"
    text_field_search = "#searchRow #textField"
    button_search = "#searchRow #searchModalButton"
    button_cancel = "#searchRow #cancelButton"
    button_reset_search = "#resetButton"
    view_search_result_number_view = "#section1"
    button_search_landing_view = "#customSection #customSectionOptions #searchButton"
    button_sort = "#customSection #customSectionOptions #sortButton"
    view_text_sort_button = "#sortButton #ContentItemText"
    custom_section = "#customSection"
    custom_section_options = "#customSectionOptions"
    search_result_count = "#customSection #customSectionOptions #searchResult"
    text_view_empty_record = "#emptyRecordComponent SpiceText[visible=true]"
    text_view_search_contacts = "#ContactsAppLandingViewlist1 #infoBlockRow SpiceText[visible=true]"

    button_close_more_options_screen = "#HeaderViewRight #closeButton"

    footer_view = "#FooterView"
    header_view_addressbook_name = "#globalHeader"
    # ConstraintMessage
    constraint_string_msg = "#ConstraintMessage"
    alert_msg = "#alertMessage"
    ok_button = "#okButton"
