class JobAppWorkflowObjectIds:
    # -------------------------------Function Keywords------------------------ #
    job_view = "#jobDetailsverticalLayout"
    button_home = "#HomeButton"
    button_back = "#jobDetails #BackButton"
    job_header = "#jobAppHeader"

    job_list_view = "#jobQueueJobList"
    job_app_list_view = "#JobQueueAppApplicationStackView #jobQueueJobList"
    job_widget_list_view = "#jobQueueByStateWidget #jobQueueJobList"
    job_widget_scroll_bar = "#jobQueueJobListScrollBar"
    job_app_scroll_bar = "#JobQueueAppApplicationStackView #jobQueueJobListScrollBar"
    older_jobs_scroll_bar = "#oldJobsListScrollBar"
    job_id = "#JOB_{0}"
    job_ui = "#JobQueueAppApplicationStackView #JOB_{0} #mouseArea"
    older_job_ui = "#jobQueueJobHistoryJobListMain #JOB_{0}[visible=true]"
    job_widget_ui = "#widgetCardJobQueueApp #JOB_{0} #mouseArea"
    job_status_box = "#JobStatusBox"
    job_status_text = "#JobStatusBox #StatusText"
    job_remaining_time = "#JobQueueAppApplicationStackView #JobStatusBox #StatusExtraText"
    job_status_description_text = "#JobStatusBox #StatusDescriptionText"
    older_jobs_list = "#jobQueueJobHistoryJobListMain"
    job_app_in_progress_text = "#jobQueueJobList #inprogress SpiceText"
    job_app_up_next_text = "#jobQueueJobList #upnext SpiceText"
    job_app_history_text = "#jobQueueJobList #history SpiceText"
    job_notification_cancel = "#notificationRowButtons #jobNotificationCancel"

    pause_button = "#pauseButton SpiceText[visible=true]"
    cancel_button = "#cancelButton"
    cancel_confirmation_button = "#cancelJobYesButton"
    cancel_confirmation_unconcurrency_button = "#cancelJobButton"
    cancel_only_print_button = "#cancelPrintOnlyButton"
    cancel_yes_button = "#cancelJobServiceYesButton"
    cancel_both_button = "#cancelBothButton"
    cancel_curing_job = "#cancelCuringYesButton"
    cancel_curing_no_job = "#cancelCuringNoButton"
    cancel_printing_curing = "#cancelPrintingAndCuring"
    cancel_job_no_button = "#cancelJobNoButton"
    cancel_printing = "#cancelPrinting"
    release_button = "#releaseButton"
    reprint_button = "#reprintButton"
    reprint_button_text = "#reprintButton SpiceText[visible=true]"
    reprint_confirmation_button = "#reprintButtonJobReprintScreen"
    reprint_confirmation_button_text = "#reprintButtonJobReprintScreen SpiceText[visible=true]"
    reprint_spin = "#SpinCopiesJobReprintScreen"
    more_options_button = "#CCB_BUTTON_EXPANDER"
    print_anyway_button = "#Button_PrintAnyway"
    print_settings_screen = "#settingsOnTheFlyEditValuesScreen"
    print_settings_screen_title = "#settingsOnTheFlyEditValuesScreen SpiceText[visible=true]"
    checkbox_overwrite_action = "#overwriteModel"
    generic_substrate_not_overwritten_message = "#genericSubstrateNotOverwritten"
    more_options_button_when_canceling = "#dropDownButton"
    delete_button = "#deleteJobButton"
    delete_button_text = "#deleteJobButton SpiceText[visible=true]"
    delete_confirmation_button = "#deleteJobDeleteAnywayButton"
    delete_confirmation_button_text = "#deleteJobDeleteAnywayButton SpiceText[visible=true]"
    promote_button = "#promoteButton"
    promote_confirmation_button = "#promoteButtonConfirm"
    delete_all_jobs_button = "#deleteAllJobsButton"
    delete_all_jobs_confirmation_button = "#deleteAnywayButton"
    view_older_jobs_button = "#viewOlderJobsButton SpiceText[visible=true]"

    spinbox_button_up = "#upButtonContainer"
    spinbox_button_down = "#downButtonContainer"
    print_settings_scroll_bar = "#settingsOnTheFlyEditValuesScreenlist1ScrollBar"
    
    back_button = "#BackButton"

    curing_temperature_row = "#mediaModeCuringTemperatureRow"
    curing_temperature_model = "#mediaModeCuringTemperatureModelSettingDetailsScreen"
    curing_temperature_spinbox = "#mediaModeCuringTemperatureModelSpinBoxModel"
    curing_temperature_backButton = "#mediaModeSettingDetailsScreenHeader #mediaModeSettingDetailsScreenHeaderHeaderView #SpiceBreadcrumb #BreadcrumbView #BackButton"

    vacuum_row = "#mediaModeVacuumRow"
    vacuum_model = "#mediaModeVacuumModelSettingDetailsScreen"
    vacuum_spinbox = "#mediaModeVacuumModelSpinBoxModel"
    vacuum_backButton = "#mediaModeSettingDetailsScreenHeader #mediaModeSettingDetailsScreenHeaderHeaderView #SpiceBreadcrumb #BreadcrumbView #BackButton"

    critical_buttons_bar_panel = "#CBB_PANEL"
    critical_buttons_bar_expander = "#CBB_BUTTON_EXPANDER"
    critical_buttons_bar_cancel_button = "#CBB_BUTTON_0a1b2bbe-bd41-11eb-8529-0242ac130003"
    critical_buttons_bar_pause_button = "#CBB_BUTTON_0a1b2bbe-bd41-11eb-8529-0242ac130004"
    critical_buttons_bar_print_settings_button = "#CBB_BUTTON_03382722-3e5c-4815-87e6-6d19660869f9"
    critical_buttons_bar_warm_up_button = "#CBB_BUTTON_0a1b2bbe-bd41-11eb-8529-0242ac130005"
    critical_buttons_bar_move_and_cut_button = "#CBB_BUTTON_0a1b2bbe-bd41-11eb-8529-0242ac130008"
    critical_buttons_bar_turn_off_take_up_reel_button = "#CBB_BUTTON_0a1b2bbe-bd41-11eb-8529-0242ac130006"
    critical_buttons_bar_print_zone_lights_button = "#CBB_BUTTON_68959690-8f3a-40c6-9fae-ec1d1357f07a"

    job_substrate_type = "#DETAIL_SubstrateType #ValueText"
    job_media_type = "#DETAIL_MediaType #ValueText"
    job_media_source = "#DETAIL_mediaSource #ValueText"
    job_start_time = "#DETAIL_startTime #ValueText"
    job_completion_time = "#DETAIL_completionTime #ValueText"
    job_original_size = "#DETAIL_OriginalSize #ValueText"
    job_color_mode = "#DETAIL_colorMode #ValueText"
    job_copies = "#DETAIL_Copies #ValueText"
    job_output_size = "#DETAIL_OutputSize #ValueText"
    job_margins = "#DETAIL_PrintMargins #ValueText"
    job_destination = "#DETAIL_destination #ValueText"
    job_type = "#DETAIL_jobType #ValueText"
    job_total_pages = "#DETAIL_TotalPages #ValueText"
    job_user_name = "#DETAIL_userName #ValueText"
    job_quality = "#DETAIL_PrintQuality #ValueText"
    job_app = "#56ce9217-377d-4d5c-a950-a2ad37c07882"
    job_pages = "#DETAIL_Pages #ValueText"
    job_saved_pages = "#DETAIL_SavedPages #ValueText"
    job_completion_text = "#JobStatusBox #StatusDescriptionText"
    job_fax_destination = "#DETAIL_destination #ValueText"
    job_details_scanned_pages = "#DETAIL_ScannedPages #ValueText"
    job_original_sides = "#DETAIL_OriginalSides #ValueText"
    job_resolution = "#DETAIL_printResolution #ValueText"
    job_output_sides = "#DETAIL_OutputSides #ValueText"
    job_output_destination = "#DETAIL_mediaOutput #ValueText"
    job_collate = "#DETAIL_collate #ValueText"
    job_file_name = "#DETAIL_FileName #ValueText"
    job_file_type = "#DETAIL_FileType #ValueText"
    job_thumbnail = "#thumbImageAreaLoader"


    mismatch_hold_button = "#pauseBtn"
    mismatch_load_button = "#loadBtn"
    mismatch_cancel_button = "#cancelBtn"
    mismatch_printanyway_button = "#continueBtn"
    mismatch_options_button = "#CollapseButton"

    # Job History more actions
    job_history_more_actions_button = "#jobHistoryMoreActions"
    job_history_more_actions_jobs_settings_button = "#jobSettingsButton"
    job_history_jobs_settings_view = "#jobQueueAppSettingsPageMenuListListView" #Confirm
    job_history_jobs_settings_scroll_bar = "#jobQueueAppSettingsPageMenuListListViewverticalLayoutScrollBar" # Confirm
    job_history_jobs_settings_view_list = "#jobQueueAppSettingsPageMenuListListViewlist1" #Confirm
    job_history_jobs_settings_view_list_scroll_bar = "#jobQueueAppSettingsPageMenuListListViewlist1ScrollBar" # Confirm
    job_history_jobs_settings_close_button = "#closeButton"
    cancel_all_jobs_button = "#cancelAllJobsButton"
    cancel_all_yes_button = "#cancelAllYesButton"

    # Jobs Settings controls.
    jobs_settings_hide_deleted_jobs = "#hideDeletedJobsMenuSwitch"
    jobs_settings_cancel_jobs_on_hold = "#cancelJobsOnHoldMenuSpinBox"
    jobs_settings_job_recovery_mode = "#jobRecoveryModeComboBox"
    jobs_settings_job_recovery_mode_settings = "#jobRecoveryModeSettingsComboBox"
    jobs_settings_job_recovery_mode_options_view = "#jobRecoveryModeComboBoxpopupList"
    jobs_settings_job_recovery_mode_put_on_hold = "#ComboBoxOptionsputOnHold"
    jobs_settings_job_recovery_mode_cancel = "#ComboBoxOptionscancel"
    jobs_settings_hold_jobs_for_manual_release = "#holdJobForManualReleaseMenuSwitch"
    jobs_settings_reprint_resend_jobs_enabled = "#reprintResendJobsEnabledMenuSwitch"
    jobs_settings_reprint_resend_jobs_enabled_confirmation_dialog = "#reprintResendJobsEnabledConfirmationDialog"
    jobs_settings_reprint_resend_jobs_enabled_confirmation_dialog_no_button = "#noButton"
    jobs_settings_reprint_resend_jobs_enabled_confirmation_dialog_yes_button = "#yesButton"
    jobs_settings_promote_to_interrupt_print_jobs_enabled = "#enableInterruptJobMenuSwitch"

    job_details_load_button = "#loadPaperButton"
    job_details_printanyway_button = "#printAnywayButton"
    job_details_load_option_not_available_ok_button = "#okButton"
    job_details_options_button = "#dropDownButton"

    notification_center_job_notification = "NotificationView #statusNotificationView #notificationRowTitle"

    # Mismatch
    size_mismatch_title = "#mediaMismatchSizeFlow #TitleText SpiceText[visible=true]"
    size_mismatch_cancel_option3 = "#Option3" # for Beam
    no_substrate_mismatch_title = "#mediaLoadFlow #TitleText SpiceText[visible=true]"
    type_mismatch_title = "#mediaMismatchTypeFlow #TitleText SpiceText[visible=true]"
    no_paper_mismatch_title = "#allSourcesEmptyPromptWindow #TitleText SpiceText[visible=true]"

    # Risk of Paper Jam
    risk_of_paper_jam = "#printingUserInterventionFlow_Message"
    risk_of_paper_jam_resume = "#printingUserInterventionFlow_Message #Resume"
    risk_of_paper_jam_resolve = "#printingUserInterventionFlow_Message #Resolve"

    # USB StoreJob  alerts
    job_storage_format_usb_alert = "#jobStorageFormatUsb"
    job_storage_format_usb_alert_cancel_button = '#jobStorageFormatUsbCancel'
    job_storage_format_usb_alert_remove_usb_title = '#titleObject'

    interrupt_button = "#interruptJob"
    confirm_button = "#confirmButton"
    promote_JobModal = "#promoteJobModal"
    promote_Job = "#promoteJob"
    promote_Job_NoButton = "#promoteJobNoButton"
    job_Promote_And_Interrupt_Modal = "#jobPromoteAndInterruptModal"
    jobQueueApp_ApplicationStackView = "#JobQueueAppApplicationStackView"
    close_button = "#closeButton"

    # Print Around
    hold_button = "#holdButton"