class MediaAppWorkflowObjectIds:

    # Media tab
    MEDIA_GRID_TAB_LAYOUT = "#mediaGridTabLayout"
    OUTPUT_OPTIONS = "#outputsCardTab"
    SUBSTRATE_SOURCE = "#inputsCardTab"
    SELECT_MEDIA_SOURCE = "#selectMediaSourceContent"
    ROLL_CARD = "#inputsCardContent"

    # Grid buttons
    MEDIA_GRID_CONTINUE_BUTTON = "#mediaGridTabLayout #continueButton"
    MEDIA_GRID_CANCEL_BUTTON = "#mediaGridTabLayout #cancelButton"

    # Media cards
    STACKER_CARD = "#outputCardContent_Stacker"
    FOLDER_CARD = "#outputCardContent_Folder"
    BASKET_CARD = "#outputCardContent_Basket"
    
    # Media info buttons
    TYPE_SETTINGS = "#typeSettingsTextImageBranch"
    TYPE_SETTINGS_VALUE = "#typeSettingsTextImageBranch SpiceText[visible=true]"
    LENGTH_SETTINGS = "#lengthSettingsTextImageBranch"
    LENGTH_SETTINGS_VALUE = "#lengthSettingsTextImageBranch SpiceText[visible=true]"
    WIDTH_SETTINGS = "#widthSettingsTextImageBranch"
    WIDTH_SETTINGS_VALUE = "#widthSettingsTextImageBranch SpiceText[visible=true]"
    SIZE_SETTINGS = "#sizeSettingsTextImageBranch"
    SIZE_SETTINGS_VALUE = "#sizeSettingsTextImageBranch SpiceText[visible=true]"
    TYPE_RADIO_BUTTON = "#typeRadioButtonModel{0}"
    LENGTH_RADIO_BUTTON = "#lengthRadioButtonModel{0}"
    LOADING_OPTIONS_SETTINGS = "#loadingOptionsSettingsTextImageBranch"
    LOADING_METHOD_SETTINGS = "#loadMethodSettingsTextImageBranch"
    LOADING_METHOD_SETTINGS_VALUE = "#loadMethodSettingsTextImageBranch SpiceText[visible=true]"
    LOADING_METHOD_RADIO_BUTTON = "#loadMethodRadioButtonModel{0}"
    TILING_OPTIMIZATION_SWITCH_LOAD_WORKFLOW = "#tilingOptimizationSwitchModel"
    TILING_OPTIMIZATION_SWITCH_MODIFY_OPTION = "#tilingOptimizationSwitch #tilingOptimizationSwitchModel"
    LOADING_ACCESSORY_SWITCH_LOAD_WORKFLOW = "#accessorySwitchModel"
    LENGTH_TEXT_INPUT = "#lengthSpinBoxModel1 #SpinBoxTextInput"
    WIDTH_TEXT_INPUT = "#widthSpinBoxModel0 #SpinBoxTextInput"
    ENTER_KEY_DECIMAL_PAD = "#enterKeyPositiveDecimalKeypad"
    ENTER_KEY_INTEGER_PAD = "#enterKeyPositiveIntegerKeypad"
    
    # Media input card details
    DETAIL_INFO_VERTICAL_LAYOUT = "#DetailInfoverticalLayout" # Screen containing media details
    MEDIA_INPUT_CARD = "#mediaInputCard"
    MEDIA_INPUT_CARD_TYPE = "#mediaInputCard #inputCardContent #rowBlockB #titleSmallItem"
    CLOSE_INPUT_CARD = "#inputCloseAction"
    MEDIA_TYPE_VALUE = "#typeNameValue SpiceText[visible=true]"
    WIDTH_TYPE_VALUE = "#widthNameValue SpiceText[visible=true]"
    SIZE_TYPE_VALUE = "#sizeNameValue SpiceText[visible=true]"
    LENGTH_TYPE_VALUE = "#lengthNameValue SpiceText[visible=true]"
    CALIBRATION_STATUS_TYPE_VALUE = "#calibrationStatusNameValue SpiceText[visible=true]"
    RIGHT_EDGE_POSITION = "#rightEdgePositionNameValue"
    RIGHT_EDGE_POSITION_VALUE = "#rightEdgePositionNameValue SpiceText[visible=true]"
    RIGHT_EDGE_POSITION_SPINBOX_INCREASE_BUTTON = "#rightEdgePositionSpinBox #upButtonContainer"
    RIGHT_EDGE_POSITION_SPINBOX_DECREASE_BUTTON = "#rightEdgePositionSpinBox #downButtonContainer"
    SKEW_SPINBOX = "#skewThresholdSpinBoxModel"

    # Media buttons
    LOAD_WIDGET                     = "#inputCardContent"
    LOAD_BUTTON_INPUT_CARD          = "#loadButton"
    UNLOAD_BUTTON_INPUT_CARD        = "#unloadButton"
    LOAD_BUTTON                     = "#mediaInputCardDetail #loadButton"
    UNLOAD_BUTTON                   = "#mediaInputCardDetail #unloadButton"
    DONE_BUTTON                     = "#doneAction"
    MOVE_AND_CUT_BUTTON             = "#moveCutButton"
    CONTINUE_ACTION                 = "#continueAction"
    LOAD_ANOTHER_ACTION             = "#loadAnotherAction"
    CUT_BUTTON_ACTION               = "#cutAction"
    MORE_OPTIONS_BUTTON             = "#mediaInputCardDetail #moreOptions"
    MODIFY_BUTTON                   = "#mediaInputFooter #modifyButton"
    STACKER                         = "#outputCardContent_StackerverticalLayoutScrollBar"
    FOLDER                          = "#outputCardContent_FolderverticalLayoutScrollBar"
    WIDGET_LOAD_UNLOAD_BUTTON       = "#jobQueueBySubstrateWidget #loadUnloadButton"
    SUBSTRATE_WIDGET                = "#jobQueueBySubstrateWidget"
    BARCODE_BUTTON                  = "#barcodeButton"
    
    # JAM Resolution Workflow
    JAM_HOW_TO_FIX_BUTTON = "#howToSolveAction"
    INPUT_CARD_CONTENT = "#inputCardContent"
    BATCH_LOAD_DETAILS_INPUT_CARD_CONTENT = "#loadRollFlow_batchLoadDetails #inputsCardContent"
    #Cancel Media Workflow
    CANCEL_MEDIA_LOAD_BUTTON        = "#cancelAction"
    CANCEL_MEDIA_LOAD_YES_BUTTON    = "#loadRollFlow_cancel #cancelAction"
    CANCEL_MEDIA_LOAD_NO_BUTTON     = "#loadRollFlow_cancel #noAction"

    UNHAPPY_PATH_TITTLE = "#troubleShootingUnhappyPathView #titleObject"
    UNHAPPY_PATH_DESCRIPTION = "#troubleShootingUnhappyPathView #alertDetailDescription #contentItem"
    UNHAPPY_PATH_OKBUTTON = "#troubleShootingUnhappyPathView #AlertFooter #okButton"

    ######### Views ###################
    # Move and Cut Workflow
    view_moveAndCutMediaFlow_ready = "#moveAndCutMediaFlow_ready"
    view_moveAndCutMediaFlow_preparing = "#moveAndCutMediaFlow_preparing"
    # Jam Resolution Workflow 
    load_roll_jam = "#loadRollFlow_jamModal"
    load_roll_jam_checking  = "#loadRollFlow_jamChecking"
    load_roll_jam_successfully_solved = "#loadRollFlow_jamSuccessfullySolved"
    load_roll_jam_close = "#loadRollFlow_jamModal #closeButton"
    # Load Roll Workflow
    load_roll_resuming_load_info = "#loadRollFlow_resumingLoadInfo"
    load_roll_resuming_load_info_title = "#loadRollFlow_resumingLoadInfo SpiceText[visible=true]"
    load_roll_resuming_load_info_content_text = "#loadRollFlow_resumingLoadInfo #alertDetailDescription #contentItem"
    load_roll_resuming_load_info_continue = "#loadRollFlow_resumingLoadInfo #continueAction"
    load_roll_ask_media_info = "#loadRollFlow_askMediaInfo"
    load_roll_ask_media_info_title = "#loadRollFlow_askMediaInfo SpiceText[visible=true]"
    load_roll_ask_media_info_continue = "#loadRollFlow_askMediaInfo #continueAction"
    load_roll_ask_media_info_cancel = "#loadRollFlow_askMediaInfo #cancelAction"
    load_roll_error_lateral_media_edge_not_found = "#loadRollFlow_errorlateralMediaEdgeNotFound"
    load_roll_error_lateral_media_edge_not_found_title = "#loadRollFlow_errorlateralMediaEdgeNotFound SpiceText[visible=true]"
    load_roll_error_lateral_media_edge_not_found_content_text = "#loadRollFlow_errorlateralMediaEdgeNotFound #alertDetailDescription #contentItem"
    load_roll_error_lateral_media_edge_not_found_continue = "#loadRollFlow_errorlateralMediaEdgeNotFound #continueAction"
    load_roll_ask_media_info_roll_width = "#loadRollFlow_askMediaInfoRollWidth"
    load_roll_ask_media_info_roll_width_continue = "#loadRollFlow_askMediaInfoRollWidth #continueAction"
    load_roll_ask_media_info_roll_width_cancel = "#loadRollFlow_askMediaInfoRollWidth #cancelAction"
    load_roll_skew_handling_correcting_manually = "#loadRollFlow_skewHandlingCorrectingManually"
    load_roll_skew_handling_correcting_manually_continue = "#loadRollFlow_skewHandlingCorrectingManually #continueAction"
    load_roll_skew_handling_correcting_manually_title = "#loadRollFlow_skewHandlingCorrectingManually SpiceText[visible=true]"
    load_roll_skew_handling_correcting_manually_video = "#loadRollFlow_skewHandlingCorrectingManually #VideoLayout #VideoItem"
    load_roll_load_recomendation_curing = "#loadRollFlow_errorloadRecomendationCuring"
    load_roll_load_recomendation_curing_skip = "#loadRollFlow_errorloadRecomendationCuring #cancelAction"
    load_roll_load_recomendation_curing_continue = "#loadRollFlow_errorloadRecomendationCuring #continueAction"
    load_roll_load_recommendation_tur = "#loadRollFlow_errorloadRecomendationTur"
    load_roll_load_recommendation_tur_skip = "#loadRollFlow_errorloadRecomendationTur #cancelAction"
    load_roll_load_recommendation_tur_continue = "#loadRollFlow_errorloadRecomendationTur #continueAction"
    roll_and_sheet_load_configuration = "#rollAndSheetLoadConfiguration"
    roll_and_sheet_load_configuration_done = "#rollAndSheetLoadConfiguration #doneButton"
    load_roll_finished = "#loadRollFlow_finished"
    load_roll_finished_ok_btn = "#loadRollFlow_finished #okAction"
    load_roll_finished_continue = "#loadRollFlow_finished #continueAction"
    load_roll_finished_content_image = "#loadRollFlow_finished #wizardCompletionImages SpiceImage"
    load_roll_cancel = "#loadRollFlow_cancel"
    load_roll_cancel_yes_button = "#loadRollFlow_cancel #cancelAction"
    load_roll_feed = "#loadRollFlow_feed"
    load_roll_manual_feed = "#loadRollFlow_feedManual"
    load_roll_manual_feed_continue = "#loadRollFlow_feedManual #continueAction"
    load_roll_manual_feed_with_accessory = "#loadRollFlow_feedWithLoadAccessory"
    load_roll_manual_feed_with_accessory_continue = "#loadRollFlow_feedWithLoadAccessory #continueAction"
    load_roll_remove_loading_accessory = "#loadRollFlow_errorremoveLoadingAccessory"
    load_roll_remove_loading_accessory_continue = "#loadRollFlow_errorremoveLoadingAccessory #continueAction"
    load_roll_winding_direction_undetected = "#loadRollFlow_errorwindingDirNotFound"
    load_roll_winding_direction_undetected_header = "#loadRollFlow_errorwindingDirNotFound SpiceText[visible=true]"
    load_roll_winding_direction_undetected_content = "#loadRollFlow_errorwindingDirNotFound #alertDetailDescription #contentItem"
    load_roll_winding_direction_undetected_skip_button = "#loadRollFlow_errorwindingDirNotFound #yesAction"
    load_roll_winding_direction_undetected_confirm = "#loadRollFlow_errorskipWindingDir"
    load_roll_winding_direction_undetected_confirm_header = "#loadRollFlow_errorskipWindingDir SpiceText[visible=true]"
    load_roll_winding_direction_undetected_confirm_content = "#loadRollFlow_errorskipWindingDir #alertDetailDescription #contentItem"
    load_roll_winding_direction_undetected_confirm_ok_button = "#loadRollFlow_errorskipWindingDir #okAction"
    load_roll_move_front_edge_manually_to_cut_line = "#loadRollFlow_moveFrontEdgeManuallyToCutLine"
    load_roll_move_front_edge_manually_to_cut_line_continue = "#loadRollFlow_moveFrontEdgeManuallyToCutLine #continueAction"
    load_roll_move_front_edge_manually_to_cut_line_title = "#loadRollFlow_moveFrontEdgeManuallyToCutLine SpiceText[visible=true]"
    load_roll_move_front_edge_manually_to_cut_line_video = "#loadRollFlow_moveFrontEdgeManuallyToCutLine #VideoLayout #VideoItem"
    load_roll_wait_for_cover_open_title = "#loadRollFlow_waitForCoverOpen SpiceText[visible=true]"
    load_roll_wait_for_cover_open_video = "#loadRollFlow_waitForCoverOpen #VideoLayout #VideoItem"
    load_roll_wait_for_cover_open_cancel = "#loadRollFlow_waitForCoverOpen #cancelAction"
    load_roll_loading = "#loadRollFlow_load"
    load_roll_checking = "#loadRollFlow_checking"
    load_roll_aligning = "#loadRollFlow_skewHandling"
    load_roll_wait_drawer_open = "#loadRollFlow_waitForDrawerOpen"
    load_roll_batch_load_details = "#loadRollFlow_batchLoadDetails"
    load_roll_open_drawer_warning = "#loadRollFlow_drawerOpenWarning"
    load_roll_reload_media_button = "#continueAction"
    # Size Type (Tray close) prompt
    alert_icon = "#imageObject"
    title_object = "#titleObject"
    ok_button = "#OK"
    modify_button = "#Modify"
    done_button = "#doneButton"
    size_row_textimagebranch = "#sizeSettingsTextImageBranch"
    #Use Another Tray
    use_Another_Tray_Option_Button = "#optionButton"
    use_Another_Tray_Prompt = "#useAnotherTrayPrompt"
    use_Another_Tray_Header = "#useAnotherTrayHeader"
    
    # Staple & Hole punch
    finisher_Staple_Option = "#stapleConfigValue"
    finisher_HolePunch_Option = "#holePunchConfigValue"
    ok_button_constrained_message = "#okButton"
    staple_noneRadioButton = "#noneRadioButton"
    staple_topLeftOnePointAngledRadioButton = "#topLeftOnePointAngledRadioButton"
    staple_topLeftOnePointAnyRadioButton = "#topLeftOnePointAnyRadioButton"
    staple_leftTwoPointsRadioButton = "#leftTwoPointsRadioButton"
    staple_topTwoPointsRadioButton = "#topTwoPointsRadioButton"
    staple_topRightOnePointAngledRadioButton = "#topRightOnePointAngledRadioButton"
    staple_topRightOnePointAnyRadioButton = "#topRightOnePointAnyRadioButton"
    staple_rightTwoPointsRadioButton  = "#rightTwoPointsRadioButton"
    staple_topAnyOnePointAnyRadioButton = "#topAnyOnePointAnyRadioButton"
    staple_leftTwoPointsAnyRadioButton = "#leftTwoPointsAnyRadioButton"
    holepunch_none_radio_button = "#noneRadioButton"
    holepunch_left_two_radioButton = "#leftTwoPointDinRadioButton"
    holepunch_right_two_radioButton ="#rightTwoPointDinRadioButton"
    holepunch_top_two_radioButton = "#topTwoPointDinRadioButton"
    holepunch_bottom_two_radioButton = "#bottomTwoPointDinRadioButton"
    holepunch_left_four_radioButton = "#leftFourPointDinRadioButton"
    holepunch_right_four_radioButton = "#rightFourPointDinRadioButton"
    holepunch_top_four_radioButton = "#topFourPointDinRadioButton"
    holepunch_config_scrollbar = "#holePunchConfigViewScrollBar"
    holepunch_config_view = "#holePunchConfigView"
    holepunch_four_point_RadioButton = "#fourPointDinRadioButton"
    holepunch_two_point_RadioButton = "#twoPointDinRadioButton"
    holepunch_bottom_two_RadioButton_ViewModel = "#bottomTwoPointDinSettingsRadioButtonViewModel"
    holepunch_four_point_RadioButton_ViewModel = "#fourPointDinSettingsRadioButtonViewModel"
    holepunch_two_point_RadioButton_ViewModel = "#twoPointDinSettingsRadioButtonViewModel"
    
    # Generic Button Object IDs
    button_back = "#BackButton"
    button_home = "#HomeButton"
    button_OK   = "#OKButton"
    
    # Skew acceptance setting
    loading_options_header = "#loadPanelHeader"
    
    # Risk of Paper Jam
    risk_of_paper_jam = "#printingUserInterventionFlow_Message"
    risk_of_paper_jam_resume = "#printingUserInterventionFlow_Message #Resume"
    risk_of_paper_jam_resolve = "#printingUserInterventionFlow_Message #Resolve"

    # Tray
    load_tray_changemedia_modify = "#loadTrayFlow_changemedia #modifyAction"
    load_tray_changemedia_ok = "#loadTrayFlow_changemedia #okAction"
    current_media_type = "#loadTrayFlow_changemedia #LayoutHorizontalIconsGrid #contentItem SpiceText[visible=true]"
    load_tray_askMediaInfo_continue = "#loadTrayFlow_askMediaInfo #continueAction"
    load_tray_askMediaInfo_media_type_value = "#typeSettingsTextImageBranch_2infoBlockRow #contentItem"
    load_tray_askMediaInfo_media_type = "#typeSettingsTextImageBranch_firstinfoBlockRow #contentItem"
    load_tray_askMediaInfo_media_size = "#sizeSettingsTextImageBranch_firstinfoBlockRow #contentItem"
    load_tray_askMediaInfo_media_size_value = "#sizeSettingsTextImageBranch_2infoBlockRow #contentItem"
    load_tray_askMediaInfo_title = "#loadTrayFlow_askMediaInfo SpiceText[visible=true]"
    load_tray_changemedia_title = "#loadTrayFlow_changemedia SpiceText[visible=true]"
    load_tray_changemedia = "#loadTrayFlow_changemedia"
    load_tray_askMediaInfo = "#loadTrayFlow_askMediaInfo"
    alert_tray_overfilled = "#trayOverfilled1Window"

    # Load CTray
    load_ctray_waitForDoorOpenWindow_title = "#loadTrayFlow_waitForDoorOpenWindow SpiceText[visible=true]"
    load_ctray_waitForDoorOpenWindow_video = "#loadTrayFlow_waitForDoorOpenWindow #VideoLayout #VideoItem"
    load_ctray_wait_for_cover_open_cancel = "#loadTrayFlow_waitForDoorOpenWindow #cancelAction"
    load_ctray_changeMedia_continue = "#loadTrayFlow_changemedia #alertDetailDescription #contentItem"
    load_ctray_changemedia_type_list = "#loadTrayFlow_askMediaInfo #typeSettingsTextImageBranch"
    load_ctray_changemedia_family_type_list = "#loadTrayFlow_askMediaInfo #familyTextImageBranch0"
    load_ctray_changemedia_size_list = "#loadTrayFlow_askMediaInfo #sizeSettingsTextImageBranch"

    # Load LTray
    load_ltray_waitForDoorOpen_title = "#loadTrayFlow_waitForDoorOpen SpiceText[visible=true]"
    load_ltray_waitForDoorOpen_video = "#loadTrayFlow_waitForDoorOpen #VideoLayout #VideoItem"
    load_ltray_wait_for_cover_open_cancel = "#loadTrayFlow_waitForDoorOpen #cancelAction"

    # Single Sheet
    load_single_sheet_waitForDoorOpenWindow_title = "#loadSingleSheetFlow_waitForDoorOpen SpiceText[visible=true]"
    load_single_sheet_waitForDoorOpenWindow_video = "#loadSingleSheetFlow_waitForDoorOpen #VideoItem"
    load_single_sheet_wait_for_cover_open_cancel = "#loadSingleSheetFlow_waitForDoorOpen #cancelAction"
    load_single_sheet_ask_media_info = "#loadSingleSheetFlow_askMediaInfo"
    load_single_sheet_ask_media_info_continue = "#loadSingleSheetFlow_askMediaInfo #continueAction"
    load_single_sheet_ask_media_info_cancel = "#loadSingleSheetFlow_askMediaInfo #cancelAction"
    load_single_sheet_loading = "#loadSingleSheetFlow_load"
    load_single_sheet_checking = "#loadSingleSheetFlow_checking"
    load_single_sheet_aligning = "#loadSingleSheetFlow_skewHandling"
    load_single_sheet_finished = "#loadSingleSheetFlow_finished"
    load_single_sheet_finished_continue = "#loadSingleSheetFlow_finished #continueAction"
    load_single_sheet_finished_content_image = "#loadSingleSheetFlow_finished #wizardCompletionImages SpiceImage"
    
    # Booklet Fold and Stitch - Finisher configuration
    menu_button_settings_print_defaultprintoptions_bookletMarkerOption = "#bookletMakerConfigValue"
    bookletNoneOption = "#nonebookletConfigPrint"
    bookletSaddleStichOption = "#saddleStitchbookletConfigPrint"
    menu_button_settings_print_defaultprintoptions_foldOption_noneButton ="#noneButton"
    menu_button_settings_print_defaultprintoptions_foldOption = "#foldConfigValue"
    menu_button_settings_print_defaultprintoptions_vFoldButton = "#vFoldButton"
    menu_button_settings_print_defaultprintoptions_vFoldSpinBox = "#vFoldSpinBox"
    menu_button_settings_print_defaultprintoptions_vFoldSpinBox_upButton = "#vFoldSpinBox #upBtn"
    menu_button_settings_print_defaultprintoptions_vInwardFoldButton = "#vInwardFoldSettingsRadioButton"
    menu_button_settings_print_defaultprintoptions_vOutwardFoldButton ="#vOutwardFoldSettingsRadioButton"
    menu_button_settings_print_defaultprintoptions_backButton = "#BackButton"
    menu_button_settings_print_defaultprintoptions_doneButton ="#doneButton"
    menu_button_settings_print_defaultprintoptions_cFoldButton = "#cFoldButton"
    menu_button_settings_print_defaultprintoptions_cFoldSpinBox = "#cFoldSpinBox"
    menu_button_settings_print_defaultprintoptions_cFoldSpinBox_upButton = "#cFoldSpinBox #upBtn"
    menu_button_settings_print_defaultprintoptions_cInwardTopButton ="#cInwardTopFoldSettingsRadioButton"
    menu_button_settings_print_defaultprintoptions_cInwardBottomButton ="#cInwardBottomFoldSettingsRadioButton"
    menu_button_settings_print_defaultprintoptions_cOutwardTopButton = "#cOutwardTopFoldSettingsRadioButton"
    stapleView = "#stapleConfigValue"
    holePunchView = "#holePunchConfigValue"
    defaultPrintOptionsMenuList = "#defaultPrintOptionsMenuList"
    defaultPrintOptionsMenuListScrollBar = "#defaultPrintOptionsMenuListScrollBar"
    cInwardBottomFoldSettingsRadioButton = "#cInwardBottomFoldSettingsRadioButton"
    foldConfigViewlist = "#foldConfigView"
    foldConfigViewlistScrollBar = "#foldConfigViewScrollBar"
    holepunch_left_four_radioButton = "#leftFourPointDinRadioButton"
    staple_leftTwoPointsRadioButton = "#leftTwoPointsRadioButton"

    #Rotate Off Set
    rotate_off_set_combobox = "#rotateOffsetMenuComboBox"
    rotate_off_set_automatic_option = "#automaticButton"
    rotate_off_set_off_option = "#OffButton"
    rotate_off_set_spice_combobox = "#SettingsSpiceComboBox"
    rotate_off_set_radio_button = "#SpiceRadioButton"
    #Simulator Conf tests 
    menu_button_auto_continue_timeout_none ="#timeWaitForEverButton  #SpiceRadioButton"
    menu_button_auto_continue_timeout_immediate ="#timeImmediateButton #SpiceRadioButton"
    menu_button_override_size_type ="#overrideSizeAndTypeButton #SpiceRadioButton"
    menu_buttoon_image_rotation_setting_left_to_right ="#leftToRightButton  #SpiceRadioButton"
    menu_buttoon_image_rotation_setting_right_to_left="#rightToLeftButton #SpiceRadioButton"
    menu_button_exclusively = "#exclusivelyButton #SpiceRadioButton"
    first_button_="#firstButton #SpiceRadioButton"
    false_button_="#falseButton #SpiceRadioButton"
    true_button_="#trueButton #SpiceRadioButton"
    hide_button ="#hide"
    load_button ="#Load"
    job_Notification_Cancel = "#jobNotificationCancel"
    cancel_Job_Yes_Button = "#cancelJobYesButton"
    foot_rectangle="#footerRectangle"
    tray1_radio_button="#tray-1 #SpiceRadioButton"
    collapse_button = "#CollapseButton"
    option1_button ="#Option1"
    tray1_button = "#tray-1"
    statusbox_block_c ="#statusBoxBlockC #StatusText"
    tray_combobox_options_manual = "#ComboBoxOptionsmanual"
    tray_combobox_options_automatic = "#ComboBoxOptionsautomatic"
    outputBin_combobox = "#outputbinSelectionMenuComboBox"
    tray_outputBin_Settings_auto = "#outputbinSelectionComboBox"
    image_rotation_setting="#imageRotationSettingsTextImage"
    vertical_layout_detail_info = "#DetailInfoverticalLayout"
    right_to_left_rotation_setting ="#rightToLeftButton"
    menu_paper_out_action_text="#defaultText"
    close_button = "#closeButton"
    first_button = "#firstButton"
    false_button = "#falseButton" 
    # Size/Type Prompt configuration
    size_type_config_combobox = "#sizeTypePromptWFMenuComboBox"
    size_type_prompt_do_not_display = "#doNotDisplayButton"
    size_type_prompt_display = "#displayButton"
    spice_radio_button = "#SpiceRadioButton"
    settings_spice_combobox = "#SettingsSpiceComboBox"
    
    # End of Roll
    end_of_roll_screen = "#loadRollFlow_errorendOfRollDetected"
    end_of_roll_header = "#loadRollFlow_errorendOfRollDetected #TitleText SpiceText"
    end_of_roll_content = "#loadRollFlow_errorendOfRollDetected #contentItem"
    end_of_roll_ok_button = "#loadRollFlow_errorendOfRollDetected #acceptAction"

    # Manual Cut Flow
    manual_cut_crop_line_flow_ready = "#manualCutCropLineFlow_ready"
    manual_cut_crop_line_flow_ready_done = "#manualCutCropLineFlow_ready #okAction"
    manual_cut_crop_line_flow_rewinding = "#manualCutCropLineFlow_rewinding"
    stationerydefaultPaperTypeConfigButton = "#stationerydefaultPaperTypeConfig"
    manualFeedMenuSwitch = "#manualFeedMenuSwitch"
    cancel_button = "#cancelButton"
    rotateddefaultPaperSizeConfig_letter_8_dot_5x11_button = "#com_dot_hp_dot_ext_dot_mediaSize_dot_na_letter_8_dot_5x11in_dot_rotateddefaultPaperSizeConfig"
    rotateddefaultPaperSizeConfig_iso_a4_210x297mmButton ="#com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a4_210x297mm_dot_rotateddefaultPaperSizeConfig"
    ecoSMARTLitedefaultPaperTypeConfigButton = "#com_dot_hp_dot_EcoSMARTLitedefaultPaperTypeConfig"
    radio_Button="#SpiceRadioButton"
    cancelOption = "#cancel"
    # Print Options
    print_option_duplex = "#option_duplex"
    print_option_simplex = "#option_simplex"
    # Paper app enhancement 
    tray_config_image = "#trayConfigImage"
    tray_icon = "#trayIcon"
    tray_title_text_header = "#leftBlockObject #titleObject"
    #Alert animation
    animation_image_visible = "#InformationTemplate #imageContainer[visible=true]"
