class SuppliesAppWorkflowUICommonOperationsObjectsIds:
    '''
        Supplies app objects ids add under this class
    '''
    supplies_summary = "#suppliesSummaryView"
    close_button = "#closeButton"
    cartridge_card_widget = "#cartridgesCardsList #cartridgeCard_"
    supplies_widget = "#widgetCardSuppliesApp"
    supplies_widget_scroll = "#HomeScreenView #widgetsLoader #horizontalScroll"
    cartridges_screen = "#Cartridges"
    cartridge_card = "#suppliesSummaryViewscrollTab #cartridgeCard_"
    mono_cartridge_card = "#cartridgeCard_"
    directToCartridge_card = "#directCartridgesView #cartridgeCard_"
    cartridge = " #cartridge"
    cartridge_label_icon = "#cartridge #cartridgeLabelIcon"
    cartridge_info = "#DetailInfoverticalLayout #block1 #spiceCartridge"
    header_text_cartridge= "#DetailInfoverticalLayout #cartridgeDetailsHeaderHeaderView #leftBlockObject SpiceText"
    status_text_cartridge= "#DetailInfoverticalLayout #block2 #rowBlockC #StatusText"
    status_icon = "#DetailInfoverticalLayout #block2 #rowBlockC #StatusIcon"
    installed = "#installed #NameText"
    installed_value = "#installed #ValueText"
    print_bottom_text = "#DetailInfoverticalLayout #FooterView #FooterViewRight #ContentItemText"
    status_text = "#suppliesOtherSuppliesCardContentverticalLayout #block2 #rowBlockC #StatusText"
    status_icon_1 = "#suppliesOtherSuppliesCardContentverticalLayout #block2 #rowBlockC #StatusIcon"
    status_image_container = "#suppliesOtherSuppliesCardContentverticalLayout #block1 #textImageBlock1 #imageContainer"
    black_very_low_action = "#blackVeryLowAction_WFMenuComboBox #SettingsSpiceComboBox #contentItem"
    color_very_low_action = "#colorVeryLowAction_WFMenuComboBox #SettingsSpiceComboBox #contentItem"
    horizontal_scroll_bar = "#horizontalScroll"
    obj_state = "#block2 #rowBlockC #StatusText"
    supplies_scroll_bar = "#suppliesSummaryViewscrollTabhorizontalScroll"
    printhead_card = "#printheadCard_"
    installed_date = "#installedDate #NameText"
    installed_date_value = "#installedDate #ValueText"
    estimated_level = "#estimatedlevel #NameText"
    estimated_level_value = "#estimatedlevel #ValueText"
    manufacturer = "#manufacturer #NameText"
    manufacturer_value = "#manufacturer #ValueText"
    product_name = "#productName #NameText"
    product_name_value = "#productName #ValueText"
    product_number = "#productNumber #NameText"
    product_number_value = "#productNumber #ValueText"
    serial_number = "#serialNumber #NameText"
    serial_number_value = "#serialNumber #ValueText"
    supported_cartridges = "#supportedCartridges #NameText"
    supported_cartridges_value = "#supportedCartridges #ValueText"
    Batch_ID ="#batchId #NameText"
    Batch_ID_value ="#batchId #ValueText"
    status_code = "#statusCode"
    status_code_Value = "#statusCode #ValueText"
    warranty = "#warranty"
    warranty_Value = "#warranty #ValueText"
    Expiration_Date = "#expirationDate "
    Expiration_Date_Value ="#expirationDate #ValueText"
    value_text = "#ValueText"
    stop ="#stop"
    continue_ = "#continue_"
    prompt = "#prompt"
    print_black = "#printBlack"
    manageButton = "#SupplyValidationButton #ButtonControl"
    lowLevelInkAlertsToggle = "#GenericStructureView #suppliesSettingsMenuList #lowOnInkSettingsSwitch #lowOnInkMenuSwitch"
    lowLevelInkAlertsPartnerMenuToggle = "#partnerMenuListListView #lowOnInkSettingsSwitch #lowOnInkMenuSwitch"
    lowLevelInkAlertTitle = "#cartridgeLowFlow1Window #TitleText #titleObject"
    supplyChangeAlertOkButton = "#SuppliesFlowModuleAlert #OK"
    alert = "#statusCenterServiceStackView #statusNotificacionView #notificationRowTitleCollection"
    okButtonAlert = "#bodyLayoutverticalLayout #FooterView #OK #ButtonControl"
    yesButton = "#bodyLayoutverticalLayout #cancelAction #ButtonControl #ContentItem"
    replaceButton = "#supplyValidationFlow_cancelAlteredInstallation #bodyLayout #FooterView #FooterViewRight #ButtonControl"
    home_button_visible = "#HomeButton SpiceText[visible=true]"
    home_button_icon = "#HomeButton #ButtonControlIcon"
    back_button_visible = "#BackButton SpiceText[visible=true]"
    back_button_icon = "#BackButton #ButtonControlIcon"
    statustext = "#suppliesSummaryView #StatusText #statusText"
    curingTemperatureObject = "#widgetsLoader #widgetCardJobQueueApp #jobProgressWidgetContentGrid #jobInfoGridLayout #curingTemperature #textColumn SpiceText[visible=true]"
    supplies_summary_cartridges_header = "#cartridgesCardsViewTabLayoutverticalLayout #SpiceHeaderVar2 #SpiceHeaderVar2HeaderView #SpiceBreadcrumb #textContainer #defaultText"
    supplies_header_title_visible = "#textContainer #defaultText[visible=true]"
    supplies_header_subtitle_visible = "#textContainer #subtitleObject[visible=true]"
    orderHPpart = "#orderHPpart #NameText"
    orderHPpart_value = "#orderHPpart #ValueText"
    approximatePagesRemain = "#approximatePagesRemain #NameText"
    approximatePagesRemain_value = "#approximatePagesRemain #ValueText"
    pagesPrinted = "#pagesPrinted #NameText"
    pagesPrinted_value = "#pagesPrinted #ValueText"
    ink_tanks_screen = "#inkTanksCardsViewTab"
    ink_tank_card = "#inkTankCard_"
    ink_tank_icon = "#inkTank #inkTankLabelIcon"
    recommended_part_number = "#orderPartNumber #NameText"
    recommended_part_number_value = "#orderPartNumber #ValueText"
    supplies_app_cartridge_card_black = "#cartridgeCardView_0"
    supplies_app_cartridge_card_cyan = "#cartridgeCardView_1"
    supplies_app_cartridge_card_magenta = "#cartridgeCardView_2"
    supplies_app_cartridge_card_yellow = "#cartridgeCardView_3"
    cartridge_card_content_plr = "#suppliesCartridgeCardContent #block2 #rowBlockA #grid #infoModelBlockA2infoBlockRow #contentItem"

    # Supplies handling alerts
    # The initial number corresponds to the alert category enumeration that can be found in Alerts.fbs
    white_printhead_required_alert = "#supplyMismatchWhiteRequired"
    white_printhead_required_alert_title = "#supplyMismatchWhiteRequired #TitleText SpiceText"
    white_printhead_required_alert_content = "#supplyMismatchWhiteRequired #alertDetailDescription #contentItem"
    white_printhead_installed_alert = "#supplyMismatchWhiteInstalled"
    white_printhead_installed_alert_title = "#supplyMismatchWhiteInstalled #TitleText SpiceText"
    white_printhead_installed_alert_content = "#supplyMismatchWhiteInstalled #alertDetailDescription #contentItem"
    supply_issues_alert = "#supplyMismatchGeneric"
    supply_issues_alert_title = "#supplyMismatchGeneric #TitleText SpiceText"
    supply_issues_alert_content = "#supplyMismatchGeneric #alertDetailDescription #contentItem"
    replace_maintenance_cartridge_alert = "#maintenanceCartridgeReplacement"
    replace_maintenance_cartridge_alert_title = "#maintenanceCartridgeReplacement #TitleText SpiceText"
    replace_maintenance_cartridge_alert_content = "#maintenanceCartridgeReplacement #alertDetailDescription #contentItem"
    reseat_printheads_alert = "#printheadReseat"
    reseat_printheads_alert_title = "#printheadReseat #TitleText SpiceText"
    reseat_printheads_alert_content = "#printheadReseat #alertDetailDescription #contentItem"
    replace_ph_done_button = "#printheadReplacementFlow_printheadInserted #acceptAction"
    alert_hide_button = "#AlertFooter #FooterView #Hide"

    supply_alert_screen = "#SuppliesFlowModuleAlert"
    supply_alert_screen_title = "#SuppliesFlowModuleAlert #TitleText #TitleTextHeaderView SpiceText[visible=true]"
    supply_alert_screen_hide_btn = "#SuppliesFlowModuleAlert #AlertFooter #Hide #ButtonControl"
    supply_out_of_ink_alert_title = "#outOfInk #TitleText #TitleTextHeaderView SpiceText[visible=true]"
    supply_missing_alert_title = "#cartridgeMissing #TitleText #TitleTextHeaderView SpiceText[visible=true]"
    
    # Supplies replacement flow
    supply_replacement_flow = "#supplyReplacementFlow_howToReplace"
    supply_replacement_flow_continue = "#supplyReplacementFlow_howToReplace #continueAction"
    supply_replacement_finished = "#supplyReplacementFlow_finished"
    supply_replacement_finished_ok = "#supplyReplacementFlow_finished #continueAction"

    # PH replacement flow
    ph_replacement_wait_door_open = "#printheadReplacementFlow_waitForDoorOpen"
    ph_replacement_cancel = "#printheadReplacementFlow_cancel"

    # Buttons
    cartridge_print_button = "#cartridgeCardContentPrintButton"
    cartridge_tab_scroll_bar = "#cartridgesCardsViewScrollverticalScroll"
    print_button = "#printAction"
    cancel_button = "#cancelAction"
    hold_button = "#holdAction"
    replace_button = "#replaceAction"
