class TraysAppWorkflowObjectIds:
    button_modify_in_tray_detail = "#mediaInputFooter #modifyButton"
    button_modify = "#modifyButton"
    button_media_size_settings = "#sizeSettingsTextImageBranch"
    button_media_type_settings = "#typeSettingsTextImageBranch"
    button_tray_configuration_back = "#trayLoadConfiguration #BackButton"
    button_cancel = "#cancelButton"
    custom_done_button = "#customDoneButton"
    button_done = "#doneButton"
    button_tray = "#mediaInputCard"
    radio_button_a5 = "#mediaSize_iso_a5_148x210mm #SpiceRadioButton"
    radio_buttom_a5_rotated = "#mediaSize_com_dot_hp_dot_ext_dot_mediaSize_dot_iso_a5_148x210mm_dot_rotated #SpiceRadioButton"
    radio_custom = "#mediaSize_custom"
    radio_custom_value = "#infoBlockRow #contentItem"
    letter_size = "#mediaSizeRow_na_letter_8_dot_5x11in"
    plain_type = "#mediaTypeRow_stationery"

    view_tray_configuration = "#trayLoadConfiguration"
    view_media_size_selection = "#sizePanelHeader"
    view_media_type_selection = "#mediaTypeListView"
    view_tray_details = "#mediaInputCardDetail"
