from dunetuf.ui.uioperations.WorkflowOperations.SubstrateLibraryAppWorkflowUICommonOperations import SubstrateLibraryAppWorkflowUICommonOperations

class SubstrateLibraryAppWorkflowUIMOperations(SubstrateLibraryAppWorkflowUICommonOperations):
    pass